### ISSUE TITLE
Alternating canonical SMILES for fused ring with N

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1028]
reported by @adalke as part of the discussion of #1022 .
Here's a reproducible (adapted from Andrew's):

```
In [1]: from rdkit import Chem

In [2]: s = 'O[C@H]1CC2CCC(C1)[N@@]2C'

In [3]: m = Chem.MolFromSmiles(s)

In [4]: Chem.MolToSmiles(m,isomericSmiles=True)
Out[4]: 'C[N@]1C2CCC1C[C@@H](O)C2'

In [5]: Chem.MolToSmiles(Chem.MolFromSmiles(_4),isomericSmiles=True)
Out[5]: 'C[N@]1C2CCC1C[C@H](O)C2'

In [6]: Chem.MolToSmiles(Chem.MolFromSmiles(_5),isomericSmiles=True)
Out[6]: 'C[N@]1C2CCC1C[C@@H](O)C2'
```

@NadineSchneider : This is a canonicalization failure, but it may not be completely due to your code. Do you have time to take a look?

**Comment by JamesJeffryes** [comment]
This might be a different issue but I'll report it here because I'm seeing a similar alternating pattern with cys/trans notation in the canonical smiles. Here is an example I found with Virginiamycin M1 from PubChem:
```
In[20]: def show_oscillation(smiles):
...         for i in range(4):
...             mol = Chem.MolFromSmiles(smiles)
...             inchikey = Chem.InchiToInchiKey(Chem.MolToInchi(mol))
...             print(inchikey, smiles)
...             smiles = Chem.MolToSmiles(mol, True)
... 
In[21]: show_oscillation('C[C@@H]1/C=C/C(=O)NC/C=C/C(=C/[C@H](CC(=O)CC2=NC(=CO2)C(=O)N3CCC=C3C(=O)O[C@@H]1C(C)C)O)/C')
DAIKHDNSXMZDCU-FQTGFAPKSA-N C[C@@H]1/C=C/C(=O)NC/C=C/C(=C/[C@H](CC(=O)CC2=NC(=CO2)C(=O)N3CCC=C3C(=O)O[C@@H]1C(C)C)O)/C
DAIKHDNSXMZDCU-UTPZUPKKSA-N C/C1=C\[C@@H](O)CC(=O)Cc2nc(co2)C(=O)N2CCC=C2C(=O)O[C@H](C(C)C)[C@H](C)/C=C/C(=O)NC/C=C/1
DAIKHDNSXMZDCU-FQTGFAPKSA-N C/C1=C/[C@@H](O)CC(=O)Cc2nc(co2)C(=O)N2CCC=C2C(=O)O[C@H](C(C)C)[C@H](C)/C=C/C(=O)NC/C=C/1
DAIKHDNSXMZDCU-UTPZUPKKSA-N C/C1=C\[C@@H](O)CC(=O)Cc2nc(co2)C(=O)N2CCC=C2C(=O)O[C@H](C(C)C)[C@H](C)/C=C/C(=O)NC/C=C/1
```

The InchiKey matches PubChem when the SMILEs from PubChem are first loaded but starts oscillation once the canonical smiles are read back in.

Also occurs with Pectenotoxin 1 & 2 as well as Chivosazole E

**Comment by ricrogz** [comment]
This one had me well entertained for over the weekend :)

First of all, I played a little with the molecule. It turns out the problem can still be simplified a bit:
```python
from rdkit import Chem
smi = 'C[N@]1C[C@@H](O)C1'
def cycle(smiles):
    s = Chem.MolToSmiles(Chem.MolFromSmiles(smiles), isomericSmiles=True)
    print(s)
    return s
s = smi
for _ in range(5):
    s = cycle(s)
----
C[N@]1C[C@H](O)C1
C[N@]1C[C@@H](O)C1
C[N@]1C[C@H](O)C1
C[N@]1C[C@@H](O)C1
C[N@]1C[C@H](O)C1
```
This was useful to discard the fused rings as the source of the problem.

After that, I played a bit with the canonicalizer, and learned that the first chiral atom in a ring gets arbitrarily set to CCW, and then all other chiral centers are adjusted accordingly. This pointed my suspicions towards the chiral nitrogen. I reordered the SMILES string so that the N atom was first, and that caused the first roundtrip to match the initial chiralities (although the atoms were reordered according to the canonicalization).

After some more investigation and debugging, I found the problem: the SMILES parser and the writer use different criteria to decide which chiral atoms need to be flipped. This caused the Nitrogen atom to have its chirality flipped at parsing, then, at writing, it was canonicalized to CCW, transferring the flip to the C atom, and so on. Using the same at parsing and writing seems to solve this problem.
