### ISSUE TITLE
Remove duplicates doesn't work on first column in rdkit.Dbase.DbUtils.GetData

### ISSUE THREAD

**Issue by gedeck** [rdkit/rdkit#1082]
While increasing test coverage on the rdkit.Dbase Python code, I found that the removeDups argument of the GetData function only works for column numbers greater 0. The fix is trivial, however before I change it, I need to know if this was intentional or not.

**Comment by greglandrum** [comment]
It's "more or less intentional", but it certainly doesn't need to stay as it is.
This is old code and the usual way we used to build databases is that the first column was always a key, so you never needed to worry about duplicates.
Allowing removing dupes in column zero will not break anything, so I'll fix this.
