### ISSUE TITLE
ValueError: Sanitization error: Can't kekulize mol

### ISSUE THREAD

**Issue by yccai** [rdkit/rdkit#1397]
This is  my code. I want to change two bonds C-O to C=O. But the code stop at the step "SanitizeMol".
```
from rdkit import Chem
from rdkit.Chem import AllChem

smi = 'OC1=CC(C2=CC(O)=C(O)N=C2O)=C(O)N=C1O'
mol = Chem.MolFromSmiles(smi)
Idx = [9, 17]
for atomIdx in Idx:
    for atom in mol.GetAtomWithIdx(atomIdx).GetNeighbors():
        Neighbors = atom.GetIdx()
        atom.SetNumExplicitHs(0)
        print Neighbors
    bond = mol.GetBondBetweenAtoms(atomIdx, Neighbors)
    bondIdx = bond.GetIdx()
    bond.SetBondType(Chem.rdchem.BondType.DOUBLE)
    print bondIdx
    Chem.SanitizeMol(mol,Chem.SanitizeFlags.SANITIZE_ADJUSTHS)
    Chem.Kekulize(mol, clearAromaticFlags=True)
    newmol = Chem.MolToSmiles(mol,kekuleSmiles=True)
    print newmol
```
Thank you very much!

**Comment by greglandrum** [comment]
When you make that change you change the electron counts in the aromatic rings from 6 to 5 (the exocyclic double bond to an O "removes" that carbon's electron from the count) and produce a ring that cannot be converted to a Kekule form, that explains the error:
`ValueError: Sanitization error: Can't kekulize mol.  Unkekulized atoms: 4 5 6 10 11`
The RDKit's aromaticity model is described here: http://rdkit.org/docs/RDKit_Book.html#aromaticity

In order to fix this, you need to tell the code that the aromatic N has a nitrogen on it using the `Atom` method `SetNumExplicitHs()`: `m.GetAtomWithIdx(4).SetNumExplicitHs(1)`

Coding the tautomer shift that you are doing here may be easier to do using a reaction, but that may produce more outputs than you like.

**Comment by yccai** [comment]
So complex the aromaticity is.  I try as you say and it runs. But the code does't produce what I want, a little difference.

**Comment by greglandrum** [comment]
If you post what the difference is we may be able to address it.

**Comment by yccai** [comment]
This is the product I want. 
true = 'O=C1N=C([O-])C(=C2C=C(O)C(=O)N=C2[O-])C=C1O'
This is the predicted product:
pred = 'O=C1N=C(O)C(C2C=C(O)C(=O)N=C2O)C=C1O'
Thank you very much!

**Comment by greglandrum** [comment]
Ok, the predicted product has more changes than what you show above:
- You've got a double bond between the rings that you need to add
- You've got charges on the O atoms that are close to the ring fusion that you need to add by calling SetFormalCharge on the atoms.

This is now considerably more complicated than the "simple" tautomer shift you were doing before; maybe it would help if you describe why you're trying to make these changes.

**Comment by yccai** [comment]
Thanks for your answer very much. Actually, it is a reaction extracted from database: Alcohol Oxidation. In this reaction, two alcohol are changed to carbonyl group. I just write my code in order to produce the product. Maybe the event that single bond is changed to double  bond is another procedure, not included in Alcohol Oxidation.

**Comment by tentrillion** [comment]
It looks like your reaction is much more complex than a simple alcohol
oxidation.  It's more akin to a quinol oxidation to a quinone, but given
that your system is a two-ring biphenyl instead of a simple single-ring, it
is actually more complex than even that.

Simple alcohol oxidation reactions can be defined using SMARTS; see this
rdkit tutorial if you haven't already:
https://github.com/rdkit/rdkit-tutorials/blob/master/notebooks/003_SMARTS_ReactionsExamples.ipynb

However, your more complex oxidation would need a considerably more complex
SMARTS for defining a reaction.  The aromaticity of every ring atom changes
during the reaction!  Here's the SMARTS that I came up with.

*from rdkit import Chem*
*from rdkit.Chem import Draw*
*from rdkit.Chem.Draw import IPythonConsole*
*from rdkit.Chem import AllChem*

*IPythonConsole.use_SVG = True*

*smi = 'OC1=CC(C2=CC(O)=C(O)N=C2O)=C(O)N=C1O'*
*reactant = Chem.MolFromSmiles(smi)*
*biphenyl_quinol_oxidation_smarts = '''*
*[a:1]1@[a:2]@[a:3](-[O:13])@[a:4]@[a:5]@[a:6]1-[a:7]2@[a:8]@[a:9]@[a:10](-[O:14])@[a:11]@[a:12]2>>*
*[A:1]1=[A:2]-[A:3](=[O:13])-[A:4]=[A:5]-[A:6]1-[A:7]2-[A:8]=[A:9]-[A:10](=[O:14])-[A:11]=[A:12]2*
*'''.strip('\n')*

*biphenyl_quinol_ox =
AllChem.ReactionFromSmarts(biphenyl_quinol_oxidation_smarts)*

*prod = biphenyl_quinol_ox.RunReactants((reactant, ))[0][0]*
*Chem.SanitizeMol(prod)*
*prod*

**Comment by tentrillion** [comment]
Re-writing the comment in Github instead of by email so Markdown works properly.

It looks like your reaction is much more complex than a simple alcohol
oxidation.  It's more akin to a quinol oxidation to a quinone, but given
that your system is a two-ring biphenyl instead of a simple single-ring, it
is actually more complex than even that.

Simple alcohol oxidation reactions can be defined using SMARTS; see this
rdkit tutorial if you haven't already:
https://github.com/rdkit/rdkit-tutorials/blob/master/notebooks/003_SMARTS_ReactionsExamples.ipynb

However, your more complex oxidation would need a considerably more complex
SMARTS for defining a reaction.  The aromaticity of every ring atom changes
during the reaction!  Here's the SMARTS that I came up with.

```python
    from rdkit import Chem
    from rdkit.Chem import Draw
    from rdkit.Chem.Draw import IPythonConsole
    from rdkit.Chem import AllChem

    IPythonConsole.use_SVG = True

    smi = 'OC1=CC(C2=CC(O)=C(O)N=C2O)=C(O)N=C1O'
    reactant = Chem.MolFromSmiles(smi)
    biphenyl_quinol_oxidation_smarts = '''
    [a:1]1@[a:2]@[a:3](-[O:13])@[a:4]@[a:5]@[a:6]1-[a:7]2@[a:8]@[a:9]@[a:10](-    [O:14])@[a:11]@[a:12]2>>
    [A:1]1=[A:2]-[A:3](=[O:13])-[A:4]=[A:5]-[A:6]1-[A:7]2-[A:8]=[A:9]-[A:10](=[O:14])-[A:11]=[A:12]2
    '''.strip('\n')

    biphenyl_quinol_ox =
    AllChem.ReactionFromSmarts(biphenyl_quinol_oxidation_smarts)

    prod = biphenyl_quinol_ox.RunReactants((reactant, ))[0][0]
    Chem.SanitizeMol(prod)
    prod
```

**Comment by yccai** [comment]
Thanks very much! I have see this rdkit tutorial about SMARTS and get your meaning. But the SMARTS is so complex to define my reaction. Is there any way to generate a SMARTS easily? Need I manually write out the SMARTS?

**Comment by greglandrum** [comment]
To be fair, what you're trying to do is rather complex.

The easiest way I know of to generate these reaction SMARTS, or at least to get started, is to draw a reaction in an editor like Marvin Sketch, do the mapping there, and then copy the reaction as SMARTS.

For this reaction:
![image](https://cloud.githubusercontent.com/assets/540511/25216652/d316af5a-25a3-11e7-8a8c-0f618541e7f2.png)
Marvin gives me this SMARTS:
```
[#8:2]-[c:3]1[c:4][c:5]([c:15](-[#8:16])[n:17][c:18]1-[#8:1])-[c:6]1[c:7][c:8](-[#8:9])[c:10](-[#8:11])[n:12][c:13]1-[#8:14]>>[#8:9]-[#6:8]-1=[#6:7]-[#6:6](-[#6:13](-[#8-:14])=[#7:12]-[#6:10]-1=[O:11])=[#6:5]-1-[#6:4]=[#6:3](-[#8:2])-[#6:18](=[O:1])-[#7:17]=[#6:15]-1-[#8-:16]
```

**Comment by yccai** [comment]
This is a good idea to generate a SMARTS. I can try it. Thank you very much.
