### ISSUE TITLE
problem with regiochemistry

### ISSUE THREAD

**Issue by ditti2** [rdkit/rdkit#1416]
It seems rdkit changes regiochemistry 
I use version 2017.03.1 and obtain the following:

from rdkit import Chem
smiles = 'CCCO\C(=C/c1ccccc1)/C(\OCC)=C\c1ccccc1'

mol = Chem.MolFromSmiles(smiles)
print Chem.MolToSmiles(mol, isomericSmiles = True)
CCCOC(=C\c1ccccc1)/C(=C/c1ccccc1)OCC

seems the obtained regiochemstry is different for the input, am I right?

of note, everything seems to be OK, when starting from another representation of input smiles, i.e. smiles = 'CCCO\C(=C/c1ccccc1)\C(\OCC)=C/c1ccccc1'

Kind regards,
Piotr

**Comment by greglandrum** [comment]
There is a bug here, but it's not exactly what you're reporting. The input you have provided is ambiguous - one of the double bonds has conflicting information provided about the stereochemistry - and the RDKit should be warning you about this (or perhaps raising an error, I need to think about that).

The problem is that you've provided the directionality of every single bond around the double bonds of the molecule and that the specifications disagree with each other.

A simpler example may help make the problem clearer:
```
In [27]: m = Chem.MolFromSmiles(r'C(=C/C)/C')

In [28]: for b in m.GetBonds():
    ...:     if b.GetBondType() == Chem.BondType.DOUBLE: print(b.GetStereo())
    ...:     
STEREOZ

In [29]: m = Chem.MolFromSmiles(r'C\C=C/C')

In [30]: for b in m.GetBonds():
    ...:     if b.GetBondType() == Chem.BondType.DOUBLE: print(b.GetStereo())
    ...:     
STEREOZ

In [33]: m = Chem.MolFromSmiles(r'C(/C)=C/C')

In [34]: for b in m.GetBonds():
    ...:     if b.GetBondType() == Chem.BondType.DOUBLE: print(b.GetStereo())
    ...:     
STEREOZ
```
So `C\C=C/C`, `C(=C/C)/C`, and `C(/C)=C/C` all correspond to the same molecule (the cis version of 2-butene). This is perhaps a "bit" counterintuitive.

The specific problem in your SMILES is here:

```
CCCO\C(=C/c1ccccc1)/C(\OCC)=C\c1ccccc1
    ^              ^  ^
    1              2  3
```
You can fix it by either flipping the direction of the bond labelled `2`:
```
In [42]: m = Chem.MolFromSmiles(r'CCCO\C(=C/c1ccccc1)\C(\OCC)=C\c1ccccc1')

In [43]: for b in m.GetBonds():
    ...:     if b.GetBondType() == Chem.BondType.DOUBLE: print(b.GetStereo())
    ...:     
STEREOZ
STEREOZ

In [44]: print(Chem.MolToSmiles(m,isomericSmiles=True))
CCCOC(=C\c1ccccc1)/C(=C/c1ccccc1)OCC
```
or by just removing that redundant piece of information completely (this is what I would suggest):
```
In [45]: m = Chem.MolFromSmiles(r'CCCO\C(=C/c1ccccc1)C(\OCC)=C\c1ccccc1')

In [46]: for b in m.GetBonds():
    ...:     if b.GetBondType() == Chem.BondType.DOUBLE: print(b.GetStereo())
    ...:     
STEREOZ
STEREOZ

In [47]: print(Chem.MolToSmiles(m,isomericSmiles=True))
CCCOC(=C\c1ccccc1)/C(=C/c1ccccc1)OCC
```
Note that, as the canonical SMILES shows, the coupling of the two double bonds actually allows the full stereochemistry to be expressed by only describing the directionality of three of the single bonds.

I think it would be helpful for the RDKit to raise a warning when ambiguous input like this is provided. I will look into that.

**Comment by ditti2** [comment]
thank you for explanation
