### ISSUE TITLE
off-the-shelf tools

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1429]
Hello,
I thing that one missing piece in rdkit is a collection of ready-to-use
community contributed scripts.
I think this is the strength of open babel, for example
(they don't have scripts, but OB can do many things without any programming
out of the box).
I mean, OK with rdkit you can program everything.
But, when I am working, I don't want to reinvent the wheel.
If someone has done it once, why should I do it a second time?
I think we should accept and encourage such user contributions.
I might contribute some myself.
Nowadays, I am not worried about having to program something.
I am more worried about the time it takes to validate that something
is done correctly.
Regards,
F.

**Comment by greglandrum** [comment]
I think this makes sense, thanks for suggesting it.  There are a small number of useful scripts in the `$RDBASE/Projects` directory, but that's not the best location and they aren't easy to find.
A good place for these would be the `$RDBASE/Scripts` directory, which needs to be cleaned out (I will get on that).

I would like to see testing code submitted with the scripts so that we can be sure that they actually work. @gedeck probably has some ideas on how to do this that are better than what's currently being done.

**Comment by UnixJunkie** [comment]
Not really an issue, and old so closing.
