### ISSUE TITLE
'module' object has no attribute 'CalcNumSpiroAtoms'

### ISSUE THREAD

**Issue by mostafachatillon** [rdkit/rdkit#1499]
**Description:**

- RDKit Version:  AttributeError: 'module' object has no attribute '__version__'
- Platform: Ubuntu 14.04

Installation from repositories:

```sudo apt-get install python-rdkit librdkit1 rdkit-data```

see: http://www.rdkit.org/docs/Install.html

```
>>> import rdkit.Chem.rdMolDescriptors
>>> rdkit.Chem.rdMolDescriptors.CalcNumSpiroAtoms()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'CalcNumSpiroAtoms'

```
When I type:
```>>> dir(rdkit.Chem.rdMolDescriptors) ```

CalcNumSpiroAtoms is absent, but it should be between CalcNumSaturatedRings and CalcTPSA.

**Comment by greglandrum** [comment]
The version of the RDKit that is provided by Ubuntu tends to be fairly old and is not updated to add new features during the life of the Ubuntu release. In this case you are using a version that was released before the `CalcNumSpiroAtoms()` descriptor was added.

The most straightforward fix is to use the anaconda python distribution instead of the Ubuntu Python version. Installing the RDKit in anaconda Python is a one-liner.

Alternatively you would likely need to build the RDKit yourself.
