### ISSUE TITLE
Request:  Build RDKit with more numpy builds

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#1518]
**Description:**

- RDKit Version: 2017.09
- Platform: All

Newer scikit learns and other packages (py-xgboost) are built with newer numpy packages.

numpy 1.12
numpy 1.13

It might be nice to start making conda builds targeting these.

On windows, there is an additional dependency for boost 1.61 which isn't captured in our naming system:

rdkit-2017.09.1.dev20170530-**np111**py35_1.tar.bz2

```
Your code sample here
```

**Comment by greglandrum** [comment]
I've setup the development branch of the conda-rdkit project (https://github.com/rdkit/conda-rdkit/tree/development) to require numpy >=1.11 instead of specifically requiring 1.11.
I've done a bit of testing with this and it seems to work, so when I do the builds for 2017.03.4 we can give that a try.

Please try pulling the linux builds from my conda channel: 'conda install -c greglandrum rdkit'. Those are still 2017.03.3, but they've been done with the numpy >= 1.11 dependency.

**Comment by bp-kelley** [comment]
I'll do the builds in a few days and see if I can get them working with
xgboost (the bigger issue will be boost here I think)

**Comment by greglandrum** [comment]
What's the boost problem?

**Comment by bp-kelley** [comment]
xgboost is built on boost and the default packages are not compatible (they use 1.61).  It appears conda understands python and numpy versions, I'm unsure if it really understands boost versions.  I'll have to experiment.  I.e. do we need to put boost in the conda name as well as numpy and the python version.

**Comment by greglandrum** [comment]
I've done some testing with conda, the rdkit, and boost 1.61 and haven't had problems with it. I was thinking of updating there too

**Comment by rvianello** [comment]
@bp-kelley as of today I don't think encoding the dependency from boost or other components in the package name would be useful/necessary, as this is exactly what conda-build aims at supporting starting from version 3, where the build string is extended to by default include (in addition the usual pyXY and npXYZ elements) a hash of various recipe info and metadata and this way uniquely identify each build variant with a different package filename (e.g. rdkit-2017.03.3-np111py36**h70f90af**_1.tar.bz2).

https://conda.io/docs/building/variants.html

**Comment by ericmjl** [comment]
May I ask what the status of this is please?

I've been having trouble using RDKit in my project conda environment because it is built with a lower `numpy` version, which conflicts with Theano. It's a mental hassle to switch between two different environments as well, and I'd prefer to avoid that if possible.
