### ISSUE TITLE
How to run in spyder ?

### ISSUE THREAD

**Issue by hcji** [rdkit/rdkit#1542]
I have install following the description, and I can activate environment and import rdkit in with command lines. But, I prefer use python with spyder IDE, can I achieve this ?

**Comment by rvianello** [comment]
yes, it should be in general possible, but you need to make sure that rdkit and the application software (spyder, in the present case) are both installed in the same python environment (instead of for example having spyder installed into an anaconda root environment, and rdkit living inside a dedicated and separate environment that is not visible to the root one).
