### ISSUE TITLE
"import rdkit" ends with failure (missing DLLs) on Windows, even after installation of VC++ advised in tutorial 

### ISSUE THREAD

**Issue by karolbadowski** [rdkit/rdkit#1610]
Hello.
I have windows 7.
I have installed anaconda 32 bit for python 2.7.
I have installed boost.
I have installed vc++ as advised in tutorial.
I have installed rdkit with anaconda, using: 
    conda create -c rdkit -n my-rdkit-env rdkit
I have activated the environment, using:
   activate my-rdkit-env

I have started console python.
The command:
import rdkit
fails with prompt about missing dlls, but with no specification what dlls are missing exactly.

When I start PyCharm from opened envelope, I can see syntax hints of the rdkit library, but when I try to execute any script, it fails on import of rdkit.

I have googled for similar problems. For someone, the paths were missing but for me 
os.environ["PATH"] contains what was missing for that person:

C:\ANACONDA\envs\my-rdkit-env
C:\ANACONDA\envs\my-rdkit-env\Library\mingw-w64\bin
C:\ANACONDA\envs\my-rdkit-env\Library\usr\bin
C:\ANACONDA\envs\my-rdkit-env\Library\bin
C:\ANACONDA\envs\my-rdkit-env\Scripts

Advice that would help me identify what dlls are missing would be very appreciated.

`Traceback (most recent call last):
  File "C:/Users/M260280/PycharmProjects/ExcerciseProject/main.py", line 5, in <module>
    import rdkit
  File "C:\ANACONDA\envs\my-rdkit-env\lib\site-packages\rdkit\__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: DLL load failed: The specified module could not be found.`

Thank you very much in advance for your advice/help/guidance.

**Comment by ClinuxMDL** [comment]
Please check your Rdkit package in which environment of python in Anaconda. Then change your system PATH about python in your windows PC. For example,  1) C:\Anaconda3\envs\py35; 2) C:\Anaconda3\envs\py35\Library\bin; 3) C:\Anaconda3\envs\py35\Scripts. It can solve  the issue of "ImportError: DLL load failed: The specified module could not be found.".

**Comment by cuongqn** [comment]
It seems like remove the period `.` before `.rdBase` in __init__.py solved the problem for me. My __init__.py is now as below.
```
try:
  from rdBase import rdkitVersion as __version__
except ImportError:
  __version__ = 'Unknown'
  raise
```

**Comment by 229668880** [comment]
I still have this problem. I  run rdkit on windows 10 and Python 3.5 (anaconda).  Within a new environment, either Python 3.5 or Python 3.6, rdkit works very well. But rdkit really cannot work on original python 3.5, and always returns the error "from .rdBase import rdkitVersion as __version__;  DLL load failed: The specified module could not be found."

I am wondering which dll rdBase depends on? Where is this dll? liboost, boost, boost_py, I am confused by these. What does rdBase require?  Maybe I can add something like "os.path.join" to manually help rdBase find the dll.

**Comment by greglandrum** [comment]
Hi. I stopped doing python 3.5 builds for the RDKit and really suggest switching to python 3.6. 
Do you need to stay with Python 3.5 for some reason?

**Comment by 229668880** [comment]
Hi. I just got the reason. Hope this may help the users with python 3.5. It is the problem of matching the version of boost and that of rdkit.

This works well:
conda install boost=1.66.0
conda install boost-cpp=1.66.0
conda install rdkit=2018.03.1 

Do not let conda choose the version automatically.

**Comment by mkoohim** [comment]
as @ClinuxMDL mentioned the order of the conda directory which you put in your path environment is important. I had the same issue and followed @ClinuxMDL suggestion and now the problem is solved. Edit you path manually and change the order of the directory like this:

C:\Miniconda3;C:\Miniconda3\Library\bin;C:\Miniconda3\Scripts

first C:\Miniconda3 then C:\Miniconda3\Library\bin and finally C:\Miniconda3\Scripts.

Thanks you @ClinuxMDL!

**Comment by vini-guimaraes** [comment]
Hello.
I'm having the same problem and couldn't solve it. I have installed rdkit version2022.03.5 and Python 3.9.12.
Is anyone else experiencing the same having the versions informed above?

**Comment by greglandrum** [comment]
@vini-guimaraes : which operating system are you using? are you using conda? how did you install the rdkit (exactly which commands did you execute)?

**Comment by vini-guimaraes** [comment]
@greglandrum thanks for the quick answer. I'm using Win10 but I know what I was doing wrong. I was activating the redkit environment but instead of initiating a Jupyter notebook from this environment I was going directly to Jupyter which wasn't giving me the option to create a new notebook already in that environment.

For those who are struggling I'll leave the steps that worked for me:

$ conda install -n my-rdkit-env nb_conda_kernels

$conda activate my-rdkit-env

Now with the environment activated just enter: $jupyter notebook

Then Jupyter will start and It will show the option " Python [conda env:my-rdkit-env]* " when you select the "New" dropdown menu.

This solved my problem.

**Comment by RMusil** [comment]
> 

Yes, I'm having the same issue. Python 3.7 (as per instructions found in a tutorial in the my-rdkit-env) (although otherwise I have also 3.9 installed).
