### ISSUE TITLE
EnumerateLibrary with initFromString called twice doesn't clear the reaction

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#1657]
**Description:**

- RDKit Version: 2017.09.01
- Platform: All

Calling InitFromString twice on the same library object will load the reactants and products twice into the ChemReaction making it senseless.

```
en = AllChem.EnumerateLibrary()
en.InitFromString(open("library.pickle").read())
en.InitFromString(open("library.pickle").read())
```

**Comment by greglandrum** [comment]
I'm looking into this one. The problem is the reaction itself.
`ReactionPickler::reactionFromPickle()` does not clear the contents of the reaction. This is analogous to `MolPickler::molFromPickle()`. This isn't necessarily a bug and would require some non-trivial changes to alter (we'd need to add the ability to clear the reaction contents).

I'm going to add a test in `EnumerateLibrary::initFromStream()` that raises an error if it's already been initialized.
