### ISSUE TITLE
Make default arguments to common functions less error prone

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1679]
**Description:**

Many of the RDKit functions/methods do not do the "best" thing by default. The idea here is to fix a lot of that.

A list of things to do:

- [x] MolToSmiles() : generate isomeric smiles by default
- [x] embedding code: use ETKDG by default
- [x] MolToMolBlock() : generate coordinates when includeStereo is set. (see #303)
- [x] call assignStereochemistryFrom3D() after reading a molecule with 3D coords.
- [x] support CXSMILES by default

**Comment by mcs07** [comment]
What about SmilesParserParams allowCXSMILES = True?

**Comment by greglandrum** [comment]
@mcs07 : sure, we can do that.

**Comment by greglandrum** [comment]
hmm, the CXSMILES thing seems to have broader implications than I thought. It's going to take a bit of digging to decide how realistic this is

**Comment by greglandrum** [comment]
The cases captured above are now all covered in the branch:
https://github.com/greglandrum/rdkit/tree/feat/github1679

@coleb @proteneer : are there other changes you guys were thinking of?

**Comment by coleb** [comment]
The only other thing I can think of is hydrogen handling. The common use case I see a lot is a user reading in an SDF file with graph hydrogens and 3D coordinates, usually because a lot of 3D methods need 3D coordinates for hydrogens, then needing a canonical isomeric smiles from that molecule at some point. 

This would require changing 2 defaults: 
- removeHs = false for all the parsers: SDMolSupplier, MolFromMolBlock, MolFromMol2Block, etc
- MolToSmiles to detect when graph hydrogens are present and Chem.RemoveHs on the molecule (or make SMILES generation ignore graph hydrogens during traversal by default)

**Comment by greglandrum** [comment]
Those are both more dramatic changes. Since the problems they are intending to correct - no Hs on a molecule, Hs in SMILES - are easy and unambiguous to detect, I think they should be skipped.

**Comment by greglandrum** [comment]
Closed by #1690
