### ISSUE TITLE
EmbedMultipleConfs Seed Zero

### ISSUE THREAD

**Issue by gncs** [rdkit/rdkit#1738]
**Description:**

- RDKit Version: 2017.09.3
- Platform: CentOS 7, gcc 6.2.0

If the seed is set to zero, ten identical conformers are generated.
This was not the case in 2017.09.1. Is this the intended behaviour?

```
  auto mol = std::unique_ptr<RDKit::RWMol>(RDKit::SmilesToMol("N[C@@H](CCCNC(N)=N)C(O)=O"));

  int seed = 0;
  RDKit::DGeomHelpers::EmbedMultipleConfs(*mol, 10, 30, seed);

  for (unsigned int i = 0; i < mol->getNumConformers(); i++) {
    std::cout << mol->getConformer(i).getAtomPos(0).x << ", " << mol->getConformer(i).getAtomPos(0).y << ", "
              << mol->getConformer(i).getAtomPos(0).z << std::endl;
  }
```

**Comment by greglandrum** [comment]
Hi. It is expected that the behavior changed relative to older releases when a seed of zero is provided. The documentation indicates that zero should be a valid seed, but it was not being used (i.e. providing a seed of zero was equivalent to providing a seed of -1). This was part of the fix for #1635.

What is not expected, and is definitely a bug in the current version, is that using a seed of zero results in the same conformation always being generated. I'll fix that, thanks for reporting it.
