### ISSUE TITLE
Matching of stereochemistry queries from complex atomic SMARTS is wrong

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1758]
**Description:**

Here's a little demo:
```
In [5]: p = Chem.MolFromSmarts('[#6]-[#6,#7@](-[#17])(-[#35])-[#9]')

In [6]: print(p.GetAtomWithIdx(1).DescribeQuery())
AtomOr
  AtomAtomicNum 6 = val
  AtomAnd
    AtomAtomicNum 7 = val
    AtomNull

In [7]: ms = [Chem.MolFromSmiles(x) for x in ('CC(Cl)(Br)F','C[C@](Cl)(Br)F','C[C@@](Cl)(Br)F')]

In [8]: [x.HasSubstructMatch(p,useChirality=True) for x in ms]
Out[8]: [False, True, False]
```

I'm not sure how Daylight did stereochem queries in SMARTS, but I'm pretty sure that the above should return the same substructure search results as this:
```
In [9]: p = Chem.MolFromSmarts('[#6]-[#6](-[#17])(-[#35])-[#9]')

In [10]: [x.HasSubstructMatch(p,useChirality=True) for x in ms]
Out[10]: [True, True, True]
```
(i.e. the `@` query only applies if the N matches).

**Comment by i-tub** [comment]
@greglandrum , I was just about to file a ticket about this but had the good sense to search first. :-) We encountered at Schrödinger it while working on a bug report from a customer, so it's not just a theoretical issue.

I also don't know what Daylight did, but I agree with your interpretation, because the OR operator `,` has low precedence. FWIW, the two other toolkits that I had available also seem to agree.

**Comment by greglandrum** [comment]
@i-tub thanks for letting me know that this happens "in the wild".

Doing a bit of investigation: the underlying problem is that the substructure-search chirality handling is happening at the atomic (instead of the query) level. So at the moment the options are: "setting chirality on a subquery affects the whole atom match" or "setting chirality on a subquery has no effect at all". Clearly this is wrong, but we will need to do some refactoring of that code in order to get this working.
