### ISSUE TITLE
Small issues with EmbedParameters

### ISSUE THREAD

**Issue by sriniker** [rdkit/rdkit#1759]
There are two small issues with the EmbedParameters object:

1) The maxAttempts parameter in the Python wrapper for EmbedMolecule() and EmbedMultipleConfs() is called maxIterations in the Python wrapper of the EmbedParameters object.
2) There is no more default for the numConfs parameters when calling EmbedMultipleConfs() with an EmbedParameters object.

**Comment by greglandrum** [comment]
Both points are true, but they're both intentional.

1. There was a mismatch between the C++ and Python naming of the parameters to the embedding functions (what was called `maxAttempts` in Python was `maxIterations` in C++). When I introduced the parameter object I decided to get rid of that mismatch. It shouldn't break an existing code, but I do see that it could be a bit confusing at first.
2. In order to provide a default value for `numConfs`, the `params` argument would have to come first. That seems a bit confusing.
