### ISSUE TITLE
Casting int to uint in MorganFingerprintHelper leads to unexpected behaviour.

### ISSUE THREAD

**Issue by SiPa13** [rdkit/rdkit#1761]
Using python (probably using c++ too), you can pass a negative value for _radius_ and _nBits_ through to the function _MorganFingerprintHelper_ in _rdMolDescriptors.cpp_ . This leads to them being casted to the max value of int minus the passed value. This might be unintended behaviour. I suggest throwing an error at one point of the chain, to let the user know, that he put a negative value there. 
Currently, passing a negative value for _radius_ or _nBits_ just leads to the program freezing (or taking extremely long to finish) without any feedback to the user that something might have gone wrong.

**Comment by SiPa13** [comment]
nbits=0 also seems to _crash_ without throwing an error/exception.

**Comment by MaxGreil** [comment]
Hi @greglandrum ,
I would like to take on this issue. Can you please explain what needs to be done here?

**Comment by greglandrum** [comment]
Hi Max,
Thanks for volunteering again.
In this case I think there are two things that are worth looking into:

1. making sure that negative values for either radius or nBits are not passed from Python to the Morgan fingerprinting code. This would be done in `$RDBASE/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp` and may be as easy as changing the types of those arguments to `MorganFingerprintHelper` from int to unsigned int. Otherwise you need to just check the values in the function and throw a value error if they are invalid. To figure out which of these works you'll need to create a test (of course).
2. making sure that the C++ fingerprinting code does something sensible (throwing a ValueErrorException would be fine) if the number of bits is 0

While making changes in `rdMolDescriptors.cpp` it's probably worth looking at the other fingerprinting functions there and seeing if any of those also are accepting ints when they really should only be accepting unsigned ints.

**Comment by mwojcikowski** [comment]
@greglandrum How about diff fingerprints where you'd expect negative values? I'd agree that there should be no negative values coming from the FP generation code, but whenever FP type is int, I'd say its fair to expect negative values too. That could be underlying cause for things like #2813
