### ISSUE TITLE
Issue with uniting two mols to a new mol

### ISSUE THREAD

**Issue by fyms107** [rdkit/rdkit#1771]
**Description:**
there are two mols
![1](https://user-images.githubusercontent.com/37279712/37261635-0fb5116e-25d9-11e8-9109-273f27f19c0b.jpg)
![2](https://user-images.githubusercontent.com/37279712/37261645-20ec4cea-25d9-11e8-93a8-beb2b3aa321d.jpg)

‘Rb’ is a placeholder. I want to unit them to a new mol

![3](https://user-images.githubusercontent.com/37279712/37261694-6670d556-25d9-11e8-8ab5-dde075df5e29.jpg)

I try to use
<<Chem.ReplaceSubstructs(), but it can't
Please help me, thanks!

**Comment by bp-kelley** [comment]
Let's walk through this.

You have two molecules

```
>>> s1 = "[Rb]c1ccccc1"
>>> Chem.MolFromSmiles(s1)
>>> s2= "[Rb]OC[Cs]"
>>> m2 = Chem.MolFromSmiles(s2)
```

And you want to combine that at the atoms *next* to [Rb].  I expect you were attempting something like this:

```
>>> mols = Chem.ReplaceSubstructs(m1, Chem.MolFromSmarts("[Rb"]), m2)
>>> print(mols[0])
'[Cs]CO[Rb]c1ccccc1'
```

And were annoyed that [Rb] was still left over.  The issue here is that ReplaceSubstruct doesn't change any atoms in the replacement.  There are two options:

1. Drop Rb from the second molecule and always make it so the first atom  is the one you want to bond.  (this is the default)

```
>>> s2= "OC[Cs]"
>>> m2 = Chem.MolFromSmiles(s2)
>>> Chem.ReplaceSubstructs(m1, Chem.MolFromSmarts("[Rb]"), m2, replacementConnectionPoint=0)
>>> print(mols[0])
'[Cs]COc1ccccc1'
```

2. Make a reaction.  The following takes two molecules and bonds anything connected to rubidium in mol1 to anything bonded to a rubidium in molecule 2 but doesn't copy the rubidium over to the final product(s).

```
>>> from rdkit.Chem import AllChem
>>> rxn = AllChem.ReactionFromSmarts("[Rb][*:1].[Rb][*:2]>>[*:1][*:2]")
>>> s1 = "[Rb]c1ccccc1"
>>> Chem.MolFromSmiles(s1)
>>> s2= "[Rb]OC[Cs]"
>>> m2 = Chem.MolFromSmiles(s2)
>>> results = rxn.RunReactants( [m1, m2] )
>>> for products in results:
...    for mol in products:
...        print(Chem.MolToSmiles(mol))
'[Cs]COc1ccccc1'
```

Hope this helps.
