### ISSUE TITLE
I want more information about Chem.MolFromSmiles('[1*]C1CCC([2*])C1')

### ISSUE THREAD

**Issue by fyms107** [rdkit/rdkit#1787]
**Description:**

It happened to find something new when I tested function ReplaceSidechains().
Can you tell me more information about [1*] in SMILES?
And how can I do with it?

![tim 20180322143915](https://user-images.githubusercontent.com/37279712/37755123-1e1b88a6-2ddf-11e8-9901-a61fffff84d1.jpg)

**Comment by greglandrum** [comment]
The `*` atoms are "dummy" atoms. They have atomic number zero and are usually used to indicate things like attachment points and the like. The number at the beginning is an isotope label and is just used to allow you to tell the atoms apart.

You aren't seeing the `1*` show up in the SMiLES on line 64 because you haven't asked for isomeric SMILES. Do this with: `Chem.MolToSmiles(new3,isomericSmiles=True)`
This piece of the documentation may be helpful to you:
http://rdkit.org/docs/GettingStartedInPython.html#substructure-based-transformations
