### ISSUE TITLE
Reordering atoms causes different rings to be found

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#1821]
**Description:**

All of the following are the same molecule, only one has isomeric ordering from RDKit

```
from rdkit import Chem
from rdkit.Chem import Descriptors
smi = "CC(C)[C@@H]1CC[C@@]2(C)[C@@H]3C[C@@H](O)C(=C)[C@H]2[C@@H]13"
molA = Chem.MolFromSmiles(smi)
print('MolA:',Descriptors.NumAliphaticCarbocycles(molA))
# MolA:, 4

molB = Chem.MolFromSmiles(Chem.MolToSmiles(molA))
print('MolB:',Descriptors.NumAliphaticCarbocycles(molA))
# MolB:, 4

molA = Chem.MolFromSmiles(Chem.MolToSmiles(molA, isomericSmiles=True))
print('MolC:',Descriptors.NumAliphaticCarbocycles(molA))
# MolC:, 3
```

**Comment by greglandrum** [comment]
Doing a bit of debugging: for the failing molecules the extra (4th) ring is not even found. So this isn't a symmetrization problem.

**Comment by greglandrum** [comment]
Here's some additional info generated while trying to track this down:
```
In [17]: m = Chem.MolFromSmiles('C1C2C3CCCC2C3CC1')

In [18]: print(m.GetRingInfo().AtomRings())
((0, 9, 8, 7, 2, 1), (3, 4, 5, 6, 1, 2), (1, 6, 7, 2))
# Wrong, should have been 4 rings. The missing one is (3, 4, 5, 6, 7, 2)

In [19]: m = Chem.MolFromSmiles('C1C2C3CCCC2C3CCC1')

In [20]: print(m.GetRingInfo().AtomRings())
((0, 1, 2, 7, 8, 9, 10), (3, 4, 5, 6, 1, 2), (1, 6, 7, 2))
# Wrong, should have been 4 rings. The missing one is (3, 4, 5, 6, 7, 2)
```

**Comment by jason-ford-silicontx** [comment]
Hi Brian and Greg, I'm not sure if there is a policy about resurrecting old issues, but I think I came across the bug in this issue recently for the following molecules:

![image](https://user-images.githubusercontent.com/81584643/197050387-0ab03359-732b-4425-8320-40d16d3f005f.png)

```
smiles = [
    "[H]N([H])C1([H])C([H])([H])C2([H])C3([H])C([H])(C1([H])[H])C23[H]",
    "[H]C1=C(N([H])[H])C2([H])OC3([H])C1([H])C([H])([H])C23[H]",
    "[H][N-]C1([H])C([H])([H])C2([H])C3([H])C([H])(C1([H])[H])C23[H]",
    "[H]C1=NC2([H])C3([H])N([H])C([H])([H])C2([H])C3([H])N1[H]",
]
```

The issue arose in my case with usage of the postgres cartidge. Specifically, these molecules ended up as duplicates in our database, despite having a unique constraint on the molecule field, and I think it is due to the number of rings being inconsistent with different orderings of the bonds (it's possible there are other issues at hand though). If I understand correctly, the ring count is used in the comparison functions in the cartridge when calling the [molcmp](https://github.com/rdkit/rdkit/blob/bd666957d1d62c2f2e46c7550f7287555cb3c95d/Code/PgSQL/rdkit/adapter.cpp#L519) function, allowing the duplicates to be entered rather than leading to an error. I can provide more details in our failure case if that is helpful.
