### ISSUE TITLE
Error about isomeric SMILES to molecules and stereo type of bonds

### ISSUE THREAD

**Issue by kaihua8910** [rdkit/rdkit#1841]
**Hi, everyone:

When I queried the stereo type of bonds in a isomeric molecule, GetStereo function returned “STEREONONE” .
My code is:
```
m=Chem.MolFromSmiles('C[C@@H]1CCC[C@@H]1C')
for bond in m.GetBonds():
      print(bond.GetStereo())
```

I think I have given the isomeric SMILES, why rdkit can not return the stereo types of all bonds ?
I tried the function Chem.DetectBondStereochemistry(m), but rdkit still returned "STEREONONE".

Moreover,
When I transferred the molecule to the isomeric SMILES by rdkit:
`print(Chem.MolToSmiles(m,isomericSmiles=True))`
rdkit returned: `C[C@H]1CCC[C@H]1C`
the stereo type has changed.

**
who can help me about this problem? thanks a lot

- RDKit Version: 2017.09.3.0
- Platform: Windows 10 x64 python 2.7.14
 ##

```
m=Chem.MolFromSmiles('C[C@@H]1CCC[C@@H]1C')
for bond in m.GetBonds():
      print(bond.GetStereo())
print(Chem.MolToSmiles(m,isomericSmiles=True))
```

**Comment by greglandrum** [comment]
Sorry for the extremely slow reply.

In the RDKit's terminology the stereochemistry of bonds refers to E/Z (or CIS/TRANS) stereochemistry of double bonds, so there is no double bond stereochemistry in this molecule.
The molecule does have two atomic stereocenters that have stereo information associated with them:
```
In [15]: m=Chem.MolFromSmiles('C[C@@H]1CCC[C@@H]1C')
    ...: for atom in m.GetAtoms():
    ...:       print(atom.GetChiralTag())
    ...:
CHI_UNSPECIFIED
CHI_TETRAHEDRAL_CCW
CHI_UNSPECIFIED
CHI_UNSPECIFIED
CHI_UNSPECIFIED
CHI_TETRAHEDRAL_CCW
CHI_UNSPECIFIED
```

Could it be that you're interested in the wedging of the bonds around chiral centers? This is not present by default, but you can add it:
```
In [17]: from rdkit.Chem import rdDepictor

In [18]: m=Chem.MolFromSmiles('C[C@@H]1CCC[C@@H]1C')
    ...: rdDepictor.Compute2DCoords(m)
    ...: Chem.WedgeMolBonds(m,m.GetConformer())
    ...: for bond in m.GetBonds():
    ...:       print(bond.GetBondDir())
    ...:
BEGINWEDGE
NONE
NONE
NONE
NONE
BEGINWEDGE
NONE
```
Note that I needed to generate a set of 2D coordinates as well, since bond wedging information only makes sense in the context of a conformer.

Does that help?
