### ISSUE TITLE
Potential SMARTS parsing error. 

### ISSUE THREAD

**Issue by bannanc** [rdkit/rdkit#1842]
**Description:**

- RDKit Version: 2018.03.1
- Platform: Mac

I am working with some relatively complex SMARTS patterns. I had written tests using them with OpenEye Toolkits. We are working to expand our tools to support RDKit as an alternative. Here's the SMARTS I'm having trouble with. I know the SMARTS pattern is a bit odd looking, but I do think it is valid. 

```
ss = Chem.MolFromSmarts("[#6$(*~[#6]=[#8])$(*-,=$([#7!-1,#8,#16]))]")
```
Which prints this to the command line:
```
[02:42:43] SMARTS Parse Error: syntax error for input: '[#6$(*~[#6]=[#8])$(*-,=$([#7!-1,#8,#16]))]'
```

Technically this came from a replacement strategy you can use with OpenEye tools (OESmartsLexReplace)[https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OESmartsLexReplace.html]. When I use this with openeye:
```
from openeye import oechem

replacements = [ ('ewg1', '[#7!-1,#8!-1,#16!-1,#9,#17,#35,#53]'),
                  ('ewg2', '[#7!-1,#8,#16]') ]
smirks = "[#6$(*~[#6]=[#8])$(*-,=$ewg2)]"
new_smirks = oechem.OESmartsLexReplace(smirks, replacements)
print(new_smirks)
```
I double checked if rdkit supported this type of replacement, but couldn't find anything in the documentation, so I wrote my own replacement for the rdkit version.

**Comment by greglandrum** [comment]
Sorry for the slow reply, this one one slipped through the (rather large) cracks in my monitoring of github.

This SMARTS: `[#6$(*~[#6]=[#8])$(*-,=$([#7!-1,#8,#16]))]` is definitely wrong.
The problem is here:
```
[#6$(*~[#6]=[#8])$(*-,=$([#7!-1,#8,#16]))]
                       ^
```
That recursive SMARTS pattern needs to be in square brackets. So I believe this should be:
```
[#6$(*~[#6]=[#8])$(*-,=[$([#7!-1,#8,#16])])]
                       ^                 ^
```
Where I've put arrows indicating the square brackets enclosing the recursive pattern.

As an aside: if you ever have questions about SMARTS validity, a great place to start is the SMARTS viewer tool from Matthias Rarey's group in Hamburg: http://smartsview.zbh.uni-hamburg.de/

**Comment by greglandrum** [comment]
Onto the lexical replacement thing.
Since I don't know the OpenEye tools, I don't know what OESmartsLexReplace does, but I believe the RDKit has a way to do something very close to what I think you're trying to do, but you do need to actually parse the SMARTS into a molecule to make it happen:
```
In [5]: replacements = {'$ewg1':'[#7!-1,#8!-1,#16!-1,#9,#17,#35,#53]',
   ...: '$ewg2':'[#7!-1,#8,#16]'}

In [6]: smirks = "[#6$(*~[#6]=[#8])$(*-,=$ewg2)]"

In [8]: patt = Chem.MolFromSmarts(smirks,replacements=replacements)

In [9]: Chem.MolToSmarts(patt)
Out[9]: '[#6&$(*~[#6]=[#8]);$(*-,=[#7&!-,#8,#16])]'

In [10]: smirks2 = "[#6$(*~[#6]=[#8])$(*-,=$ewg1)]"

In [11]: patt2 = Chem.MolFromSmarts(smirks2,replacements=replacements)

In [12]: Chem.MolToSmarts(patt2)
Out[12]: '[#6&$(*~[#6]=[#8]);$(*-,=[#7&!-,#8&!-,#16&!-,#9,#17,#35,#53])]'
```
Note that I had to make a small modification : adding the `$` to the replacements dictionary.

If you just want to do this as a string replacement, doing it with Python string operations is likely reasonably straightforward.

**Comment by bannanc** [comment]
OK, I found it because I test I had running with OpenEye failed when I added support for RDKit. It must have to do with the way they handle the replacement.  Sorry I missed the replacement option with RDK, that will solve this for us. 
Thanks Greg! I'll close the issue.
