### ISSUE TITLE
Weird looking molecules with Draw.MolToFile(mol, imageName)

### ISSUE THREAD

**Issue by redBirdTx** [rdkit/rdkit#1863]
**hi, New to RDKit and need some help understanding what RDKit is drawing:**

- RDKit Version:'2017.09.1'
- Platform:Ubuntu

So I converted my string to Canonical smiles, then converted to mol via MolFromSmiles. When try drawing the molecule, somehow the atoms doesn't show up right. I have the rectangles instead of the actual element showing in the drawing. Any thing I did wrong here? Thanks

```
params = Chem.SmilesParserParams()
params.removeHs=True
params.sanitize=True       
smileStr = Chem.CanonSmiles(s, useChiral=1)
mol = Chem.MolFromSmiles(smileStr, params)
AllChem.Compute2DCoords(mol)
![0_fromcon](https://user-images.githubusercontent.com/29144404/39795997-9831388e-5319-11e8-8de0-f2259dd9916f.png)

Draw.DrawingOptions.bondLineWidth=2
Draw.DrawingOptions.atomLabelFontSize=14
Draw.MolToFile(mol,imgName)
```

![85_fromcon](https://user-images.githubusercontent.com/29144404/39827347-525de208-537d-11e8-8e8a-34ca68cfada9.png)

**Comment by greglandrum** [comment]
Due to historic reasons and a desire to maintain some backwards compatibility, there are a couple of different ways to get drawings of molecules into a file via the RDKit. You're using an older one (which makes sense, it's the thing that's documented).

I would suggest switching to using the newer drawing code. There's a discussion here that you may find helpful:
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg07907.html
