### ISSUE TITLE
"make install" appears to miss RDBoost/export.h

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1903]
I'm compiling a test program against the git master, where I've used "make install" to install out-of-tree.

If I want to get the version from RDGeneral/versions.h, this includes the line:
```
#include <RDBoost/export.h>
```
but this file is not installed by the "make install" command.

**Comment by greglandrum** [comment]
Thanks for pointing this out @baoilleach

**Comment by dawenzi123** [comment]
any workaround? just hit the same problem ...

**Comment by greglandrum** [comment]
It looks like the problem here is that `export.h` is being created in the `RDBoost` directory, which is only installed when you build the python wrappers.
A better place for the file would be `RDGeneral`.

@ptosco : If you agree, I will go ahead and make the change (it touches a lot of files, but is easy to automate).

**Comment by ptosco** [comment]
Sure, that’s fine by me. I didn’t know that `RDBoost` is installed only if Python wrappers are built or I’d put it in `RDGeneral` in the first place.
