### ISSUE TITLE
Incorrect tetrahedral stereo when reading SMILES with ring closure as last neighbor

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1972]
I've just been adding stereo tests to the SMILES benchmark. There's a single failure for RDKit (2018.03.1) related to ring closures on a tetrahedral stereocenter. The following four SMILES strings represent the same molecule, where I walk the ring closure along the string:
```
[C@]1(Cl)(F)I.Br1
[C@@](Cl)1(F)I.Br1
[C@](Cl)(F)1I.Br1
[C@@](Cl)(F)(I)1.Br1
```
However, the final one is not interpreted correctly. That is, it should be the same as ```[C@@](Cl)(F)(I)Br``` but it is not:
```
>>> from rdkit import Chem
>>> Chem.MolToSmiles(Chem.MolFromSmiles("[C@@](Cl)(F)(I)1.Br1"))
'F[C@](Cl)(Br)I'
>>> Chem.MolToSmiles(Chem.MolFromSmiles("[C@@](Cl)(F)(I)Br"))
'F[C@@](Cl)(Br)I'
```

**Comment by bp-kelley** [comment]
This isn't a bug I think.  Chirality is normally defined by the order of the atoms in the smiles string, not the order of the bonds, the atom orderings for your example are the same hence the chirality should be the same.

**EXCEPT** (http://opensmiles.org/opensmiles.html)

_One exception to the atom order is when these atoms are bonded to the chiral center via a ring bond. In these cases, it is the order of the bonds to these atoms that should be considered._

Even if you aren't forming a ring, the number notation is considered a ring bond.  This might be an edge case where a closure isn't really a ring bond and should be using the atom order.  I'll leave deducing the semantics of this to @adalke and Roger Sayle though :)

**Comment by bp-kelley** [comment]
I'll point out that the RDKit parses the opensmiles examples in the document correctly:

```
>>> from rdkit import Chem
>>> Chem.MolToSmiles(Chem.MolFromSmiles("FC1C[C@](Br)(Cl)CCC1"))
'FC1CCC[C@](Cl)(Br)C1'
>>> Chem.MolToSmiles(Chem.MolFromSmiles("[C@]1(Br)(Cl)CCCC(F)C1"))
'FC1CCC[C@](Cl)(Br)C1'
```

**Comment by adalke** [comment]
Brian wrote: " Chirality is normally defined by the order of the atoms in the smiles string, not the order of the bonds"

This is not correct. The Daylight documentation says: " The chiral order of the ring closure bond is implied by the lexical order that the ring closure digit appears on the chiral atom (not in the lexical order of the "substituent" atom). "

What's happened here is that "\[C@@](Cl)(F)(I)1.Br1" is not a valid SMILES, according to Daylight and OpenSMILES. Those require that the ring closures come immediately after the atom symbol/bracket term, and not after any branches.

This appears to be related to #786 .

**Comment by bp-kelley** [comment]
@adalke wasn't the "Normally" cleared by the exception text I cited?

**Comment by bp-kelley** [comment]
I do agree that it isn't a valid smiles though.  However, the same chiral ordering via ring bonds can occur in valid smiles.

**Comment by adalke** [comment]
I was wrong, in that it's not incorrect. I just don't think it's useful to describe it as "normally X except Y for ring closures" when the rule is "always Y". It happens that Y == X when there are no ring closures.

Yes, this means I disagree with the OpenSMILES description as well. I think it's better/simpler to say that it always depends on the order of the bonds to the atom.

I do agree with Noel's assessment that RDKit's support of this extension does not seem reasonable. Technically I can't say it's wrong because that extension isn't documented, but I can point out that other toolkits also support this non-standard SMILES. OEChem's answer seems reasonable:

    >>> from rdkit import Chem
    >>> Chem.CanonSmiles("[C@@](Cl)(F)(C)1.Br1")
    'C[C@@](F)(Cl)Br'
    >>> Chem.CanonSmiles("[C@@](Cl)(F)(C)Br")
    'C[C@](F)(Cl)Br'
    >>>
    >>> from openeye.oechem import *
    >>> mol = OEGraphMol()
    >>> OEParseSmiles(mol, "[C@@](Cl)(F)(C)1.Br1")
    True
    >>> OECreateIsoSmiString(mol)
    'C[C@](F)(Cl)Br'
    >>> mol = OEGraphMol()
    >>> OEParseSmiles(mol, "[C@@](Cl)(F)(C)Br")
    True
    >>> OECreateIsoSmiString(mol)
    'C[C@](F)(Cl)Br'

**Comment by bp-kelley** [comment]
@adalke Thanks for the clarification, I agree that the exceptional case isn't exceptional in the bond order sense, except of course if we don't consider Br1 a ring bond since it isn't in a ring, then the OpenSmiles definition would match OpenEye's smiles, i.e. the atom order would win out here.

Aren't semantics fun?

**Comment by adalke** [comment]
The OpenSMILES spec is insufficiently precise. It never defines "ring bond".  It implies that a ring bond is somehow different from a non-ring bond, with:

> A ring-number specifications ("rnum") is most commonly used to specify a ring-closure bond, but when used with the '.' dot-bond symbol, it can also specify a non-ring bond.

I disagree with that distinction, and think that Craig wasn't being precise when he wrote it.

The other example of "ring bond" is in the section on relaxed SMILES for "Mismatched Ring Bonds ... Mismatched ring bonds are ignored". If we say there is a distinction between a "ring bond" and a "non-ring bond", then there is no relaxed interpretation for "C1CCC.C" because we do not know if the 1 is 'supposed' to be to a ring bond or a non-ring bond.

If we make your assumption, and say that this is a non-ring bond so that atom order wins, then there is an error in the following as the atom order of the bromine does not affect the chirality:

    >>> Chem.CanonSmiles("[C@@](Cl)(F)(C)1.Br1")
    'C[C@@](F)(Cl)Br'
    >>> Chem.CanonSmiles("[C@@](Cl)(F)(C.Br1)1")
    'C[C@@](F)(Cl)Br'
    >>> Chem.CanonSmiles("[C@@](Cl)(F.Br1)(C)1")
    'C[C@@](F)(Cl)Br'
    >>> Chem.CanonSmiles("[C@@](Cl.Br1)(F)(C)1")
    'C[C@@](F)(Cl)Br'
    >>> Chem.CanonSmiles("Br1.[C@@](Cl)(F)(C)1")
    'C[C@@](F)(Cl)Br'

**Comment by baoilleach** [comment]
Usually I refer to these as bond closure digits, as they (strictly-speaking) have nothing to do with rings, except that if you have a ring you need to use one. Also, it is more useful to consider the digit as indicating an atom, not a bond, as they can appear everywhere an atom can appear (with some exceptions). Just like atoms, they can be preceded by a bond symbol but otherwise it's an implicit bond, What I'm trying to say is that the digit itself is not the bond, but rather is a proxy for the atom at the other end of the bond.

Anyway, perhaps it is sufficient simply to point out that for all but one of the other programs that I've tested that support this syntax, the meaning is as I described. Those programs are BIOVIADraw, Cactvs, CDK (https://github.com/johnmay/beam/issues/6), ChemDraw, Indigo, Open Babel, and OEChem. OpenChemLib loses the stereo on the fourth position but supports it at the others - I will be reporting this similarly as a bug.

**Comment by greglandrum** [comment]
I agree that the current behavior is a bug.
As I mentioned on the previous ticket, it's kind of goofy to support the "ring digits" anywhere other than directly after the atom, but as long as we're stuck supporting it (and it seems that we are), the right thing should happen.

@baoilleach : these are interesting corner cases, but I'm curious if you've ever seen any "in the real world"

**Comment by greglandrum** [comment]
It's always a question I like to ask because it helps me prioritize things.
:-)

**Comment by bp-kelley** [comment]
@greglandrum: I have a few use-cases:

1. Fast reaction enumeration with stereo centers, this is one of the reasons it isn't in the enumeration library yet since I had wrong assumptions about closure bonds and stereo, fixing this would make this way easier.
2. MMP with stereo

@adalke Yes, I believe those interpretations are incorrect in RDKit, I think the answer should be 'C[C@](F)(Cl)Br'  Which I believe is equivalent to atom order in these examples however it is derived.

**Comment by greglandrum** [comment]
Just a quick note to myself that the problem here happens on SMILES parsing:
```
In [3]: Chem.MolFromSmiles('[C@@](Cl)(F)(I)Br').Debug()
Atoms:
	0 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 1
	1 17 Cl chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	3 53 I chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	4 35 Br chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 0->2 order: 1 conj?: 0 aromatic?: 0
	2 0->3 order: 1 conj?: 0 aromatic?: 0
	3 0->4 order: 1 conj?: 0 aromatic?: 0

In [4]: Chem.MolFromSmiles('[C@@](Cl)(F)(I)1.Br1').Debug()
Atoms:
	0 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 2
	1 17 Cl chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	3 53 I chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	4 35 Br chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 0->2 order: 1 conj?: 0 aromatic?: 0
	2 0->3 order: 1 conj?: 0 aromatic?: 0
	3 4->0 order: 1 conj?: 0 aromatic?: 0
```
