### ISSUE TITLE
Difficulty with enumeration

### ISSUE THREAD

**Issue by b-mahjour** [rdkit/rdkit#1980]
I am trying to enumerate a reaction that looks like this: 

![template](https://user-images.githubusercontent.com/37459179/43345439-89444678-91bb-11e8-97d9-85814d5917f9.JPG)

The carbons I have circle in blue are the ones that are changing for the enumeration. However, they may or may not be part of an aromatic cycle. I've tried as many different combinations of reaction SMARTS but I still can't get it to work. I usually run into a problem where it doesn't recognize the carbons as being in the aromatic ring or a problem with kekulization (the reaction not running correctly)

The closest I've gotten is this: 

`    rxn7 = AllChem.ReactionFromSmarts("O=C(CCC)O.N[a:1]>>O=C(CCC)O[a:1](N)")
`

But I get "Can't kekulize mol" for each enumerated reaction. Any help would be appreciated

Thanks

**Comment by greglandrum** [comment]
The first reaction you show does not correspond to the specific example in the second image, and I'm not sure the specific example is what you actually intend, but I think I understand what you're looking for.

It looks like you are trying to do this general reaction:
![image](https://user-images.githubusercontent.com/540511/43353325-f07d1ea8-9235-11e8-96aa-dfce4fee0802.png)
And then your more specific example:
![image](https://user-images.githubusercontent.com/540511/43353343-5559eb08-9236-11e8-8b00-04a49ca01647.png)

The difficulty here is that it's hard to "destroy" aromaticity in a reaction. Unless you include the entire aromatic ring in your reaction definition (which I doubt you want to do), you're almost guaranteed to end up with a sanitization problem. A trick to solve that is to kekulize your reactants before you run the reaction:
```
In [28]: rxn = AllChem.ReactionFromSmarts('[NH2:1]-[C:2](-[C:3])=[C:4]>>[N:1]-[C:2](-Cl)(-[C:3])-[C:4]')

In [29]: m = Chem.MolFromSmiles('Nc1ccccc1')

In [31]: Chem.Kekulize(m,clearAromaticFlags=True)

In [32]: ps = rxn.RunReactants((m,))

In [33]: Chem.SanitizeMol(ps[0][0])
Out[33]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [34]: Chem.MolToSmiles(ps[0][0])
Out[34]: 'NC1(Cl)C=CC=CC1'
```

The specific reaction  you show actually does something different since it rearranges the bonds in aromatic ring itself. For that you'd need to include the whole ring. I will post an example of that after the weekend.

**Comment by b-mahjour** [comment]
Thanks so much Greg. I will try this out.

And yes, you are right my second example is incorrect I just wanted to give an idea of what I was trying to do (my orgo is a bit rusty). Basically the gist of the issue is that the most of the reactants in the reactant library has aromatic rings and I want to enumerate reactions on alpha, beta, and gamma positions relative to each functional group (amide and carboxylic acid)

**Comment by greglandrum** [comment]
And here's a simple example of using the RDKit reaction machinery to go from a aromatic 6-ring to a 1-4 diene:
```
In [45]: rxn = AllChem.ReactionFromSmarts('[NH2:1][c:2]:1:[a:3]:[a:4]:[a:5]:[a:6]:[a:7]:1>>[N:1][C:2]1(-Cl)-[A:3]=[A:4]-[A:5]-[A:6]=[A:7]-1')

In [46]: m = Chem.MolFromSmiles('Nc1ccccc1')

In [48]: Chem.SanitizeMol(ps[0][0])
Out[48]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [49]: Chem.MolToSmiles(ps[0][0])
Out[49]: 'NC1(Cl)C=CCC=C1'
```

**Comment by greglandrum** [comment]
@b-mahjour: I'm closing this because it looks like the question is answered. Please reopen if necessary.
