### ISSUE TITLE
Unable to get Molecule from Smile

### ISSUE THREAD

**Issue by sachinrox** [rdkit/rdkit#2009]
**Description:**

- RDKit Version: 2016.03.5
- Platform: Python 2.7 on Ubuntu 18.04

>from rdkit import Chem
 In [32]: m=Chem.MolFromSmiles('[NH2]=C(N)c1ncnn1')
[12:00:21] Explicit valence for atom # 0 N, 4, is greater than permitted
RDKit ERROR: [12:00:21] Explicit valence for atom # 0 N, 4, is greater than permitted

I am trying to obtain a molecule from a SMILE. The SMILES are obtained from the QM9 data set. I run into the above error for some of the molecules.

How can I resolve this issue?

**Comment by greglandrum** [comment]
That molecule is not chemically reasonable: `N #0` (the first atom) is neutral and four valent, this violates the octet rule.
The aromatic ring is also going to cause problems: none of the heteroatoms in the ring have an indication of implicit H count, so that's going to fail as well.

If you believe that this is supposed to correspond to a stable molecule, your best bet is probably to contact the group that produced the dataset and ask them to fix their SMILES-generation process.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
