### ISSUE TITLE
Stochasticity in PMI calculations

### ISSUE THREAD

**Issue by b-mahjour** [rdkit/rdkit#2012]
I'm new to using PMI calculations and I'm getting a fairly large range of potential values when using NPR1 and NPR2. This is what I have been doing:

```
           mol2 = Chem.AddHs(mol)
           AllChem.EmbedMolecule(mol2)
           AllChem.UFFOptimizeMolecule(mol2)
           x1 = Chem.Descriptors3D.NPR1(mol2)    
           y1 = Chem.Descriptors3D.NPR2(mol2)
```
Is there anyway to reduce this variance? I'm having a hard time comparing trends because of it.

Thanks

**Comment by greglandrum** [comment]
Which version of the RDKit are you using? Which operating system?
Can you please provide an example molecule where you see this problem?

**Comment by b-mahjour** [comment]
I am using the 3/3/2018 release on linux subsytem for windows (ubuntu).

Strangely I can't recreate my problem from a week ago.. It seems to be always producing the same numbers now/

**Comment by b-mahjour** [comment]
Alright I found an example:

 '[CH]c1cccc(C(=O)N[C@@H]2CCC[C@H](C)C2)c1': 
[(0.152673595282949, 0.9161095627248084),
 (0.22955020134585416,0.970582079859437)]

**Comment by greglandrum** [comment]
By default when you generate conformations for a molecule, a random number is used. So if you generate multiple conformations for the molecule, each of them will be generally be different.

Since the PMI and NPR descriptors use the 3D coordinates of the conformations, they *should* vary from conformer to conformer of the same molecule.

If you want to always get the same conformer for a molecule try providing the `randomSeed` argument:
![image](https://user-images.githubusercontent.com/540511/45492225-0bf8b600-b76c-11e8-91cd-0d55bcb16858.png)


There actually was a bug that was leading to PMI and NPR results being *too* reproducible: #2037

**Comment by b-mahjour** [comment]
Right, but shouldn't I always get the same conformer from "AllChem.UFFOptimizeMolecule(mol2)"?

**Comment by greglandrum** [comment]
Nope. Different conformers generally optimize to different minima.

**Comment by b-mahjour** [comment]
Great. Thanks for clearing this up for me!
