### ISSUE TITLE
Depiction of stereochemistry in molfile depends on content of line 2 / generation programm

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#2019]
**Description:**

- RDKit Version: 2018.03.1
- Platform: Windows / Ubuntu

Depending on the contents of line 2 of a molfile, bonds at stereocenters are drawn in correctly (wedges) or wrong(flat)

Example molfile that works:
```
Test
  ChemDraw09031810422D

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.0717    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0717    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0      
  2  3  1  0      
  3  4  1  0      
  4  5  1  0      
  5  6  1  0      
  6  1  1  0      
  5  7  1  6      
  3  8  1  6      
M  END
```
If we take the exact same molfile but manipulate line 2 (generation programm) it displays the depiction without stereochemistry
```
Test2
  ChemDraw01412400-2571-620482D

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.0717    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0717    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0      
  2  3  1  0      
  3  4  1  0      
  4  5  1  0      
  5  6  1  0      
  6  1  1  0      
  5  7  1  6      
  3  8  1  6      
M  END
```
Note: Names like this are generated by PerkinElmer Oracle Cartridge (older version).

Code to display is simply

```
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True
Chem.MolFromMolBlock(molblock) 
```

in Jupyter notebook where molblock is either of above strings.

This is extremely confusing. Seems like some regex matching going on? But why? Anyway same ctab file should be displayed the same in all cases or am I missing some weird technically issue?

**Comment by jasondbiggs** [comment]
I've encountered this before, and I think this is what's happening.  In order for wedge/dash information from a mol file to be read, the 21st and 22nd character of the second line need to be "2D".  Otherwise, it interprets the file as a 3D conformer, and looks for stereo information in the coordinates rather than the CTAB.  The relevant code is [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FileParsers/MolFileParser.cpp#L2413).

I think this is consistent with page 34 of [the MOL file spec](http://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf).

**Comment by greglandrum** [comment]
@jasondbiggs has it right here: the second mol block is incorrect because the `2D` marker is in the wrong place (this is caused by this bit being too long `ChemDraw01412400-2571-62048`). If the RDKit does not see the `2D` marker it assumes that the conformation is 3D and does not check bond wedging for stereo information.

A possible solution is to edit the mol blocks to correct this problem before you parse them. Something like this works for me:
```
ls = mb.split('\n')
ls[1] = ls[1][:20]+'2D'
nmb = '\n'.join(ls)
```

**Comment by kienerj** [comment]
Thanks both. So the generation program is faulty and fixing second line indeed works.
