### ISSUE TITLE
Incorrect cis/trans stereo symbol for conjugated ring

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#2023]
For the following SMILES (taken from a larger ChEMBL molecule), RDKit writes a SMILES string that has the final symbol in the opposite direction (i.e. "N/1" instead of "N\1"). That direction is incorrect, and inconsistent with the direction at the other end of the ring closure bond. (Just for the record, not part of my benchmark, just came across it :-) )
```
from rdkit import Chem

smi = r"CO/C1=C/C=C\C=C/C=N\1"
m = Chem.MolFromSmiles(smi)
can = Chem.MolToSmiles(m, isomericSmiles=True)
print(can)
# 'CO/C1=C/C=C\C=C\C=N/1'
# - which has inconsistent cis/trans bond symbols (the first and last)
# Should be
# 'CO/C1=C/C=C\C=C\C=N\1'
```

**Comment by baoilleach** [comment]
Just confirmed that it's still a problem with 2018.09.1.

**Comment by greglandrum** [comment]
Yep. and the problem is actually in the interpretation of the stereochemistry on *parsing*:
```
In [6]: m = Chem.MolFromSmiles(r"CO/C1=C/C=C\C=C/C=N\1" )                                              

In [8]: for b in m.GetBonds(): 
   ...:     if b.GetStereo() != Chem.BondStereo.STEREONONE: 
   ...:         print(b.GetBeginAtomIdx(),b.GetEndAtomIdx(),b.GetStereo()) 
   ...:                                                                                                
2 3 STEREOE
4 5 STEREOZ
6 7 STEREOZ
8 9 STEREOZ
```
The bonds should all be `STEREOZ`

**Comment by greglandrum** [comment]
Here's a simplified version:
```
In [39]: m = Chem.MolFromSmiles(r"OC1=C/CCCCCN\1")                                                     

In [40]: for b in m.GetBonds(): 
    ...:     if b.GetStereo() != Chem.BondStereo.STEREONONE: 
    ...:         print(b.GetBeginAtomIdx(),b.GetEndAtomIdx(),b.GetStereo()) 
    ...:                                                                                               
1 2 STEREOE
```
It looks like the problem is in the way the ring closure bond is being parsed

**Comment by greglandrum** [comment]
Apologies, I had confused myself, so I just deleted a couple of comments.

**Comment by ricrogz** [comment]
I have had a look at this one. The problem is caused by the double bond canonicalizer.

It first sets the first directed bond (which is redundant in the initial SMILES?). Then, it tries to set the other bond direction (redundant, as we set the first) on the same atom, but it apparently expects it to be inside a bracket, so that it had to be written in reverse (i.e. with the same direction as the first bond).

The problem is, it is not inside a bracket, it is the last directed bond ("N/1"). Then, the canonicalizer builds up from the initial directed bond, up to the point of reaching the last double bond, where it finds the "bad" redundant bond, and also badly setting the second to last direction:
smi = CO/C1=C/C=C\C=C**/**C=N**\**1
can = 'CO/C1=C/C=C\C=C**\**C=N**/**1

**Comment by ricrogz** [comment]
I might have been to fast with the last comment... I found a small error in my fix, and it seems to work quite good... without too much change to what the canonicalizer does.

PR coming up...

**Comment by baoilleach** [comment]
Thanks @ricrogz .
