### ISSUE TITLE
Depicting from molfile: Wrong bond getting wegded

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#2024]
**Description:**

- RDKit Version: 2018.03.1
- Platform: Windows , Ubuntu

For some molfiles the wrong bond is getting drawn as a wegde. 

Example:

```
Untitled Document-1
  ChemDraw09031812212D

 10  9  0  0  0  0  0  0  0  0999 V2000
   -2.8578   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1433   -0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4289   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1433   -0.6187    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.8578   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.6188    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0      
  2  3  1  0      
  3  4  1  0      
  4  5  1  0      
  5  6  1  0      
  6  7  1  0      
  7  8  1  0      
  8  9  1  0      
  5 10  1  6      
M  END
```

The file clearly marks the C-S bond as a wedge but in fact the bond from the C to another C gets wedged. In ChemDraw it is displayed as expected.

See depictions [here](https://imgur.com/a/pqFVlYa)

**Comment by greglandrum** [comment]
Here's what happens:
1) The molblock is parsed and stereochemistry perception is done. This removes the bond wedging information.
2) When you generate a depiction (or molblock) from the resulting molecule, the RDKit picks a bond to wedge.

In this case the bond that the RDKit picks to wedge is different from what was in the input. The resulting structure is correct, just different from what you provided. 

I know that that this seems a bit strange, but it is expected behavior: the RDKit does not, in general, attempt to preserve all information required to be able to round trip every input structure.

There's a good argument that it would be "nicer" to wedge the bond to the S (since that atom is degree one) instead of the C (degree 2), but that's a different thing.

**Comment by d-b-w** [comment]
There is now a function called `ReapplyMolblockWedging` that will achieve this commonly desired behavior.
