### ISSUE TITLE
GetReactingAtoms() returning non reacting atoms

### ISSUE THREAD

**Issue by doctorx84** [rdkit/rdkit#2031]
Hi,

I'm trying to extract reaction centers from reactions.
Therefor i load the reaction into a `RDKit::ChemicalReaction` and call `RDKit::getReactingAtoms(*rxn, true);`.
The results dose not match my expectations.
The example below should result in one reacting atom in the first reactant but i get seven.
Is this a bug or a misunderstanding from my side?

My system:
Visual Studio 2017 (c++)
RDKit 2017.9.3
Windows 10 [1803] Pro x64

Example code:
`RDKit::ChemicalReaction *rxn;`
`string rxn_str = "[Cl:1][CH2:2][CH2:3][CH2:4][C:5]([C:7]1[CH:12]=[CH:11][C:10]([CH:13]([CH3:15])[CH3:14])=[CH:9][CH:8]=1)=[O:6].[Br:16]N1C(=O)CCC1=O>C(Cl)(Cl)(Cl)Cl.CC(N=NC(C#N)(C)C)(C#N)C>[Br:16][C:13]([C:10]1[CH:9]=[CH:8][C:7]([C:5](=[O:6])[CH2:4][CH2:3][CH2:2][Cl:1])=[CH:12][CH:11]=1)([CH3:15])[CH3:14]";`
`rxn = RDKit::RxnSmartsToChemicalReaction(rxn_str);`
`rxn->initReactantMatchers();`
`auto ra = RDKit::getReactingAtoms(*rxn, true);`
`cout << ra[0].size() << endl;`

Output: 7

Thank you in advance!

-Wolf

**Comment by greglandrum** [comment]
This one is non-trivial to explain, and even more non-trivial to make work.
The short answer is that the RDKit is very quick to label something as a reacting atom and it doesn't carry out sanitization of reactants/products.
In your case you have a different kekule form of the 6 ring between the reactants and the products, so all of the atoms in that ring are flagged as reacting. You can fix this by using a different kekule form:
```
sma='[Cl:1][CH2:2][CH2:3][CH2:4][C:5]([C:7]1[CH:12]=[CH:11][C:10]([CH:13]([CH3:15])[CH3:14])=[CH:9][CH:8]=1)=[O:6].[Br:16]N1C(=O)CCC1=O'\
'>C(Cl)(Cl)(Cl)Cl.CC(N=NC(C#N)(C)C)(C#N)C>'\
'[Br:16][C:13]([C:10]1=[CH:9][CH:8]=[C:7]([C:5](=[O:6])[CH2:4][CH2:3][CH2:2][Cl:1])[CH:12]=[CH:11]1)([CH3:15])[CH3:14]'
rxn = AllChem.ReactionFromSmarts(sma)
rxn.Initialize()
rats = rxn.GetReactingAtoms()
print(rats)
```
outputs:
```
((9,), (0, 1, 2, 3, 4, 5, 6, 7))
```
(all the unmapped atoms in your second reactant are automatically flagged as reacting since they don't appear in the products... these would be easy to filter out)

**Comment by greglandrum** [comment]
If your reactions are actually SMILES instead of SMARTS (as these are) you can probably get a long way by setting the `useSmiles` argument to `RxnSmartsToChemicalReaction()` to true and then looping over the reactant and product templates and calling `MolOps::sanitizeMol()` on each of them. I haven't tested this, but it could help.

**Comment by doctorx84** [comment]
Hi Greg,

As first:
Thankt you very much for the explanation and hard work on the toolkit as well!

I tryed your guess to loop over the reactants as well as the products and called the sanitizer against.
This was not the final solution but if i call as well updatePropertyCache() it is working fine.

The first problem was realy the different kekulized structures.
I do not recorgnized that before but i'm aware about that 'problem' form other stuff i did.
(Sometimes i'm blind 👎 )

I guess the second problem has to do with the explicite hydrogen count (solved with the call of updatePropertyCache()).
(This was figured out by usage of removeHs(*mol, false, true, true))

I will check my sets of ractions. 
If all of them are just smiles the problem is solved.
Otherwise i know about the problem and can take care of that later on.

Thank you again!

- Wolf

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
