### ISSUE TITLE
BRICSDecomposition does not break a particular ligand

### ISSUE THREAD

**Issue by ghiander** [rdkit/rdkit#2036]
Dear all,

I have recently tried to decompose a known drug that is Sertraline Hydrochloride using the function BRICSDecompose(). There is no problem with the code itself but the decomposition fails whereas I would have expected a fragmentation of the ligand into two fragments. 
Is there anything you can do to improve the fragmentation algorithm?

- RDKit Version: 2017.09.3
- Platform: Windows 10

I report the code below:
```
m = Chem.MolFromSmiles("CNC1CCC(c2ccc(Cl)c(Cl)c2)c2ccccc12")
AllChem.Compute2DCoords(m)
frags = BRICS.BRICSDecompose(m, returnMols=True)
```

**Comment by greglandrum** [comment]
Here's what's going on:
There are BRICS patterns associated with aliphatic carbon rings (it's atom type L15 in the original paper), and there are rules for L15 - L16 (aromatic carbon ring) and L15 - L5 (SP3 nitrogen). 
The RDKit encoding of the pattern for L15: `[C;$(C(-;@C)-;@C)]` requires that the linking atom and its two neighbors are all aliphatic C. That fails in your case since one of the neighbors is aromatic.

I think it's probably ok for us to change that pattern to `[C;$(C(-;@C)-;@[#6])]` in order to allow an aromatic neighbor. but I will need to think about it a bit more in order to be sure.

**Comment by ghiandonigianmarco** [comment]
I have spotted another one as well: "NS(=O)(=O)c1cc(ccc1Cl)C1(O)NC(=O)c2ccccc12" (Chlorthalidone)
Similar issue.
