### ISSUE TITLE
Best way to fragment aromatic molecule into radicals?

### ISSUE THREAD

**Issue by pstjohn** [rdkit/rdkit#2081]
**Description:**
- RDKit Version: 2018.03.4
- Platform: Mac OS X

The overall goal I'm trying to accomplish is to break a bond in a molecule and end up with SMILES strings for the two resulting radical species. At this point, I'm happy to stick to only single bonds outside of a ring.

If my example molecule is, for instance, `c1cc[nH]c1`, and I want to end up with `C1=C[N]C=C1` and `[H]`, what would the best way of doing that be? 

So far I've tried variants of the following code:

```python
mol = rdkit.Chem.MolFromSmiles('c1cc[nH]c1')
mol = rdkit.Chem.rdmolops.AddHs(mol)

for bond in mol.GetBonds():
    if {bond.GetBeginAtom().GetSymbol(), bond.GetEndAtom().GetSymbol()} == {'H', 'N'}:
        bond_idx = bond.GetIdx()

split_mol = rdkit.Chem.FragmentOnBonds(
    mol, bond_idx, addDummies=False)

fragmented_smiles = rdkit.Chem.MolToSmiles(
    split_mol, isomericSmiles=True)
```
which returns `'[HH].[H]c1[nH]c([H])c([H])c1[H]'`, i.e., 
1. Not breaking the aromaticity of the ring
2. seemingly adding hydrogens to both radicals

If I use a dummy atom, the bond appears to be breaking in the right place:
```python
split_mol = rdkit.Chem.FragmentOnBonds(
    mol, [bond_idx], addDummies=True, dummyLabels=[(0, 0)])
fragmented_smiles = rdkit.Chem.MolToSmiles(
    split_mol, isomericSmiles=True)
```
results in `'*[H].*n1c([H])c([H])c([H])c1[H]'`, 

but later explicitly deleting the wildcard atom still results in the added hydrogens and lack of breaking the aromatic structure noted above.

*Edit:* Working on this further, I seem to be able to narrow the issue down to the kekulization step if I manually remove the bond using an `RWMol`.
```python
split_mol = rdkit.Chem.RWMol(mol)
a1 = bond.GetBeginAtomIdx()
a2 = bond.GetEndAtomIdx()
split_mol.RemoveBond(a1,a2)

rdkit.Chem.SanitizeMol(split_mol)

fragmented_smiles = rdkit.Chem.MolToSmiles(split_mol)

```

This works for most molecules, but when the bond breaks the aromaticity, the last step will throw a `ValueError: Sanitization error: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4`

**Comment by greglandrum** [comment]
Congrats on picking one of the hardest examples for this particular problem. :-)

The underlying reason why this is hard is that the RDKit doesn't recognize the radical species `c1ccc[n]1` as aromatic (it generates a kekulization error). Given that it recognizes `c1cccc[c]1` as aromatic without problems, I think this is a bug (with more thought I may convince myself that it's ok, but at the moment it feels like a bug). It may be a bug that's hard to fix, but that's a different thing.

Fortunately, there's an easy solution to the problem: kekulize the molecules before you break the bonds. You also should call `SetNoImplicit()` on the atoms affected by the bond breakage in order to tell the RDKit that it shouldn't add additional implicit Hs to them.
Here's a little demo:
```
In [50]: m = Chem.MolFromSmiles('c1ccc[nH]1')

In [51]: mh = Chem.RWMol(Chem.AddHs(m))

In [52]: a1idx = 4

In [53]: a2idx = 9

In [59]: Chem.Kekulize(mh,clearAromaticFlags=True)

In [60]: mh.RemoveBond(a1idx,a2idx)

In [61]: mh.GetAtomWithIdx(a1idx).SetNoImplicit(True)

In [62]: mh.GetAtomWithIdx(a2idx).SetNoImplicit(True)

In [63]: Chem.SanitizeMol(mh)
Out[63]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [64]: Chem.MolToSmiles(mh)
Out[64]: '[H].[H]C1=C([H])C([H])=C([H])[N]1'
```
or, if you'd rather not have the Hs in the output SMILES:
```
In [66]: Chem.MolToSmiles(Chem.RemoveHs(mh))
Out[66]: 'C1=C[N]C=C1.[H]'
```

I have a suspicion that this is more complicated if the ring isn't aromatic, but I will address that with either a new comment or an edit to this one.

**Comment by pstjohn** [comment]
Thanks for the help with this!! That code definitely clears things up and fixes my fragmentation issue.

I'll mention though that there may be a bug in `RemoveHs`. I'm getting a segfault for a different bond in that molecule.

```python
from rdkit import Chem

m = Chem.MolFromSmiles('c1ccc[nH]1')
mh = Chem.RWMol(Chem.AddHs(m))

a1idx = 0
a2idx = 5

Chem.Kekulize(mh,clearAromaticFlags=True)
mh.RemoveBond(a1idx,a2idx)
mh.GetAtomWithIdx(a1idx).SetNoImplicit(True)
mh.GetAtomWithIdx(a2idx).SetNoImplicit(True)
Chem.SanitizeMol(mh)

# Generates a segfault
mh = Chem.RemoveHs(mh)

print(Chem.MolToSmiles(mh))
```

**Comment by pstjohn** [comment]
Ah OK, good to know. Thanks again for the help! 
No rush from me on that issue, for now I'm getting around it by running `MolFromSmiles`, `MolToSmiles` on each radical.

I'll close this issue since you answered my main question -- I'm happy to blame this on 'user error' on my part :).
