### ISSUE TITLE
MCS misses a ring with equivalent atoms

### ISSUE THREAD

**Issue by Mickdub** [rdkit/rdkit#2166]
**Description:**

![image](https://user-images.githubusercontent.com/4589724/48504333-2271cb00-e80a-11e8-911c-7e0ef925867e.png)

![image](https://user-images.githubusercontent.com/4589724/48504366-31f11400-e80a-11e8-8da1-1f0575c20e8f.png)

These molecules give this as the mcs...

![image](https://user-images.githubusercontent.com/4589724/48504391-4208f380-e80a-11e8-9465-f68e461d3f30.png)

Unfortunately, it doesn't match the ring containing 3 F's even though all the atoms are identical. This happens in many similar examples. Can this be fixed? Is there a way to capture that ring in the match? I have tried using all sets of parameters I can find.

 
- RDKit Version: 2017.03.2
- Platform: Python? Jupyter Notebook? Unix? Mac?

```
R= Chem.MolFromSmiles('Cc1nc(Nc2ncc(C(=O)N=C3C=CC(=O)C=C3C(F)(F)F)s2)cc(N2CCN(CCO)CC2)n1')
P= Chem.MolFromSmiles('Cc1nc(Nc2ncc(C(=O)Nc3cc(SCC(NC(=O)CCC(N)C(=O)O)C(=O)NCC(=O)O)c(O)cc3C(F)(F)F)s2)cc(N2CCN(CCO)CC2)n1')
rdFMCS.FindMCS([R,P],Chem.rdFMCS.BondCompare.CompareAny,Chem.rdFMCS.AtomCompare.CompareElements)
```

**Comment by Mickdub** [comment]
If you just change all bond types in both molecules to single, that works as a workaround. Apparently, the BondCompare.CompareAny doesn't let you really compare any.

**Comment by greglandrum** [comment]
Apologies for the slow reply.
What's happening here is that you've provided the arguments to `rdFMCS.FindMCS()` in the wrong order. It would be nice if you could get warnings about this, but the way the wrappers are written the comparison types - things like `BondCompare.CompareAny` - are just integers, so Python just can't tell the difference.
If you provide the keywords as well as the arguments things work fine:
```
In [31]: res = rdFMCS.FindMCS([R,P],bondCompare=Chem.rdFMCS.BondCompare.CompareAny,atomCompare=Chem.rdFMCS.AtomCompare.CompareElements)

In [32]: res.smartsString
Out[32]: '[#6]-[#6]1:[#7]:[#6](-[#7]-[#6]2:[#7]:[#6]:[#6](:[#16]:2)-[#6](=[#8])-[#7]=,-[#6]2-,:[#6]=,:[#6]-,:[#6](-,:[#6]=,:[#6]-,:2-[#6](-[#9])(-[#9])-[#9])=,-[#8]):[#6]:[#6](:[#7]:1)-[#7]1-[#6]-[#6]-[#7](-[#6]-[#6]-1)-[#6]-[#6]-[#8]'
```

It is almost always a good idea to provide the keywords themselves for optional arguments in order to prevent things like this from happening.
