### ISSUE TITLE
No error on a molecule with incorrect valence

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2195]
```
import rdkit.Chem as Chem 
mol = Chem.MolFromSmiles('C1=Cc2ccco(C(=O)Cn3ccc4cc[nH]c43)c2=N1')
```

`o` has an incorrect valence of 3, but no error occurs (`sanitize` doesn't help).

`rdkit.__version__='2018.09.1'`

**Comment by sirbiscuit** [comment]
Hey @shayakhmetov,

it seems that the valence of atoms in aromatic rings is not checked. I tried to find a solution for this problem, but it looks a bit trickier than I thought. So let's mention @greglandrum and hope that he has an elegant solution in mind.

Some details: the problem lies in [Atom.cpp at line 216](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Atom.cpp#L216). The variable accum holds the sum of the bond orders of all incident bonds. If the investigated atom is aromatic, accum will be overwritten with a legal valence value (in line 216). For example, the oxygen in ```c1cc2ccco(#C)c2c1``` has valence 6 = 1.5 + 1.5 + 3 (two aromatic and one triple bond), but the variable accum is set to 2 since this is the only possible valence of oxygen. Finally, this value is also returned as the explicit valence of this atom.

**Comment by shayakhmetov** [comment]
@greglandrum, can you please elaborate on whether there would be a fix or not?

**Comment by shayakhmetov** [comment]
we can close the issue, cannot reproduce in '2019.03.2'. Thanks!

**Comment by shayakhmetov** [comment]
Found another example in the rdkit 2019.03.2

'c2ncc3n2-c2ccc(nc2)-o(C)-s-3C'
The oxygen has a valency of 3, but the molecule is valid

**Comment by greglandrum** [comment]
Wow, where did that SMILES come from? That's pretty horrible and wrong (specifically the O and S atoms that are indicated as aromatic but only have single bonds coming from them).

This definitely should be rejected.

**Comment by greglandrum** [comment]
> Wow, where did that SMILES come from? That's pretty horrible and wrong (specifically the O and S atoms that are indicated as aromatic but only have single bonds coming from them).
> 

I realize that there's every possibility that it came from the RDKit. :-)

**Comment by shayakhmetov** [comment]
It didn't come from the RDKit per se, and I agree that RDKit should consider it invalid w.r.t the valencies/aromaticity.
