### ISSUE TITLE
Square brackets sometimes missing in SMILES output for undervalent carbons

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#2339]
Undervalent atoms should be shown in SMILES strings within square brackets. Here's some code that sets the hydrogen count on the first atom in three molecules to 0, 1, and 2.

```
from rdkit import Chem
import rdkit
print(rdkit.__version__)

for hcount in range(3):
    print("hcount is %d"% hcount)
    for smi in ["C", "C1CCCCC1", "c1ccccc1"]:
        mol = Chem.MolFromSmiles(smi)
        atom = mol.GetAtoms()[0]

        # Set hydrogen count on atom
        atom.SetNoImplicit(True)
        atom.SetNumExplicitHs(hcount)
        atom.UpdatePropertyCache() # so that valence is reported correctly
        assert(atom.GetTotalNumHs(False) == hcount)
        print(Chem.MolToSmiles(mol))
    print()
````
This gives:
```
2018.09.1
hcount is 0
C
C1CCCCC1
c1ccccc1

hcount is 1
[CH]
[CH]1CCCCC1
c1ccccc1

hcount is 2
[CH2]
C1CCCCC1
c1ccccc1
````
When hcount is 0, the hydrogen count appears to be ignored completely. When hcount is 1 or 2, it works for methane and cyclohexane but it appears to be ignored in benzene.

**Comment by greglandrum** [comment]
I think we probably disagree about what the bugs are, but we can agree that something is not quite right. :-)

With the exception of `[CH2]1CCCCC1` and `[cH]1ccccc1`, every molecule you create here is incorrect and totally nonphysical since you've set the number of Hs without changing either charge or the number of radical electrons. 

As an example take the bare C atom with no Hs, no charge, and no radical electrons. What is that? What SMILES should be produced? Certainly not `[C]`, which corresponds to a C atom with 4 radicals.

If you set the molecule up properly, things work:
```
In [27]: m2 = Chem.MolFromSmiles('C')                                                                      

In [28]: m2.GetAtomWithIdx(0).SetNoImplicit(True)                                                          

In [29]: m2.GetAtomWithIdx(0).SetNumExplicitHs(0)                                                          

In [30]: m2.UpdatePropertyCache()                                                                          

In [33]: Chem.AssignRadicals(m2)                                                                           

In [34]: Chem.MolToSmiles(m2)                                                                              
Out[34]: '[C]'

In [35]: m2.GetAtomWithIdx(0).GetNumRadicalElectrons()                                                     
Out[35]: 4
```

There's an argument to be made that the SMILES writer should do a sanity check on output, recognize these completely bogus cases, and raise a warning, but it doesn't seem like high priority.

**Comment by baoilleach** [comment]
I didn't know about the radical count. Presumably I can also increment/decrement it with get/setNumRadicalElectrons() also. In any case, this solves the problem I was having. Marking as closed from my point of view.
