### ISSUE TITLE
VSA_EState {1, ..., 10} calculated by rdkit doesn't seem correct.

### ISSUE THREAD

**Issue by c56pony** [rdkit/rdkit#2372]
**Description:**
The values ​​of VSA_EState {1, ..., 10} calculated by the rdkit module seem a bit strange.
The cause is probably an incorrect array of bin edges.
According to the reference(ex. http://rdkit.org/docs/source/rdkit.Chem.EState.EState_VSA.html),
the sequence should be [4.78, 5.00, 5.410, 5.740, 6.00, 6.07, 6.45, 7.00, 11.0].
However, in practice, [-0.390, 0.290, 0.717, 1.165, 1.540, 1.807, 2.05, 4.69,. 9.17, 15.0] are used.

- RDKit Version:2018.09.1
- Platform:Python 3.6.6 (default, Mar  8 2019, 18:24:30), Ubuntu 18.04.2 LTS

I think there is an error in line 40 of the rdkit/rdkit/Chem/EState/EState_VSA.py.
```
--- rdkit-Release_2018_09_1/rdkit/Chem/EState/EState_VSA.py       2018-10-22 11:29:34.000000000 +0900
+++ EState_VSA.py.mod       2019-03-28 18:03:05.986954933 +0900
@@ -37,7 +37,7 @@ def VSA_EState_(mol, bins=None, force=1)
     return mol._vsaEState
 
   if bins is None:
-    bins = estateBins
+    bins = vsaBins
   propContribs = EStateIndices_(mol, force=force)
   volContribs = VSAContribs_(mol)
```

I also compared the rdkit VSA_EState values to the manually calculated values.
But, they did not match.
```
import numpy as np
from rdkit import Chem
from rdkit.Chem.EState import EState_VSA
smi = "Oc1ccccc1" # phenol
mol = Chem.MolFromSmiles(smi)
estate_vsaR = np.array([getattr(EState_VSA,"VSA_EState"+str(i))(mol) for i in range(1,11)])
print("ESTATE_VSA{1,...,10}(rdkit) =\n",estate_vsaR)
```
ESTATE_VSA{1,...,10}(rdkit) =
 [ 0.          0.          0.          0.          0.          0.  0.          0.         17.66666667  0.        ]
```
from rdkit.Chem.EState.EState import EStateIndices
from rdkit.Chem.MolSurf import _LabuteHelper
vsaContribs = _LabuteHelper(mol)[1:]
estateContribs = EStateIndices(mol)
vsaBins = [-np.inf, 4.78, 5.00, 5.410, 5.740, 6.00, 6.07, 6.45, 7.00, 11.0, np.inf]
estate_vsaM,_ = np.histogram(vsaContribs,vsaBins,weights=estateContribs)
print("ESTATE_VSA{1,...,10}(manual) =\n",estate_vsaM)
```
ESTATE_VSA{1,...,10}(manual) =
 [0.         0.         8.63222222 0.         0.32175926 8.71268519 0.         0.         0.         0.        ]
```
np.allclose(estate_vsaR,estate_vsaM)
```
False

**Comment by luizimgiolo** [comment]
Sorry, but using mordred
[mordred                   1.2.0              pyhe5148d4_0]
And 2020 version of rdkit
[rdkit                     2020.03.3.0      py37hc20afe1_1]

I'm still gettin this kind of error.
Thank you all for the great work with this amazing tool

**Comment by greglandrum** [comment]
@luizimgiolo : in order to be able to help we need to know what input molecule you used, what values you saw, and why you think they are wrong.

**Comment by luizimgiolo** [comment]
These 3 SMILES are examples
1) CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@](C#N)([C@H](O)[C@@H]1O)C1=CC=C2N1N=CN=C2N)OC1=CC=CC=C1

2) COCC1O[C@H]2OC3C(COC)O[C@@H](OC4C(COC)O[C@@H](OC5C(COC)O[C@@H](OC6C(COC)O[C@@H](OC7C(COC)O[C@@H](OC8C(COC)O[C@@H](OC1[C@H](OC)[C@@H]2OC)[C@@H](OC)[C@H]8OC)[C@@H](OC)[C@H]7OC)[C@@H](OC)[C@H]6OC)[C@@H](OC)[C@@H]5OC)[C@@H](OC)[C@H]4OC)[C@@H](OC)[C@H]3OC

3) COCC1O[C@H]2OC3C(COC)O[C@@H](OC4C(COC)O[C@@H](OC5C(COC)O[C@@H](OC6C(COC)O[C@@H](OC7C(COC)O[C@@H](OC8C(COC)O[C@@H](OC1[C@H](OC)[C@@H]2OC)[C@@H](OC)[C@H]8OC)[C@@H](OC)[C@H]7OC)[C@@H](OC)[C@@H]6OC)[C@@H](OC)[C@H]5OC)[C@@H](OC)[C@H]4OC)[C@@H](OC)[C@H]3OC.CC(=O)O[C@H]9C(=O)[C@]%10(C)[C@@H](O)C[C@H]%11OC[C@@]%11(OC(=O)C)C%10[C@H](OC(=O)c%12ccccc%12)[C@]%13(O)C[C@H](OC(=O)[C@H](O)[C@@H](NC(=O)c%14ccccc%14)c%15ccccc%15)C(=C9C%13(C)C)C

I think they are wrong because they are out of range.
I upload a file with my output of this cases 

[crazy_vsa.zip](https://github.com/rdkit/rdkit/files/5052656/crazy_vsa.zip)
