### ISSUE TITLE
Cannot set just one parameter in FingerprintMol

### ISSUE THREAD

**Issue by tawe141** [rdkit/rdkit#2499]
**Description:**
`FingerprintMol()` is giving me variable length fingerprints, and I need them to be constant. It seems easy enough, just set the `minSize=` to whatever I want (in this case, 2048, the default fpSize). However, it appears I have to define all other parameters despite them having default values according to the documentation for `RDKFingerprint()`. Running `FingerprimtMol(m, minSize=2048)` returns the following:

```
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/rdkit/Chem/Fingerprints/FingerprintMols.py", line 72, in FingerprintMol
    fp = fingerprinter(mol, fpArgs['minPath'], fpArgs['maxPath'], fpArgs['fpSize'],
KeyError: 'minPath'
```

How do you selectively assign a parameter without having to define all others?

- RDKit Version: 2019.03.2.0
- Platform: Ubuntu 18.04, Python 3.6

**Comment by greglandrum** [comment]
First a tip, then an explanation:
In general I would suggest using the fingerprinting functions directly instead of using `FingerprintMols()`.  It's more explicit and can be easier to understand what's going on. To get the RDKit fingerprints that `FingerprintMols()` generates by default, you can call `Chem.RDKFingerprint()`. We should deprecate that module at some point.

If you do want to keep using `FingerprintMols`(),  a "solution" would be something like:
```
In [11]: params = FingerprintMols.FingerprinterDetails()

In [12]: params.tgtDensity = 0

In [13]: len(FingerprintMols.FingerprintMol(Chem.MolFromSmiles('CCC'),**params.__dict__))
Out[13]: 2048
```

**Comment by tawe141** [comment]
I see. RDKFingerprint works well. In that case, could we change the Getting
Started page to explicitly use a fingerprint type?

https://www.rdkit.org/docs/GettingStartedInPython.html#fingerprinting-and-molecular-similarity

**Comment by greglandrum** [comment]
Yep, good point
