### ISSUE TITLE
MolFromSmiles failure causes memory leak/double free

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#2556]
**Description:**

There appears to be a double free() in MolFromSmiles if the underlying topology is in error, as with "C1C1". In an older version of RDKit, there is no double free, but there is a memory leak.

I tested this under 2018.03.4, 2019_03_3, and git HEAD as of 22 July 2019.

- RDKit Version:  '2019.09.1dev1'
- Platform: macOS Mojave 10.14.4

In RDKit-2019_03_3 and git HEAD, MolFromSmiles("C1CC1") causes a free() error, saying "pointer being freed was not allocated".

```
>>> from rdkit import Chem
>>> Chem.MolFromSmiles("C1C1")
[11:16:02]

****
Pre-condition Violation
bond already exists
Violation occurred on line 386 in file /Users/dalke/cvses/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph) .second)
****

python(16524,0x112cec5c0) malloc: *** error for object 0x7fef7b890298: pointer being freed was not allocated
python(16524,0x112cec5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort
```

In RDKit-2018.03.4 it correctly gives the "Pre-condition Violation" (just like the newer versions) but it does not have the double free. Instead, it has a memory leak.

I assume the change causing the above was part of trying to fix that leak, but that's only a guess.

The reproducible is:
```
from rdkit import Chem
Chem.MolFromSmiles("C1C1")
```

**Comment by greglandrum** [comment]
I can't reproduce this behavior on my linux box. @adalke: you're running on a Mac, right?

**Comment by adalke** [comment]
Yes, running macOS Mojave 10.14.4, "Apple LLVM version 10.0.1 (clang-1001.0.46.4)". I only built these versions this morning when trying to get a more recent build for the report.

If you don't get the crash, can you reproduce the memory leak?
```
from rdkit import Chem
while 1:
  Chem.MolFromSmiles("C1C1")
```
should show increasing memory use.

When I run the following using the Anaconda build of 2018.03.4:
```
import psutil
from rdkit import Chem
process= psutil.Process()
Chem.MolFromSmiles("C1C1")  
start_rss = process.memory_info().rss
num_calls = 0
for i in range(1000):
  num_calls += 1
  Chem.MolFromSmiles("C1C1") 

rss = process.memory_info().rss - start_rss
print("leaks", rss/num_calls, "bytes/call")
```
I get "Violation occurred on line 356 in file /Users/glandrum/anaconda5/conda-bld/rdkit_1534389448433/work/Code/GraphMol/ROMol.cpp" and "leaks 1400.832 bytes/call"

**Comment by bp-kelley** [comment]
I believe there is a leak, but I can’t reproduce the crash.  I’m going to run valgrind shortly.

----
Brian Kelley

**Comment by mgarort** [comment]
Hi @bp-kelley  and @greglandrum ,

I'm having the same issue in RDKit version `2020.03.3`, installed with `conda-forge` (since the default `conda` installation gave me an old version from 2018 that didn't have inchi keys).

Since this issue is closed, is there a version I can install that doesn't have the memory leak? 

Thanks a lot!

**Comment by greglandrum** [comment]
@mgarort which operating system are you using?

**Comment by mgarort** [comment]
Hi @greglandrum , thanks for your quick response. I'm on Ubuntu 18.

I'm currently investigating and I've realized that the issue is indeed a memory leak but it's not exactly the same as the one reported by @bp-kelley , so I'm investigating further to see where it's coming from. I am using `Chem.MolFromSmiles` and `Chem.MolToSmiles` within `pandas.DataSeries.map()`, and I'm also filling in the argument `canonical`  for `Chem.MolToSmiles` with `functools.partial`.

I will investigate more and come back with a minimal example where the memory leak happens.

**Comment by mgarort** [comment]
Hi @greglandrum ,

I've created another issue with a detailed explanation of my (potential) memory leak, since it seems to be different from the one in this issue. Thanks!
