### ISSUE TITLE
Support range-based charge queries from SMARTS

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2604]
**Description:**
This would be `[+{1-}]`, etc.

**Comment by sroughley** [comment]
I like the  idea - is it 'standard' SMARTS (whatever that might mean!)?

**Comment by greglandrum** [comment]
Nope. These are RDKit extensions: https://github.com/rdkit/rdkit/blob/master/Docs/Book/RDKit_Book.rst#range-queries

CACTVS has something similar (at least that's where the inspiration came from).

**Comment by sroughley** [comment]
Thanks Greg - that's an interesting read!

Any plans to support $$()-style recursive queries (e.g. https://www.xemistry.com/docs/html/tcl_reference-49.htm) - "Standard recursive SMARTS does not know about atoms and bonds already matched in upper levels - the complete structure can be matched by the atoms in the recursive expression. This variant blocks all atoms and bonds already matched in any previous recursion level."?

**Comment by greglandrum** [comment]
I'm not even sure I know what that means. ;-)

Seriously though: sounds like one of those "someone had a use for it, once" things.

**Comment by sroughley** [comment]
I can't think of a good example at the moment, but a (very) trivial example would be for e.g. the SMILES `CC`, then the SMARTS `[C][C;$(CC)]` would match, whereas `[C][C;$$(CC)]` would not, because the 1st C atom has already meen matched. _I think_!
You can probably come up with a use for e.g. looking for substitution patterns on disubstituted aromatics.
