### ISSUE TITLE
Bond removal and readdition changes isomer

### ISSUE THREAD

**Issue by harsh6646** [rdkit/rdkit#2627]
**Description:**

- RDKit Version: 2018.09.1
- Platform: Pop OS 18.04 LTS (Ubuntu 18.04 LTS)

When removing and adding the same bond the chirality sometimes changes if the new bond has a higher idx than before.
I am not a chemist but from my understand rdkit is using the order of the bonds to determine order in which different R groups added to the chiral center. Perhaps due to this when I remove a bond to make fragments, and later need to combine then, the same isomer is not created. Any help is appreciated.

(Code from python API)

```python
from rdkit import Chem

Initmol = Chem.MolFromSmiles("[4*][C@H](c1cccs1)[C@H]([4*])C")
smiles = Chem.MolToSmiles(Initmol, isomericSmiles=True)
print(smiles)
mol = Chem.MolFromSmiles(smiles)
# C[C@H](c1cccs1)[C@H](C)C
emol = Chem.EditableMol(mol)
emol.RemoveBond(1, 2)

emol.AddBond(1, 2, Chem.rdchem.BondType.SINGLE)
mol2 = emol.GetMol()
new_smiles = Chem.MolToSmiles(mol2, isomericSmiles=True)
print(new_smiles)

# Outputs:
# [4*][C@H](c1cccs1)[C@H]([4*])C
# [4*][C@@H](c1cccs1)[C@H]([4*])C
```
This does not make sense as I should be recreating the original molecule, not a isomer of it.

**Comment by harsh6646** [comment]
If there was a way to change Bond Index or ordering of bonds on an atom then it would allow developers to create the isomer they want.

**Comment by bp-kelley** [comment]
This is exactly what is happening.  You are changing the order of the bonds around the atom.

```
>>> mol = Chem.MolFromSmiles(smiles)
>>> emol = Chem.RWMol(mol)
>>> order = [bond.GetIdx() for bond in emol.GetAtomWithIdx(1).GetBonds()]
>>> order
[0, 1, 6]
>>> emol.RemoveBond(1, 2)
>>> emol.AddBond(1, 2, Chem.rdchem.BondType.SINGLE)
10
>>> order = [bond.GetIdx() for bond in emol.GetAtomWithIdx(1).GetBonds()]
# note atom #6 has become #5
>>> order
[0, 5, 9]
```

In this case as you've changed the clockwise/counter clockwise ordering, you need to invert chirality:

```
>>> Chem.MolToSmiles(emol)
'[4*][C@@H](c1cccs1)[C@H]([4*])C'

>>> emol.GetAtomWithIdx(1).InvertChirality()
>>> Chem.MolToSmiles(emol)
'[4*][C@H](c1cccs1)[C@H]([4*])C'
```

**Comment by harsh6646** [comment]
Thank you for your response.
Right, however there are times where I do not need to invert chirality.
I trying breaking and reconnecting thousands of bonds around hundreds of molecules, and I cannot tell which one needs their chirality inverted to make it the same as the original molecule.
Would there be any good way to track this chirality issue and only invert as needed?

**Comment by harsh6646** [comment]
Currently, I store the chiralTag of the molecule where I break the bond and restore it when I recombine it, however because fragments are rendered different than the original molecule, I may be running into some issues there. When I added the tracking of the chiralTag less False Fragments were generated.

**Comment by harsh6646** [comment]
To clarify I want to order the bonds for a given atom, so the chirality is exactly as I want it to be.
Any help would be appreciated.

**Comment by greglandrum** [comment]
There's probably a way to do this, but I want to understand what exactly you're trying to do.
You say "I want to order the bonds for a given atom, so the chirality is exactly as I want it to be"
Given that the RDKit understands atomic chirality based on the order of the bonds I'm not quite sure what that means or how you would tell the RDKit what chirality you want so that it can either give you the appropriate order of the bonds or, more likely, the correct chiral tag.

Do you want to replace a bond in an molecule without changing the stereochemistry?

**Comment by harsh6646** [comment]
Sorry for the lack of clarity, its my first time doing chemistry related coding.

Do you want to replace a bond in an molecule without changing the stereochemistry?
Yes, but I cannot use the replace substruct or replace bond methods as I want both the broken parts and later on rebuild some of these broken bonds.

I break molecules into fragments (replacing the brokes ends of both new ends with 0 atomic number, and different isotopes as IDs). The breakdown works fine, I get only valid sub fragments.
Valid: being a proper substructure of the original molecule.

However when I rebuild the fragments into different substructures, I need to remove that placeholder atomic number 0 on both fragments and reattach them. Here is where the issue happens.
example:
CCC(NO)CC breaks into CCC([1*])CC and [2*]NO
When I recombine them potentially get CCC(CC)NO.
The ordering of the R groups around C is changed, making the rebuild not the same as the original.
I was wondering if there was anyway for me to indicate, when adding a bond, that NO should be ordered before CC.

**Comment by greglandrum** [comment]
ok, I think I'm starting to get it.

**Comment by harsh6646** [comment]
Original mol: ```COc1ccc(N2CCN([C@H](c3cccs3)[C@@H](C)NC(=O)C(=O)NCc3ccco3)CC2)cc1```
frag 1: ```[106*][C@H]([116*])[C@H]([112*])C```
frag 2: ```[117*]c1cccs1```
frag 1 and 2 from BRICS.Decompose and from my code(i'ved just changed the isotope on the pseudo atoms)
desired: ```[4*][C@H](c1cccs1)[C@H]([4*])C``` (from BRICS.Decompose())
Getting: ```[4*][C@H](C)[C@@H]([4*])c1cccs1``` (from my code)

I'm trying to build up different sub structures as opposed to breaking down to them.


Subfragments from BRICS.Decompose() I do cannot build. (2nd one is the given example)
![Old_only](https://user-images.githubusercontent.com/21232963/63540442-15e17800-c4ea-11e9-9c1e-47eb3f2d11a9.png)

Subfragments BRICS.Decompose() cannot built, but I can, some have this bond order issue. (4th column, 5th row is given example)
![New_only](https://user-images.githubusercontent.com/21232963/63540499-2b56a200-c4ea-11e9-97be-a64d136bcd1d.png)

**Comment by bp-kelley** [comment]
@harsh6646 did the gist help out?

**Comment by atomoton** [comment]
To carry on for @harsh6646  here (I am now also working on this issue a little bit), unfortunately the gist does not help (or I am misunderstanding it). 

Specifically there is one bond being deleted (a-b), two atoms being added (x,y), and then two new bonds being added ((a-x), (y-b)).

So originally the bonds for atom a might look like this: 
[(2, 3), (3, 4), (3, 5)]
then afterwards they look like this:
[(3, 4), (3, 5), (3, 30)]
**What I need is to have them look like this:**
[(3, 30), (3, 4), (3, 5)]

Similarly, for atom b:
old b bonds: [(1, 2), (2, 3)]
new b bonds: [(1, 2), (2, 31)]
**In this case there is no issue (but not always.)**


However, as far as I can tell, adding a bond to an atom always adds it at the end of this list, and the order of this list is being used to define the chirality? If I delete those other bonds and add all of them back in the correct order, this error propagates to all the atoms that were connected to those atoms as well, ending only when we get to atoms with only one bond or where the removed bond was last in the list of bonds.

the eMol.ReplaceBond() function is also not going to work here, as even if I replace one bond, I will still need to add another for the other atom.

**Comment by bp-kelley** [comment]
The gist doesn’t preserve ordering, it preserves chirality, I.e. it knows when to flip the chirality in the output molecule.

**Comment by atomoton** [comment]
Does it flip the chirality of all stereocenters? Or only the incorrect ones?

**Comment by bp-kelley** [comment]
The incorrect ones.  The “trick” here is that the attachment points in all fragments need to be dummy atoms so we know the original bond orders.

----
Brian Kelley

**Comment by atomoton** [comment]
I do have dummy atoms, and I am storing the chiral tags, but I'm not sure I understand how to apply this gist to this issue.

The issue is not just with zipping molecules together, but also in breaking them down. In the process of breaking apart a molecule we’re destroying one bond and adding two. This sometimes borks the stereochemistry, long before we attach molecule fragments back together.

Ideally we should see that even just the frag_a -> dummy_atom_a bond and the frag_b -> dummy_atom_b bond should have the same stereochemistry as before fragmentation. However, upon adding the bond to the dummy atom, the stereochemistry often changes (because the bond order changes).

**Comment by atomoton** [comment]
@bp-kelley Okay so we have managed to get something working by sidestepping this entirely, and simply creating a different non rdchem.Mol object, editing the bonds in that object, and then using that object to build each fragment from scratch as an editableMol object.

Thanks all for your help and feel free to close this issue if you want. **Though I still think it would be really nice to add a feature to the editableMol class that allows you to reorder the bonds for a given atom.**

**Comment by adalke** [comment]
The main idea of Brian's code snippet is to look at the parity of the permutation order of the bonds, which is either even or odd. If it's changed, then swap the chirality from CW to CCW or back.

He mentioned some writings I did on the topic. The most specific is at http://www.dalkescientific.com/writings/diary/archive/2016/08/14/fragment_chiral_molecules.html .

The work I did then lead to some fixes in the RDKit, which should have improved some of the errors I found.

My general view these days is to manipulate things as SMILES strings, rather than as molecule objects, because getting chirality (and double-bond stereochemistry) correct, while editing a molecule object, ended up being difficult and confusing.

**Comment by atomoton** [comment]
Wow! Thanks for sharing the link, that’s a remarkably clear analysis of this issue! Since the consensus seems to be that it’s better to deal with this outside of the Chem.Mol format anyway, I feel a little better about the approach we ended up taking, which only converts back to Mol at the end, when finished.
