### ISSUE TITLE
rdkit doesn't compile with boost-1.71

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#2648]
**Description:**

recent builds with brew on a mac broke because of the recent
update of boost from 1.70 to 1.71.

cmake doesn't detect boost-python anymore

```
brew install --HEAD rdkit
```

I am updating the brew recipe.
However, this might hit others, so here is the issue for rdkit.

**Comment by bp-kelley** [comment]
This is a cmake issue not an rdkit one.

https://gitlab.kitware.com/cmake/cmake/issues/19658

It looks like post boost 1.71 there may be a consistent path  for cmake to find boost.

You can set the boost paths explicitly, but this is relatively painful.

**Comment by UnixJunkie** [comment]
always a pleasure to have to deal with cmake...

**Comment by UnixJunkie** [comment]
Isn't there a fix we can apply to CMakeLists.txt so as to get rid of the cmake issue?

**Comment by greglandrum** [comment]
The problem is not really the fault of the cmake developers. Boost dependencies are very complicated and can change from release to release. The cmake folks keep up as best as they can.

There's nothing we can do about this that wouldn't be a gross hack; we need to wait for a version of cmake that supports the new boost.

Is there some reason you need boost 1.71? The RDKit certainly doesn't take advantage of anything that's new in it.

**Comment by UnixJunkie** [comment]
No, I don't need boost 1.71. It's just that boost 1.71 broke the build of rdkit with brew on mac.
The fix that I am currently testing it to pin the boost (and boost-python3) versions the rdkit
brew recipe requires (which we should have done long time ago, probably).
