### ISSUE TITLE
rdkit.Chem.Draw Error

### ISSUE THREAD

**Issue by hl2500** [rdkit/rdkit#2684]
Good Evening, I was implementing the code below:
```
mol_list = [Chem.MolFromSmiles(x) for x in smile_list]
dicarbonyl = Chem.MolFromSmarts('*C(=O)C(=O)*')
match_list = [mol.GetSubstructMatch(dicarbonyl) for mol in mol_list]
Draw.MolsToGridImage(mol_list, highlightAtomLists=match_list, molsPerRow=5)
```
There is an error:
```
OSError: cannot identify image file <_io.BytesIO object at 0x2b40d1a3e518>
```
What can I do to solve this problem? Thank you!

**Comment by greglandrum** [comment]
We need more information in order to be able to help.

Please let us know:
- which version of the rdkit are you using?
- are you using anaconda python?
- which version of  python are you using?
- which operating system?
- did you get the error while running a script, at the command line, or using Jupyter?
