### ISSUE TITLE
legend font & size in MolToImage is hardcoded

### ISSUE THREAD

**Issue by NKUCodingCat** [rdkit/rdkit#2758]
**Configuration:**

- RDKit Version: - 2018.09.1
- Operating system: - Fedora 26
- Python version (if relevant): - 3.7.1
- Are you using conda?  - yep
- If you are using conda, which channel did you install the rdkit from? - rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

```
Your code sample here
```

In https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Draw/__init__.py#L140 , legend in `rdkit.Chem.Draw.MolToImage` is forced as sans, size=12

Will it be configable in future?

**Comment by greglandrum** [comment]
`rdkit.Chem.Draw.MolToImage()` uses the old drawing code and, as such, will not be expanded.
We really need to update the docstrings in the Python so that you have a chance to figure this out on your own. Sorry about that.

The supported drawing code, using a MolDraw2D object, does not currently allow the font to be changed, though you do have some control over the font size.
This would be a great thing for us to add for a future RDKit version.

**Comment by PjFlan** [comment]
Hi Greg,

I am currently trying to change the legend font size of a MolDraw2DCairo instance using `drawOptions().legendFontSize = 20`. However it does not work and the default of 40 remains. It's strange because other properties such as `maxFontSize` can be changed

Can you suggest a method for changing the font size?

**Comment by DavidACosgrove** [comment]
Hi @PjFlan,
What version of RDKit are you using?  I have just tried with 2020.03.2 and it works for me.  Can you post a small snippet of code that demonstrates the problem you are seeing?
Thanks,
Dave

**Comment by PjFlan** [comment]
Hi David,
I am using version 2020.03.1 but have since realised the source of my error (nothing to do with RDKit so I won't describe).

I appreciate the help.
Thanks,
Padraic
