### ISSUE TITLE
Wrong InChIKey generation

### ISSUE THREAD

**Issue by Junsu** [rdkit/rdkit#2770]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Linux/Ubuntu 18.04
- Python version (if relevant): python 3.6
- Are you using conda? No
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? build from source code

**Description:**

rdkit.Chem.inchi.MolToInchiKey function generated wrong InChIKey.

* Molecule : https://www.rcsb.org/ligand/HSR
* Input : 	InChI=1/C8H15NO6/c1-3(11)9-5-7(13)6(12)4(2-10)15-8(5)14/h4-8,10,12-14H,2H2,1H3,(H,9,11)/t4-,5-,6-,7-,8-/m1/s1/f/h9H
* Correct InChIKey : OVRNDRQMDRJTHS-HEEJIFACDV
* RDKit generated InChIKey : OVRNDRQMDRJTHS-FMDGEEDCSA-N

```
#!/usr/bin/env python3

import rdkit
from rdkit import Chem
from rdkit.Chem import inchi as rd_inchi

def main() :
    # https://www.rcsb.org/ligand/HSR
    hsr_pdb_inchi = "InChI=1/C8H15NO6/c1-3(11)9-5-7(13)6(12)4(2-10)15-8(5)14/h4-8,10,12-14H,2H2,1H3,(H,9,11)/t4-,5-,6-,7-,8-/m1/s1/f/h9H"
    hsr_mol = rd_inchi.MolFromInchi(hsr_pdb_inchi)
    hsr_inchi = rd_inchi.MolToInchi(hsr_mol)
    hsr_inchikey = rd_inchi.MolToInchiKey(hsr_mol)

    print("===========")
    print("HSR")
    print(hsr_pdb_inchi)
    print(hsr_inchikey) # Correct InChIKey = OVRNDRQMDRJTHS-HEEJIFACDV
    print(hsr_inchi)

main()
```

**Comment by greglandrum** [comment]
If you look carefully you will notice that the InChI from the PDB is not a standard InChI: it starts with `InChI=1/` instead of `InChI=1S/`
By default the RDKit generates standard InChIs.

If you want an InChI with a FixedH layer (which the InChI you show has), then you need to do:
`Chem.MolToInchi(m,options='/FixedH')`

As a general comment: converting InChIs into molecules is generally not a great idea. The format is not designed for that.
