### ISSUE TITLE
Help manipulating rings in 3D

### ISSUE THREAD

**Issue by tarungog** [rdkit/rdkit#2774]
Hello. The normal rdkit MolTransforms setDihedralRad function doesn't work at all for ring torsions. How can I manipulate the 3D geometry of a molecule with rings such as cyclohexanes?

Thank you

**Comment by jasondbiggs** [comment]
You can try using a forcefield to optimize to a geometry with the desired
torsion angles.  Look at the function MMFFAddTorsionConstraint here,
https://www.rdkit.org/docs/source/rdkit.ForceField.rdForceField.html.

Jason Biggs

**Comment by ptosco** [comment]
Hi Tarun,

that's because when a torsion is in a ring it cannot rotate freely and 
independently from the rest of the molecule; furthermore, rotating a 
single torsion inside a ring would just distort the ring.

You can rotate dihedrals inside a ring, but you need to break the ring 
first, do the rotation(s) and then close the ring again.

This gist shows how to alter the conformation of a cyclohexane ring from 
chair to boat, which then converts to a skew-boat upon minimization:

http://htmlpreview.github.io/?https://gist.githubusercontent.com/ptosco/f8fb764dbab6427ff903e543ed7c79a0/raw/c02e7817c1fb1a826f7600fd3f9af71ec9ae2e8f/AdjustRingTorsions.html

Cheers,
p.

**Comment by tarungog** [comment]
@ptosco  Thank you! How did you calculate that it would need a 90 degree change to get to boat?

**Comment by tarungog** [comment]
@jasondbiggs This seems super promising also, thanks. My question is, what's stopping us from encumbering this force field from unmeetable constraints? Using MMFFAddTorsionConstraint, I could easily create torsion requirements that don't make any sense on rings.

**Comment by greglandrum** [comment]
@tarungog : there's nothing to stop you from creating a set of constraints that can't be realized.
