### ISSUE TITLE
Nitrogen in nitro group doesn't have charge after `RunReactants()`.

### ISSUE THREAD

**Issue by aigulkhkmv** [rdkit/rdkit#2811]
**Configuration:**

- RDKit Version: 2019.03.4
- Operating system: MacOS 10.14.3
- Python version (if relevant): Python 3.7.4
- Are you using conda? Yes, I do
- If you are using conda, which channel did you install the rdkit from? conda-forge 
- If you are not using conda: how did you install the RDKit?

**Description:**

We want to generate amino group oxidation reaction (`[H]N([H])C1=CC=CC=C1>>[O-][N+](=O)C1=CC=CC=C1`) using `RunReactants`. We have reaction reactant `[H]N([H])C1=CC=CC=C1` and reaction core `[N:2]([c:4])([H:1002])[H:2002]>>[O:1]=[N+:2]([O-:3])[c:4]`. Reaction core has atoms that were changed during reaction and their neighbours around one bond.

Nitrogen in the reaction core has charge. But nitrogen that was generated after `RunReactants` doesn’t have it. 

And so we get a broken molecule, because nitrogen atom has valence of 4, but doesn’t have charge. 

Here is the code to reproduce:

```python
>>> from rdkit import Chem
>>> from rdkit.Chem import AllChem
>>> reaction = AllChem.ReactionFromSmarts('[N:2]([c:4])([H:1002])[H:2002]>>[O:1]=[N+:2]([O-:3])[c:4]', useSmiles=True)
>>> mol_to_decompose = Chem.AddHs(Chem.MolFromSmiles("[H]N([H])C1=CC=CC=C1"))
>>> result = reaction.RunReactants([mol_to_decompose])
>>> Chem.MolToSmiles(result[0][0])
'[H]c1c([H])c([H])c(N(=O)[O-])c([H])c1[H]'
```

Here you can see that we expect to see the following molecule with explicit charge for nitrogen ( `[H]c1c([H])c([H])c([N+](=O)[O-])c([H])c1[H]` ), but we don’t.

We were able to catch this behaviour due to the following error of `AddHs`:

```python
>>> Chem.AddHs(result[0][0])
[18:16:09] Explicit valence for atom # 1 N, 4, is greater than permitted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Sanitization error: Explicit valence for atom # 1 N, 4, is greater than permitted
```
Thanks!

**Comment by ptosco** [comment]
That's a consequence of specifying `useSmiles=True`. If you do not use query molecules, the default behaviour is that implicit properties on reactant atoms (i.e., formal charge, isotope, number of implicit Hs) will be copied to the matching product atom. Therefore, as the nitrogen is neutral in the reactant, it is made neutral in the product.
If you set `useSmiles=False`, then the product is interpreted as SMARTS rather than SMILES, so atoms can have query properties, and hence formal charge query, isotope query, H count query that you have set on the product will not be overridden by the respective property on the matching reactant atom.
If you need to specify `useSmiles=True`, you may force that implicit properties are *not* copied by setting
```
reaction._setImplicitPropertiesFlag(False)
```
ahead of running
```
result = reaction.RunReactants([mol_to_decompose])
```
This will give you the protonated product that you expected, as the formal charge property that you set on the product atom will be retained rather than being overwritten by the matching reactant atom property:
```
from rdkit import Chem
from rdkit.Chem import AllChem

reaction = AllChem.ReactionFromSmarts('[N:2]([c:4])([H:1])[H:3]>>[O:1]=[N+:2]([O-:3])[c:4]', useSmiles=True)
mol_to_decompose = Chem.AddHs(Chem.MolFromSmiles("[H]N([H])C1=CC=CC=C1"))
reaction._setImplicitPropertiesFlag(False)
result = reaction.RunReactants([mol_to_decompose])
print(Chem.MolToSmiles(result[0][0]))
[H]c1c([H])c([H])c([N+](=O)[O-])c([H])c1[H]
```

**Comment by aigulkhkmv** [comment]
Thanks! It really helped!
