### ISSUE TITLE
Problem with Stereochemistry in RDKit

### ISSUE THREAD

**Issue by lucianlschan** [rdkit/rdkit#2874]
**Configuration:**
RDKit Version: 2019.03.3
Ubuntu 18.04
Python version: 3.6.9

**Description:**
I have problem in identifying the cis/trans isomers. See decalin example below.

**Code Example:**
from rdkit import Chem
from rdkit.Chem import rdmolops

cis = Chem.MolFromSmiles("C1CC[C@H]2CCCC[C@H]2C1")
trans = Chem.MolFromSmiles("C1CC[C@H]2CCCC[C@@H]2C1")

print(cis.GetAtomWithIdx(8).GetProp("_CIPCode"))
print(trans.GetAtomWithIdx(8).GetProp("_CIPCode"))

I expect to see "R" and "S" in the last two lines, but i see  KeyError: '_CIPCode'

Thank you for your help.

**Comment by mc-robinson** [comment]
I believe trans has an incorrect lowercase h. It should probably read:
`trans = Chem.MolFromSmiles("C1CC[C@H]2CCCC[C@@H]2C1")`

However, I think the real issue is likely the symmetry of your molecule, making it hard to define R and S.

If I run
`trans.GetAtomWithIdx(8).GetPropsAsDict()`
All I can see is 
```
{'__computedProps': <rdkit.rdBase._vectNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE at 0x1189dd870>,
 '_CIPRank': 2,
 '_ringStereochemCand': True,
 '_ringStereoAtoms': <rdkit.rdBase._vecti at 0x1189ddf30>}
```
