### ISSUE TITLE
EnumerateStereoisomers cannot handle STEREOANY bonds

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#2890]
When running this minimal example,
```
from rdkit import Chem
from rdkit.Chem.EnumerateStereoisomers import EnumerateStereoisomers

mol = Chem.MolFromSmiles('CC=CC')
mol.GetBondWithIdx(1).SetStereo(Chem.rdchem.BondStereo.STEREOANY)

list(EnumerateStereoisomers(mol))
```

Release 2019.09.2 of RDKit dies with:
```
****
Pre-condition Violation
Stereo atoms should be specified before specifying CIS/TRANS bond stereochemistry
Violation occurred on line 288 in file /tmp/rdkit/build/rdkit/Code/GraphMol/Bond.h
Failed Expression: what <= STEREOE || getStereoAtoms().size() == 2
****

Traceback (most recent call last):
  File "minimal.py", line 8, in <module>
    list(EnumerateStereoisomers(mol))
  File "/tmp/lib/python3.6/site-packages/rdkit/Chem/EnumerateStereoisomers.py", line 321, in EnumerateStereoisomers
    flippers[i].flip(flag)
  File "/tmp/lib/python3.6/site-packages/rdkit/Chem/EnumerateStereoisomers.py", line 49, in flip
    self.bond.SetStereo(Chem.BondStereo.STEREOTRANS)
RuntimeError: Pre-condition Violation
	Stereo atoms should be specified before specifying CIS/TRANS bond stereochemistry
	Violation occurred on line 288 in file Code/GraphMol/Bond.h
	Failed Expression: what <= STEREOE || getStereoAtoms().size() == 2
	RDKIT: 2019.09.2
	BOOST: 1_68

```
The problem seems to be that `EnumerateStereoisomers` tries to flip these stereo bonds, but, since Stereo Atoms haven't been set, it fails. This is especially relevant since the reactions code does now set STEREOANY on some product stereo bonds under certain circumstances.

I can think of two ways of considering STEREOANY bonds: they could either be ignored, being treated like if they were marked as STEREONONE, or, which seems the more reasonable to me, `EnumerateStereoisomers` could produce the two possible stereoisomers for the bond (CIS and TRANS).

**Comment by d-b-w** [comment]
It looks like EnumerateStereoisomers actually runs `Chem.FindPotentialStereoBonds()` before starting, so any STEREONONE that have meaningful stereochemistry are converted to STEREOANY with valid stereoatoms.

I expect that the issue is with the source of the STEREOANY, which needs to set the stereoatoms, apparently. I think that we observed this in output of a reaction.

**Comment by greglandrum** [comment]
Sorry I managed to miss this issue when it was originally raised. Just to have it captured in case questions come up later, here's my thought process on this one and the proposed fix:

I'm willing to be convinced otherwise, but it seems to me like it would be ok to have a double bond have STEREOANY set without having any stereo atoms. From a client code perspective it doesn't seem like I should have to specify which two atoms I don't know the positioning of.

This would then devolve the responsibility for setting the stereo atoms on STEREOANY bonds that don't have them set to EnumerateStereoisomers. #3015 does this indirectly by having `findPotentialStereoBonds()` ensure that STEREOANY bonds have their stereo atoms set.

If we *are* going to start requiring that STEREOANY bonds have stereo atoms set (and, again, I don't currently think this is a good idea), then we should enforce that in Bond::setStereo and update the comment there that specifically says that you can have STEREOANY without specifying StereoAtoms.
