### ISSUE TITLE
Aromaticity of imidazole ring depends on side ring/no ring?

### ISSUE THREAD

**Issue by wopozka** [rdkit/rdkit#2947]
**Configuration:**

- RDKit Version: '2019.09.3'
- Operating system: Darwin
- Python version (if relevant): 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit? conda install rdkit -c rdkit

**Description:**
Aromaticity of imidazole ring seems to depend on whether side chains are connected into ring or not. Example:
Your code sample here
1) Moiecule: CN1C=CN2CCCN=C12
from rdkit import Chem
Chem.MolToSmiles(Chem.MolFromSmiles('CN1C=CN2CCCN=C12'))
'CN1C=CN2CCCN=C12'
imidazole ring seems to be not aromatic
2) Molecule: CCN=C1N(C)C=CN1C
from rdkit import Chem
Chem.MolToSmiles(Chem.MolFromSmiles('CCN=C1N(C)C=CN1C'))
'CCN=c1n(C)ccn1C'
Here imidazole ring is considered to be aromatic.
It looks weird for me, that two, very similar structures are treated so different. I discovered this issue doing substructure searches (SMARTS based), and there as well  queries need to be defined differently to get each of compounds.
Thanks.
Piotr

**Comment by greglandrum** [comment]
Yeah, I agree that this is strange behavior.
It's happening because the N which is double bonded to the "imidazole" ring in the first molecule is also in a ring, so it doesn't count as an "exocyclic bond" which removes electrons. This is probably fixable without too much trouble.

**Comment by wopozka** [comment]
Hi Greg,
I wonder if you have any idea when this bug might be fixed?

**Comment by greglandrum** [comment]
This one got lost (and I actually thought I'd already fixed it, but I clearly haven't)
We should be able to fix it for the upcoming 2020.09 release.

**Comment by greglandrum** [comment]
Now I remember why this is trickier than it seems.
Here's your molecule:
![image](https://user-images.githubusercontent.com/540511/94329668-6e245c80-ffbd-11ea-87e2-b7869139a9bd.png)
It seems clear that C10 should contribute 0 pi electrons to the five ring because it has the equivalent of an exocyclic double bond (even though that bond isn't actually exocyclic).

However, what if I change the 6 ring so that it too is conjugated:
![image](https://user-images.githubusercontent.com/540511/94329742-facf1a80-ffbd-11ea-88fe-72ae7f056cb3.png)
If we follow the above logic C10 contributes 0 electrons to the 5 ring and 1 electron to the 6 ring, which doesn't make sense.

A solution would be to include a test for whether or not the "exocyclic" double bond is part of another conjugated ring system, but that's a considerably more involved fix

**Comment by wopozka** [comment]
Hi,
I agree that solution might be tricky. I was playing a bit today and found that the same applies for 6m ring, eg. below. Left ring is considered to be aromatic for left molecule, but not aromatic for right molecule.
![image](https://user-images.githubusercontent.com/46928633/94402788-c77ebe00-016c-11eb-9047-cb3ebd6f280a.png)

**Comment by greglandrum** [comment]
I'm going to mark this one as "won't fix" because I don't see a way forward that doesn't add a lot of code complexity while at the same time making the aromaticity model harder to explain and reason about. If that changes at some point in the future we can reopen this.
