### ISSUE TITLE
rdkit.Chem.QED.qed() cannot award more than 0.948

### ISSUE THREAD

**Issue by pcko1** [rdkit/rdkit#2968]
According to scores reported in [literature](https://arxiv.org/abs/1811.09621) (Table 3), `rdkit.Chem.QED.qed()` does not seem to award scores greater than 0.948.

I have also experienced the same results using a custom model that I've made, meaning that it was impossible to push the score of the generated molecules above 0.948xxx, after training on ChEMBL25. 

This can be due to:

- natural limitations that don't allow for higher scores even though QED is defined up to a value of 1.0
- lack of known molecules in the training set with a score higher than this (yet I would expect some models to extrapolate even marginally to a higher value, e.g. 0.949 if not more)
- the implementation of `rdkit.Chem.QED.qed`

Any ideas?

**Comment by bp-kelley** [comment]
This seems in line with the original publication's supplementary material
(below).  Since this is a multi-parameter objective, I don't really see
this as a major concern.  QED is a bit of a heuristic anyway.

https://static-content.springer.com/esm/art%3A10.1038%2Fnchem.1243/MediaObjects/41557_2012_BFnchem1243_MOESM238_ESM.pdf
