### ISSUE TITLE
SegmentationFault on EmbedMolecule

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#3019]
EmbedMolecule crashes with segmentation fault on large molecules.

```
# rdkit version 2019.09.3
from rdkit import Chem
from rdkit.Chem import AllChem
smiles = 'C'*900
mol = Chem.MolFromSmiles(smiles)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol)
```

**Comment by shayakhmetov** [comment]
It seems that it doesn't depend on AddHs, only on the number of atoms.
```
from rdkit import Chem
from rdkit.Chem import AllChem
smiles = 'C'*2000
mol = Chem.MolFromSmiles(smiles)
AllChem.EmbedMolecule(mol)
```

**Comment by shayakhmetov** [comment]
1627 seems to be the minimum number of carbon atoms (without hydrogens), when segmentation fault appears

**Comment by greglandrum** [comment]
Confirmed. Thanks for the bug report!

**Comment by greglandrum** [comment]
@shayakhmetov : please note that even after this bug is fixed, it's unlikely that the conformation generation for molecules this size is going to complete in a reasonable amount of time.
There may be ways to set things up so that you can work with macromolecules using `EmbedMolecule()`, but the default settings are definitely targeted at molecules that are more in the "drug-like" size category (low hundreds of atoms instead of thousands)

**Comment by shayakhmetov** [comment]
@greglandrum , thank you! Simple warning and returning error code would be enough for EmbedMolecule()

**Comment by greglandrum** [comment]
The crashing problem is definitely fixable, no worries there.
