### ISSUE TITLE
Understanding Atom.getNumRadicalElectrons()

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [rdkit/rdkit#3036]
Dear All,

I'm trying to use RDKit to do some feature engineering for some molecular machine learning model. I found Atom.getNumRadcialElectrons() is used as default atom feature in some packages but I'm not quite sure how it is defined here in RDKit. Is it equivalent to number of unpaired electrons for an atom? I've tried looking at documentations and some source code files and didn't find answer. 

I may have some other confusions about features defined in RDKit package. Are there any other suggested place I should post this kind of questions to?

Thanks

**Comment by GreenTail** [comment]
As you wrote here, based on the name Atom.getNumRadcialElectrons(), the function should return the number of unpaired electrons. However, I don't know for sure, since I also couldn't find any kind of documentation with explanations regarding this matter. The only advice I can give to you (as captain obvious): if you plan to use this feature in your machine learning models, check this function on a few examples to make sure that it behaves exactly as you expect it to work.

In the future, I think that the fastest way to get answers (regarding applying RDKit to ML in chemistry) is posting your questions to gitter: https://gitter.im/deepchem
