### ISSUE TITLE
how to smaller the size of  exe file generated by pyinstaller? 

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3100]
**Configuration:**

- RDKit Version: 2019.09
- Operating system: windows 10
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

pyinstaller package the python script to exe,  the size is 300M .
rdkit package was used in the script.

how to smaller the size of  exe file generated by pyinstaller? 

```
Your code sample here
```

**Comment by mwojcikowski** [comment]
The trick is to install numpy _et al_ without intel_mkl package. `conda-forge` by default builds numpy without it, so my best recommendation is to use conda-forge package and watch out for intel_mkl package when you install other dependencies or additional packages,

**Comment by autodataming** [comment]
> 
> 
> The trick is to install numpy _et al_ without intel_mkl package. `conda-forge` by default builds numpy without it, so my best recommendation is to use conda-forge package and watch out for intel_mkl package when you install other dependencies or additional packages,

Thank you! I try it.   

It will be much better if author could support minimal rdkit for the pip install.

**Comment by mwojcikowski** [comment]
It has nothing to do with RDKit. I used to create binaries lower than 40MB with fully functional RDKit and few other python libraries. This is the size you should be able to achieve.

**Comment by autodataming** [comment]
> 
> 
> It has nothing to do with RDKit. I used to create binaries lower than 40MB with fully functional RDKit and few other python libraries. This is the size you should be able to achieve.

The environment is anaconda or  just python environment?

In python environment,  the binaries lower than 50 MB.
But in anaconda environment, the binaries large than 100 MB.

**Comment by LeeKamlong** [comment]
I am trying to package the python script to exe by pyinstaller,  it raise a error that No module name 'rdkit'.
but the source code is able to run in the spyder environment. So I want to ask if it needs to be packaged in the rdkit environment ？？

**Comment by fredludlow** [comment]
(Occasional and not very knowledgeable rdkit user here, this may all be wrong...)

I'm hitting a similar thing (pyinstaller sizes seem to be much larger than I remembered in the past). I have a theory it's a combination of two things. 

If you do the recommended `conda create -n my-env -c conda-forge python=3.x rdkit` then it brings in a huge number of dependencies including tornado, tk, cairo, some qt stuff etc -  I think these all come in via the matplotlib-base dependency?

In the rdkit codebase (e.g. the bit in Chem.Draw setting up various drawing backends) these get imported from within a `try/except` block to figure out how to actually draw your molceules, but pyinstaller can't know beforehand which of those imports you're going to use, so they all get bundled in. To be fair, a lot are already excluded (IPython and PyQt5 aren't brought in by conda so pyinstaller just flags them as "missing" - unless you happen to have installed IPython in your environment because you like the terminal! ;) )

I think for now it's just a case of using a clean environment to run pyinstaller painfully going through each package and working out what you can exclude in your pyinstaller config, the html file that pyinstaller produces in the build directory when it analyses your program is helpful here.

Longer term, there's a lot of discussion on conda about how to specify "optional" dependencies https://github.com/conda/conda/issues/7502. It would be really nice if it were possible to do `conda install rdkit.minimal` and it wouldn't include things like tornado, but right now it looks like that's not really straightforward to set up (see that linked issue).
