### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'.

### ISSUE THREAD

**Issue by srinu844** [rdkit/rdkit#3111]
Hello 

I installed the new version of rdkit  2020.03.1 using confa forge. When do the import rdkit, I got an error message 

`ModuleNotFoundError: No module named 'rdkit'. `

I am using python 3.6 and installed it on MACOS catalina. I am going through the posts and found that I need to link the python and rdkit using RDBASE. I am not sure how do I do that . Can I get some help.

**Comment by greglandrum** [comment]
I'm closing this because there are multiple other issues with the same topic. Please read those, try out the solutions there, and if it doesn't work for you then please add a comment to one of the more recent open issues.

https://github.com/rdkit/rdkit/issues?q=is%3Aissue++%22no+module+named+rdkit%22
