### ISSUE TITLE
Python and postgres descriptor functions return different values

### ISSUE THREAD

**Issue by Fizzizist** [rdkit/rdkit#3276]
**Configuration:**

- RDKit Version: 2018.09.1
- Operating system: Ubuntu 18.04 LTS
- PostgreSQL Version: 10
- Python version (if relevant): 3.7
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? A custom rdkit-installer: https://github.com/cyclica/rdkit-installer

**Description:**

Using the same isomeric smiles string, many of the descriptor functions from `rdkit.Chem.rdMolDescriptors` give different output values to the equivalent stored prodecures in the rdkit postgres extension. For `CalcNumHBA` alone we found around 20,000 molecules that had differing HBA values from those returned by the `mol_hba` stored procedure in the rdkit postgres extension. The following code example shows one such instance:

On the python side:
```python
from rdkit.Chem import rdMolDescriptors
from rdkit.Chem.AllChem import MolFromSmiles
from django_rdkit.models import HBA

print(CalcNumHBA(MolFromSmiles('O=c1[nH]c2cc([N+](=O)[O-])c(Nc3c4ccccc4nc4ccccc34)c([N+](=O)[O-])c2[nH]1')))
```
output: `7`

postgres side:
```sql
SELECT mol_hba(mol_from_smiles('O=c1[nH]c2cc([N+](=O)[O-])c(Nc3c4ccccc4nc4ccccc34)c([N+](=O)[O-])c2[nH]1'::cstring));

mol_hba 
---------
      11
(1 row)
```

consulting with my scientist colleagues, the python one returns the correct HBA. Maybe the postgres extension is using an old version of these functions?

**Comment by greglandrum** [comment]
The postgresql `mol_hba()` function is equivalent to the Python `CalcNumLipinskiHBA()` function.
Similarly `mol_hbd()` is equivalent to `CalcNumLipinskiHBD()`
There are two different definitions because there's no absolutely correct for the number of hydrogen bond donors and acceptors. Though I agree that the value returned by `CalcNumHBA()` is generally more chemically reasonable, the `CalcNumLipinskiHBA()` form is what you're supposed to use if you want to calculate the famous Rule-of-5 values.
At the moment it's not possible to calculate the equivalent of `CalcNumHBA()` in the cartridge.

**Comment by Fizzizist** [comment]
Cool, thank you for the explanation. I didn't know that the Lipinski HBA was even a thing. I went back to https://www.rdkit.org/docs/Cartridge.html and it does mention that its using "Lipinski H-bond acceptors " so this makes a lot more sense now.
