### ISSUE TITLE
ComputeMolVolume units.

### ISSUE THREAD

**Issue by jcminerlanl** [rdkit/rdkit#3347]
I have been trying to calculate the total volume of hollow single-wall carbon nanotubes with RDKit.
I am using two that have lengths ~7Ang and ~20Ang.

When I embed the molecule and use:
AllChem.ComputeMolVolume(mol)
I get values of ~500 and ~1000, but I am not aware of what units they are and searching the manual has not revealed it to me.
I am further confused by what happens when I collect a numpy array of the coordinates and feed it to scipy.spatial.ConvexHull, which returns ~140 and ~365 respectively.

What are the units returned by ComputeMolVolume?

Thanks.

**Comment by bp-kelley** [comment]
The volume that is being computed is the Van der Waals volume.  This is the essentially the space that the atoms take up, if there is a "hollow" interior, that is not computed.

It has units angstroms^3

Here is a decent entry:

http://polymerdatabase.com/polymer%20physics/vdWVolume.html

The atomic shape, however, is computed on a grid.  It might be possible to do a painters style algorithm if you want to get the volume of the interior of the tube.

**Comment by p3rAsperaAdAstra** [comment]
I'm not sure if people are interested, but I was sceptical at first if the values obtained by RDKit aren't inflated. 
For example: The V_vdW of carbon is, according to `ComputeMolVolume` equal to 20.55 A^3, which I thought was too much.

So I compared the result of `ComputeMolVolume` to the result of calculating V_vdW = 4/3 * pi * r^3 based on the value from [this](doi:10.1021/j100785a001) publication. 

It checks out. Here's the code.
Note: For some reason I could not use `MolFromSmiles` using 'C' or '[C]' and had to use 'MolFromXYZFile' instead. So just make an xyz file like this:

```
1

C    0    0    0
```
And name it test.xyz to run this:

```
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromXYZFile('test.xyz') # MolFromSmiles with 'C' and '[C]' returns: "ValueError: Bad Conformer Id rdkit"

print('This is the vdW volume in Angström^3 based on ComputeMolVolume:')
print('Volume of %s: %.2f'%('Carbon',AllChem.ComputeMolVolume(mol,gridSpacing=.05))) # extra tight spacing just to be sure.

print('\n')
print(r'This is the vdW volume in Angström^3 based on the vdW radius of Carbon obtained from: doi:10.1021/j100785a001')

r_C = 170/100 # convert radius in picometer to angström.
V_exp = 4/3*np.pi*r_C**3 # calculate volume of simple sphere.

print('Volume of %s: %.2f'%('Carbon',V_exp)) # extra tight spacing just to be sure.
```

The result is 20.55 A^3 vs 20.58 A^3, so that's close enough. I also tried out how the results of `ComputeMolVolume` change with gridspacing. The default value of 0.2 seems to be a good point between calculation speed and accuracy. The calculation becomes very long for gridspacings of less than 0.05, but almost nothing is gained past 0.2.

Here's the visualisation of how V_vdw evolves with gridspacing for a carbon atom:
```
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
import matplotlib.pyplot as plt 

mol = Chem.MolFromXYZFile('test.xyz')

x = np.linspace(0.5,0.04,20)
y = [AllChem.ComputeMolVolume(mol,gridSpacing=gs) for gs in x]

fig,ax = plt.subplots(figsize=(6,4))

ax.scatter(x,y,c='r',label='Carbon Atom')
ax.invert_xaxis()

ax.set_ylabel(r'$V_\mathrm{vdw} \quad / \quad \mathrm{\AA^3}$')
ax.set_xlabel(r'$\mathrm{Grid\;\;Spacing} \quad / \quad \mathrm{\AA}$')

r_C = 170/100 # convert radius in picometer to angström.
V_exp = 4/3*np.pi*r_C**3 # calculate volume of simple sphere.

bbox_props = {'ec':'grey','ls':'--','fc':(0,0,0,0)}

ax.text(0.9,0.9,'$V_\mathrm{vdw,exp}$ = %.2f'%V_exp, transform=ax.transAxes, ha='right', va='top',bbox=bbox_props)
ax.axhline(y=V_exp,c='grey',ls='--')

plt.show()
```

I don't know why my gut told me the results were too large, but at least I am at peace now knowing that it's working as intended.
