### ISSUE TITLE
error in run pg_regression.sh

### ISSUE THREAD

**Issue by qq87258580** [rdkit/rdkit#3355]
I used the command conda install -c rdkit rdkit to install rdkit2020.03.3 in the anaconda3 compilation environment, and installed the dependency package according to the pgsql installation document, and set —LD_LIBRARY_PATH. There was no problem during use cmake installation, but when I When opening pgsql, I tried to add the rdkit extension and reported an error: ERROR: could not load library "/usr/pgsql-12/lib/rdkit.so": libboost_system.so.1.67.0: cannot open shared object file: No such file or directory. I checked the mailing list and tried many methods, but none of them were able to solve this problem. Could you please tell me how can I solve it?

diff -U3 /home/he/Downloads/rdkit/build/Code/PgSQL/rdkit/expected/rdkit-91.out /home/he/Downloads/rdkit/build/Code/PgSQL/rdkit/results/rdkit-91.out
--- /home/he/Downloads/rdkit/build/Code/PgSQL/rdkit/expected/rdkit-91.out	2020-08-24 04:53:06.224129890 -0400
+++ /home/he/Downloads/rdkit/build/Code/PgSQL/rdkit/results/rdkit-91.out	2020-08-24 06:14:40.943674762 -0400
@@ -4,182 +4,160 @@
 --
 SET client_min_messages = warning;
 \set ECHO none
+ERROR:  could not load library "/usr/pgsql-12/lib/rdkit.so": libboost_system.so.1.67.0: cannot open shared object file: No such file or directory
 RESET client_min_messages;
 SET extra_float_digits=0;
 SELECT is_valid_smiles('c1ccccc1');
- is_valid_smiles

**Comment by greglandrum** [comment]
@qq87258580 : the problem here is that the postgresql process cannot find the boost libraries that the RDKit depends on. Which version of boost did you use when you built the RDKit postgresql cartridge?


From the issue description it sounds like you have installed the RDKit using conda *and* built it yourself. This is a bit unusual. Generally if you're going to build the RDKit you don't install it using conda (or at least not in the same environment that you use to build the RDKit).

**Comment by qq87258580** [comment]
@greglandrum :
i use boost1.67 ,it's  use - `conda install boost boost-cpp py-boost `

I have installed rdkit2020.03.3 before, and I want to install the RDKIT extension for postgresql-server11-4-1 of /usr/pgsql-11/，

Here's a command i didi `cd rdkit mkdir build &&cd build
cmake -DBOOST_ROOT=“$CONDA_PREFIX” -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_CPP_TESTS=OFF -DRDK_BUILD_PGSQL=ON --PostgreSQL_CONFIG=/usr/pgsql-11/bin/pg_config -DRDK_BUILD_INCHI_SUPPORT=ON ..`

I tried many times and I don’t know why this error is reported every time. I would like to ask whether the conda environment build of rdkit-postgresql will affect the original installation of rdkit, thank you for your reply

**Comment by greglandrum** [comment]
The problem is that you're linking against boost libraries which are not in the LD_LIBRARY_PATH of the user which runs your postgresql server process (usually `postgres` on linux machines).
Two straightforward solutions are to change the LD_LIBRARY_PATH of the postgres user (generally not recommended) or to install the boost package from your operating system and build the RDKit using that (with `-DBOOST_ROOT=/usr`)

**Comment by qq87258580** [comment]
yeah，i do 3，but also error  `cmake not load library /usr/pgsql/lib/rdkit.so: /lib64/libstc++.so.6 version 'GLIBCXX 3.4.20 not found(required by /usr/pgsql/lib/rdkit.so)`,i update gxx-linux 7.3.0 in conda.
