### ISSUE TITLE
Multiple Canonical SMILES for a single molecule?

### ISSUE THREAD

**Issue by chaoyan1037** [rdkit/rdkit#3462]
**Configuration:**

- RDKit Version: 2020.03.1
- Operating system: Ubuntu 18
- Python version (if relevant): Python 3.7
- Are you using conda? 
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I have a molecule with mapping numbers, when I remove mapping numbers and convert the molecule into the canonical SMILES by Chem.MolToSmiles(Chem.MolFromSmiles(...)), it results in a non-canonical SMILES. I have to do Chem.MolToSmiles(Chem.MolFromSmiles(...)) again to get the canonical SMILES.

Or are there multiple canonical SMILES for each molecule?

```
from rdkit import Chem

react1 = '[CH3:1][C:2]1([CH3:3])[C@:4]2([C:5](=[O:6])[NH:7][C:8]3=[CH:9][CH:10]=[C:11]([Cl:12])[CH:13]=[C:14]3[C:15](=[O:16])[C:22]([F:23])([F:24])[F:25])[CH2:26][CH2:27][C@@:28]1([CH3:29])[C:30](=[O:31])[O:32]2'
mol1 = Chem.MolFromSmiles(react1)
[atom.SetAtomMapNum(0) for atom in mol1.GetAtoms()]
react1 = Chem.MolToSmiles(mol1)
print(react1)
# CC1(C)[C@@]2(C)CC[C@]1(C(=O)Nc1ccc(Cl)cc1C(=O)C(F)(F)F)OC2=O

react2 = Chem.MolToSmiles(Chem.MolFromSmiles(react1))
print(react2)
# CC1(C)[C@]2(C(=O)Nc3ccc(Cl)cc3C(=O)C(F)(F)F)CC[C@@]1(C)C(=O)O2

print(react1 == react2)
# False

```

**Comment by contrebandeco** [comment]
Hello,

My question is related, I think. [CDK allows for congiguring](http://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/smiles/SmiFlavor.html)  the "SMILES" rederer with a set of flags. I'm wondering if I can configure CDK and/or RDKit so that they canonicalize SMILES in the exact same way (or as close as possible ? Anyone knows ? Is there a similar way to configure RDKit SMILES output ?

**Comment by bp-kelley** [comment]
There is something odd happening here.  If I add a SanitizeMol after removing atom maps, I get the expected result.

```
react1 = '[CH3:1][C:2]1([CH3:3])[C@:4]2([C:5](=[O:6])[NH:7][C:8]3=[CH:9][CH:10]=[C:11]([Cl:12])[CH:13]=[C:14]3[C:15](=[O:16])[C:22]([F:23])([F:24])[F:25])[CH2:26][CH2:27][C@@:28]1([CH3:29])[C:30](=[O:31])[O:32]2'
mol1 = Chem.MolFromSmiles(react1)
[atom.SetAtomMapNum(0) for atom in mol1.GetAtoms()]
Chem.SanitizeMol(mol1)
...
```

**Comment by bp-kelley** [comment]
It could be that the atoms property caches need to be updated.

**Comment by contrebandeco** [comment]
As for my part of the problem, I will provide examples later.

**Comment by contrebandeco** [comment]
Here is the file that illustrates the difference from an alleged RDKit SMILES (alleged because the source told me that's what they were using, but I haven't been able to install RDKit in a Java environment yet, issue about that is upcoming) and the CDK SMILES I've made from that alleged RDKit source : [cdk-vs-rdk.txt](https://github.com/rdkit/rdkit/files/5503155/cdk-vs-rdk.txt).

**Comment by bp-kelley** [comment]
And Here you can see why making universal canonicalization algorithms is like shaving a yak

```
rdkit    : OCC1CC2CC1C1C2C(CC1)CO
cdk      : OCC1CC2CC1C3C2C(CC3)CO
```

Rdkit reuses closures, cdk doesn't appear too.  I think daylight did this, but can't verify it currently.

btw - here is oechem's 'C1CC2C3CC(C2C1CO)CC3CO'

**Comment by contrebandeco** [comment]
Yes, but is there a way to configure either to behave like the other. Surely this is not _inconceivable_. Also [here ](https://github.com/rdkit/rdkit/issues/3555)is the Java issue I'm having which would allow me to make sure that it's really rdkit (latest version) we are talking about.
