### ISSUE TITLE
SetPreferCoordGen generates strange coordinates

### ISSUE THREAD

**Issue by iwatobipen** [rdkit/rdkit#3491]
**Configuration:**

- RDKit Version: '2020.03.3' and '2020.09.1dev1'
- Operating system: Ubuntu 18.04
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? I installed rdkit from rdkit channel
- If you are not using conda: how did you install the RDKit?

**Description:**

I couldn't render molecule which has many rings when I set SetPreferCoordGen(True).
I tried to render Adamantane with the same option, it worked well.
Any advice, suggestions are greatly appreciated.

```
from rdkit import Chem
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import IPythonConsole
# following SMILES seems good without SetPreferCoordGen option.
smi = 'C12CC3CC(CC3C1)C2'
ring = Chem.MolFromSmiles(smi)
rdDepictor.SetPreferCoordGen(False)
ring

ring = Chem.MolFromSmiles(smi)
rdDepictor.SetPreferCoordGen(False)
ring

```

**Comment by d-b-w** [comment]
Thanks for reporting this. What do you mean "you couldn't render molecule?" - like, no image was produced or there was a traceback or something? Could you provide an example of a molecule for which it didn't work well?

**Comment by iwatobipen** [comment]
Thanks for your reply. I attached image below.
When I use the option, the example molecule has 2D layout.
Thanks.
 
![screenshot](https://user-images.githubusercontent.com/1076067/95924512-ab2c8380-0df2-11eb-9000-aad63103d174.png)

**Comment by greglandrum** [comment]
Hi @iwatobipen, I'm unable to reproduce this with either v2020.09.1:
![image](https://user-images.githubusercontent.com/540511/96669377-64dca480-135d-11eb-9e30-141377868fcb.png)

or with v2020.03.6:
![image](https://user-images.githubusercontent.com/540511/96670069-cfdaab00-135e-11eb-8346-faf965de4436.png)

**Comment by iwatobipen** [comment]
Hi Greg,
Thanks for your reply. Yes, Adamantan worked well but I still have trouble about following ring system ''C12CC3CC(CC3C1)C2''.
I uploaded the example code on my gist.
https://gist.github.com/iwatobipen/4984f397dfb4e027632cc7ee3bdc2122
Could you please check the code if you have time?
Thanks,

**Comment by greglandrum** [comment]
@iwatobipen : sorry I didn't look at the molecule closely enough.
Your script is fine: coordgen is generating bad coordinates for this molecule.
@d-b-w : I also confirmed that this isn't due to the fact that the RDKit is using the coarse minimizer parameter settings, when I do:
```
ps = rdCoordGen.CoordGenParams()
ps.minimizerPrecision = ps.sketcherBestPrecision
rdCoordGen.AddCoords(m,ps)
```
the coordinates are the same.

**Comment by cyesteban** [comment]
Hi,

I have the same problem when drawing molecules with fused rings.
For example: 

This code with `rdDepictor.SetPreferCoordGen(False)` gives the correct structure
   ```
    
    from rdkit.Chem import rdDepictor
    from rdkit.Chem import rdCoordGen
    
def get_image(smiles):
    mol = Chem.MolFromSmiles(smiles, sanitize=True)
    rdDepictor.SetPreferCoordGen(False)
    rdCoordGen.AddCoords(mol)
    rdDepictor.Compute2DCoords(mol)
    return mol

molec = 'C1=CC=C(N(C2=CC=CC=C2)C2=CC3=C4B(C5=CC=CC=C5N3C3=CC=CC=C3)C3=C(C=C5C(=C3)B3C6=C(C=CC=C6)N(C6=CC=CC=C6)C6=CC(N(C7=CC=CC=C7)C7=CC=CC=C7)=CC(=C36)N5C3=CC=CC=C3)N(C3=CC=CC=C3)C4=C2)C=C1'
m = get_image(molec)
m
```
![image](https://user-images.githubusercontent.com/80709306/111196039-2c17c300-85bd-11eb-835f-feca01804e41.png)


while `rdDepictor.SetPreferCoordGen(True) `gives this:
![image](https://user-images.githubusercontent.com/80709306/111196171-49e52800-85bd-11eb-961d-83a8683020ac.png)

However, I cannot use always the `rdDepictor.SetPreferCoordGen(False) `option because other structures (with flexible bonds) are drawn wrong, like this one:
![image](https://user-images.githubusercontent.com/80709306/111196359-79943000-85bd-11eb-9ad1-0779f266b7ca.png)

which comes right when we have `rdDepictor.SetPreferCoordGen(True) `:

![image](https://user-images.githubusercontent.com/80709306/111196594-c11abc00-85bd-11eb-9315-ef3c4523f182.png)


Is there any global solution for both kinds of structures?

Thank you very much.

**Comment by d-b-w** [comment]
ugh, yeah, these are pretty bad. Thanks for reporting these. 

I've cloned this issue over to the schrodinger/coordgenlibs as https://github.com/schrodinger/coordgenlibs/issues/83
