### ISSUE TITLE
a question about atom coordinates after embedding

### ISSUE THREAD

**Issue by amateurcat** [rdkit/rdkit#3492]
**Configuration:**

- RDKit Version: 2020.03.6
- Operating system: linux
- Python version (if relevant): 3.8.3
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from?   defaults/conda-forge
- If you are not using conda: how did you install the RDKit? 

**Description:**

Please see the two block of codes below, I believe they should have exactly same output, however only the first part can output coordinates of molecule, the second part will report something like:
****
Pre-condition Violation

Violation occurred on line 46 in file /home/conda/feedstock_root/build_artifacts/rdkit_1600678001365/work/Code/GraphMol/Conformer.cpp
Failed Expression: dp_mol->getNumAtoms() == d_positions.size()
****

Please note that I did not run them continuously, instead I comment the second part when I run the first part and vice versa

```
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
import copy


print(rdkit.__version__)

s = 'CC'

m = Chem.MolFromSmiles(s)
m = Chem.AddHs(m)
AllChem.EmbedMolecule(m)
print(m.GetConformers()[0].GetPositions())

#######################################################################
def read_smile(s):
    m = Chem.MolFromSmiles(s)
    m = Chem.AddHs(m)
    AllChem.EmbedMolecule(m)
    return m

print(read_smile(s).GetConformers()[0].GetPositions())
```

**Comment by ptosco** [comment]
@amateurcat that happens because the C++ molecule object that holds the conformers goes out of scope before you access the conformers that belong to that molecule, which are returned as internal references rather than as copies for efficiency.
As a workaround, changing
```
print(read_smile(s).GetConformers()[0].GetPositions())
```
into
```
m = read_smile(s) 
print(m.GetConformers()[0].GetPositions())
```
will avoid to trigger the problem.
I'll look into fixing this.

**Comment by greglandrum** [comment]
@amateurcat : to add one additional piece of information to @ptosco's answer:
if you use `GetConformer()` instead of `GetConformers()` everything works fine.

Technical answer for why this works: with `GetConfomer()` we're able to tell Python that the lifetime of the molecule is tied to that of the conformer; we haven't figured out how to do that for `GetConformers()`

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
