### ISSUE TITLE
Oxidation states for phosphorus and its period

### ISSUE THREAD

**Issue by cbouy** [rdkit/rdkit#3528]
I think there's a mistake (or at least an unusual choice) in the list of oxidation states/valences for phosphorus and the other elements of its period:
```python
>>> list(Chem.GetPeriodicTable().GetValenceList(15))
[3, 5, 7]
```

https://github.com/greglandrum/rdkit/blob/5059765f93a22a5fb8d6dcee5c1e117bd0feef56/Code/GraphMol/atomic_data.cpp#L54

**Description:**

Phosphorus can only share 3 or 5 electrons from it's valence shell to form covalent bonds, and a valence of 7 was introduced in issue #510 to tackle hexafluorophosphate, and then #1668 for the other elements of the same period.
I can understand the need for this but should it really be part of the RDKit **Periodic Table** ?
Otherwise additional valences should also be added to atoms like boron (see tetrafluoroborate), beryllium (tetrafluoroberyllate), and probably others.

**Comment by ptosco** [comment]
I think you raise a very good point. I ran into the BF<sub>4</sub><sup>-</sup> and BeF<sub>4</sub><sup>2-</sup> cases myself, and while I was initially tempted to add additional valences into `atomic_data.cpp`, I then refrained from doing so as I felt it was not the proper way to address compounds featuring dative bonds. Let's see what others think.

**Comment by bp-kelley** [comment]
I mostly feel the same, however what we have under the hood is a chemistry
model, and if it's too hard to model on the dative bond side, perhaps
valence changes are appropriate if they were flagged as "coordination" or
"dative" valences.

I'll pass the buck and  leave this up to Greg.

**Comment by greglandrum** [comment]
BF4- and BeF4-2 are currently accepted without problems... they don't need any additional valence states:
```
In [17]: Chem.MolToSmiles(Chem.MolFromSmiles('F[B-](F)(F)F'))
Out[17]: 'F[B-](F)(F)F'

In [18]: Chem.MolToSmiles(Chem.MolFromSmiles('F[Be-2](F)(F)F'))
Out[18]: 'F[Be-2](F)(F)F'
```
This is because both Be-2 and B- are isoelectronic to C, so they are happy having four neighbors.

In general adding new states is a complicated thing because there are a couple of "competing interests".

On one side there's something of a core principle in the RDKit to not accept chemically unreasonable molecules by default. You can always read in molecules with odd chemistry (five-coordinate carbon, whatever) if you choose to, but the default behavior is to generate errors for things that aren't chemically reasonable. I believe that this is really important for data quality.

On the other side there's the desire to have the RDKit accept, by default, common stable structures which have unusual valences. At the risk of using another word which means different things to different people, by this I basically mean hypervalent structures. This would include things like PF6- and, as of v2020.09.1, ClF3, BrF3, IF3. The new allowed valence states for Cl are a good illustration of why this is problematic: we added the new valence state in order to be able to have the RDKit handle ClF3 by default. That's certainly not a pleasant compound, but it's a real one. The problem is that we now also support things like CCl(C)C by default, and if that appears in a dataset it's mostly likely a mistake (and in the cases where it's not a mistake the user hopefully knows that they are working with strange compounds).

There's more I should write here, but I will probably send that to the mailing list in the next couple of days.

**Comment by ptosco** [comment]
Unless I completely misunderstand how valences and dative bonds are handled in the RDKit, something does not seem right to me.
I think it should be possible to place the formal charge on F in BF<sub>4</sub><sup>-</sup> and BeF<sub>4</sub><sup>2-</sup> when using a dative bond:
```
m = Chem.MolFromSmiles("[F-]->B(F)(F)F")
RDKit ERROR: [09:25:32] Explicit valence for atom # 1 B, 4, is greater than permitted

m = Chem.MolFromSmiles("[F-]->[Be](F)(F)<-[F-]")
RDKit ERROR: [09:25:33] Explicit valence for atom # 1 Be, 4, is greater than permitted
```

When I do the same with PF<sub>6</sub><sup>-</sup> the fact that P is allowed to be heptavalent seems to have undesired side effects as a hydrogen is added:
```
m1 = Chem.MolFromSmiles("F[P-](F)(F)(F)(F)F")
m2 = Chem.MolFromSmiles("[F-]->P(F)(F)(F)(F)F")
Chem.MolToSmiles(m1) == Chem.MolToSmiles(m2)
False
Chem.MolToSmiles(m1)
'F[P-](F)(F)(F)(F)F'
Chem.MolToSmiles(m2)
'F[PH](F)(F)(F)(F)<-[F-]'
```

N-oxides represented as dative bonds also don't seem quite right, as an implicit H is added to the O while I believe it shouldn't:
```
m1 = Chem.MolFromSmiles("C[N+](C)(C)[O-]")
m2 = Chem.MolFromSmiles("CN(C)(C)->O")
for a in m1.GetAtoms():
    print(a.GetIdx(), a.GetSymbol(), a.GetNumImplicitHs(), a.GetNumExplicitHs())
0 C 3 0
1 N 0 0
2 C 3 0
3 C 3 0
4 O 0 0
for a in m2.GetAtoms():
    print(a.GetIdx(), a.GetSymbol(), a.GetNumImplicitHs(), a.GetNumExplicitHs())
0 C 3 0
1 N 0 0
2 C 3 0
3 C 3 0
4 O 1 0
```
Don't slap me too hard if I am utterly wrong: I have a delicate skin ;-)

**Comment by greglandrum** [comment]
The RDKit has a chemistry model that doesn't use dative bonds for those things. If you want to use dative bonds you certainly can do it, but you need to not use the RDKit's chemistry model (i.e. don't ask the RDKit to calculate things like number of Hs, radicals, etc)

**Comment by greglandrum** [comment]
This whole thing is going to become 1000 times more "exciting" as we start to expand support for organometallics

**Comment by cbouy** [comment]
Yes I completely agree that it's not easy to balance between "hypervalence" and the fact that in most cases those hypervalent molecules only exist as halides and not as hydrides and you might allow unreasonable structures as you described.
My point was should phosphorus' valence 7 show up in RDKit's periodic table as an actual valence rather than a coordination/dative valence that is used internally by RDKit to model these edge cases ? Or in other terms, should this be exposed to users ?

**Comment by ptosco** [comment]
Quoting what Greg said about Be and B:
"This is because both Be<sup>2-</sup> and B<sup>-</sup> are isoelectronic to C, so they are happy having four neighbors"

PF<sub>6</sub><sup>-</sup> is isoelectronic with SF<sub>6</sub>, so I'd propose to handle it by a similar mechanism rather than by adding a 7 valence in the periodic table.

By the way, SiF<sub>6</sub><sup>2-</sup> (also isoelectronic with SF<sub>6</sub>) is not currently handled:
```
Chem.MolFromSmiles("[Si-2](F)(F)(F)(F)(F)F")
RDKit ERROR: [12:13:10] Explicit valence for atom # 0 Si, 8, is greater than permitted
```
and I would not add an 8 valence to handle it.
