### ISSUE TITLE
rdMolDraw2D Depictions - setFontSize has no effect - 2020.09.1 release

### ISSUE THREAD

**Issue by AlDossetter** [rdkit/rdkit#3581]
**Configuration:**
Configuration:
import rdkit
rdkit.__version__
-->

RDKit Version: 2020.09.1
Operating system: MacOSX Darwin 10.15.7  and Ubuntu 20.04
Python version (if relevant): 3.7
Are you using conda? Yes
If you are using conda, which channel did you install the rdkit from? rdkit

What:
All depictions to .png file type have the same font size when changing SetFontSize()

Expected:
To be able to set the pixel size of the font as outlined in release docs

The fontSize()/setFontSize() (FontSize()/SetFontSize()) methods in MolDraw2D
now work in units of pixels (more or less) instead of the molecule units.

Code:

```python
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D

if hasattr(Draw, 'MolDraw2DCairo'):
    print('can do Cairo')
if hasattr(Draw, 'MolDraw2DSVG'):
    print('can do SVG')


smarts = 'cncO'
mol = Chem.MolFromSmiles('c1cccnc1O')
mc = rdMolDraw2D.PrepareMolForDrawing(mol)
d = Draw.MolDraw2DCairo(300, 300)

# Is it possible to change min and maxFontSize as draw properties and this changes the range?
#_options = d.drawOptions()
#_options.minFontSize = 40
#_options.maxFontSize = 200

# Default max size - try 6 to 40 with no change in the depiction
d.SetFontSize(6)

d.DrawMolecule(mc, highlightAtoms = mol.GetSubstructMatch(Chem.MolFromSmarts(smarts)))
d.FinishDrawing()
txt = d.GetDrawingText()
with open('demo1_6pixel_font_size.png', 'wb') as pngf:
    pngf.write(txt)

```

Exploring the docs further and experiments the default max and min font sizes are 6 and 40 'pixels'.

I understand that the font size scale automatically with bond length?

Debate:
Is this a bug or intended behaviour change?

Should setFontSize have the expected effect?

**Comment by DavidACosgrove** [comment]
The drawMolecule function ignores setFontSize and scales the characters in the picture to be in proportion to the drawing.  The drawOptions minFontSize and maxFontSize stop them getting too big and too small as the picture is scaled, but that is currently the only way of changing the relative size of the letters wrt bond lengths etc.  it would be useful to have some use cases where that isn't sufficient, so that we can see what else might be needed.  Two things that occur and wouldn't be too much work would be an option not to scale the characters along with the rest of the picture, though I wouldn't be surprised if that didn't have knock-on effects that would make it a pain to implement; and an option to change the relative size of the characters. There is already a draw option annotationFontScale that defaults to 0.5, so that atom and bond annotations are half the size of the atom symbols.  Something similar could be introduced.  The font size would still scale with the drawing, but would be bigger or smaller compared to the bonds and such.  This would be relatively unobtrusive and in particular wouldn't change the API.

Possibly the documentation for setFontSize should explain some of this.

Input from other people, especially @greglandrum would be appreciated.
