### ISSUE TITLE
Rendering with PandasTools does not work for DataFrame slices

### ISSUE THREAD

**Issue by RMeli** [rdkit/rdkit#3661]
**Describe the bug**
`PandasTools.ChangeMoleculeRendering(df, renderer="SVG")` works as expected for a full `pd.DataFrame`, but it does not seem to work as expected when the data frame is sliced.

**To Reproduce**

```
PandasTools.ChangeMoleculeRendering(df, renderer="SVG")
HTML(df.iloc[:2].to_html())
```

**Expected behavior**

The code above should display the data frame with rendered molecules but it does not, while displaying the whole data frame (`HTML(df.to_html())`) works as expected.

**Configuration (please complete the following information):**
 - RDKit version: `2020.09.3`
 - OS: `macOS 10.15.7`
 - Python version (if relevant): `Python 3.8.6`
 - Are you using conda? `Yes`
 - If you are using conda, which channel did you install the rdkit from? `rdkit`

**Additional context**

I attached a simple Jupyter Notebook showcasing the problem, together with the full definition of the `conda` environment used: [rdkit-bug.zip](https://github.com/rdkit/rdkit/files/5714911/rdkit-bug.zip)

This problems seems to be related to #3563 but for me only the slice is problematic while the full data frame renders correctly as expected. The following workaround from #3563 seems to work here as well:
```
PandasTools.ChangeMoleculeRendering(df, renderer="SVG")
PandasTools.RenderImagesInAllDataFrames(images=True)
HTML(df.iloc[:2].to_html())
```

**Comment by sirbiscuit** [comment]
Hello @RMeli,

the instruction PandasTools.ChangeMoleculeRendering(df) only affects the DataFrame df that is passed as the first argument. But df.iloc[:2] creates a new instance of a DataFrame! In order to render it, you have to call ChangeMoleculeRendering on the new instance as well. The following code demonstrates this (and doesn't even need IPython.display.HTML):

```python
from rdkit.Chem import PandasTools, MolFromSmiles
import pandas as pd

df = pd.DataFrame(dict(mol=[MolFromSmiles('CCO')]))
df_subset = df.iloc[:2]

PandasTools.ChangeMoleculeRendering(df_subset)
df_subset
```
![image](https://user-images.githubusercontent.com/8418161/103536183-5436c780-4e92-11eb-92c7-3ba3dd2970a8.png)

**Comment by RMeli** [comment]
@sirbiscuit How silly, thanks for pointing this out!
