### ISSUE TITLE
Map atom numbers in compounds and the reactions SMARTS string

### ISSUE THREAD

**Issue by XFaIT** [rdkit/rdkit#3666]
I'd like to see what position each atom of the reagents take in the product, i.e. map atom numbers in reagents and the product to ones in the reaction SMARTs string 
for example rxn = RunReactants ('[# 6: 1][# 6: 2][# 6: 3][# 6: 4].[# 6: 5]#[# 6: 6] >>[# 6: 1]1[# 6: 2][# 6: 3][# 6: 4][# 6: 5][# 6: 6]1'). Is it possible to do this?

**Comment by greglandrum** [comment]
@XFaIT I'm moving this to the discussions because I think it's a question and not an actual feature request.

It may be possible to do this, but can you please be a bit more explicit about what you would like to see? Please give an actual example reaction along with example molecules you would like to apply it to and what you want to see in the output.

**Comment by greglandrum** [comment]
@XFaIT I'm marking this as a discussion because I think it's a question and not an actual feature request. Normally I'd just move it to discussions, but for some reason github isn't letting me do this today.

It may be possible to do this, but can you please be a bit more explicit about what you would like to see? Please give an actual example reaction along with example molecules you would like to apply it to and what you want to see in the output.

**Comment by XFaIT** [comment]
I am using the reaction generator AllChem.ReactionFromSmarts ()

AllChem.ReactionFromSmarts () — это не генератор, просто I create reaction from smarts string and then run it with

and rxn.RunReactants ((reag, acet)). 

For example, for following Diels-Alder reaction '[C: 1] = [C: 2] [C: 3] = [C: 4]. [# 6: 5] # [# 6: 6] >> [C: 1] 1 [C: 2] = [C: 3] [C: 4] [C: 5] = [C: 6] 1 ' I want to match atoms participating in reaction with corresponding numbers from SMARTs string.
![изображение](https://user-images.githubusercontent.com/68810304/103824876-d1765e00-5085-11eb-8f5a-7ba2ab714454.png)

**Comment by Vicky-0925** [comment]
Hi,have you solve this problem?I have same question now.And my boss told me could use something like this,but I still don't know the meaning of each outcomes.

```
 rxn = AllChem.ReactionFromSmarts('[OH:1][C:2][C:3][C:4][C:5][C:6](=[O:7])>>[O:1]1[C:2][C:3][C:4][C:5][C:6]1[OH:7]')
reactants = [Chem.MolFromSmiles(x) for x in ('[H]C(=O)[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO', )]
for i,m in enumerate(reactants):
    for atom in m.GetAtoms():
        atom.SetIntProp('reactant_idx',i)
ps = rxn.RunReactants(reactants)
p0 = ps[0][0]
[atom.GetPropsAsDict(True, False) for atom in p0.GetAtoms()]
```
