### ISSUE TITLE
Have better insight when use FindAtomEnvironmentOfRadiusN and PathToSubmol

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3674]
RDKit: 2020.09.1 - Anaconda Installation
Python: 3.7.9 - Windows 10

[1]: At current time, when I have this fragment (hydrogen is included: CH3 - NH): C[NH] and when I use FindAtomEnvironmentOfRadiusN at atom [N] with r = 3. It doesn't not give me any path. I suggest that this function can be fixed as circular searching. 
Ex: take atom nitrogen for example (idx = 1), at r = 1: it will detect bond N-H and C-N, at r = 2, it will detect 3 bonds C-H, at r = 3, as there are no new bond added. It will only give all the bond detected instead of giving me an empty list. 

[2] In case of no bond is given (empty list) in the function FindAtomEnvironmentOfRadiusN, for example: [H] (r_max = 0), the function PathToSubmol will return a new copied version of the input mol which is the same as input mol (copied == input) if the input parameter of 'path' is empty.

**Comment by greglandrum** [comment]
Hi @IchiruTake : thanks for the suggestions.

1. The current behavior of that function is intentional. If you ask for a radius 3 environment and none exist you get back no results. If you want to find the largest environment up to a particular size, you can do something like this:
```
>>> m = Chem.MolFromSmiles('CCOCC')
>>> def FindLargestAtomEnvironmentUpToSize(mol,radius,atomIdx):
...     for i in range(radius,0,-1):
...         res = Chem.FindAtomEnvironmentOfRadiusN(m,i,atomIdx)
...         if len(res):
...             return res
...     return []
... 
>>> list(FindLargestAtomEnvironmentUpToSize(m,2,2))
[1, 2, 0, 3]
>>> list(FindLargestAtomEnvironmentUpToSize(m,3,2))
[1, 2, 0, 3]
>>> list(FindLargestAtomEnvironmentUpToSize(m,1,2))
[1, 2]
```

2. Again, `PathToSubmol()` returns an empty molecule if you give it an empty list. Returning the full molecule when you ask for none of it would be quite confusing.  If you'd like to have that behavior in your own code, it would be straightforward to do something like:
```
if len(path):
  submol = Chem.PathToSubmol(mol,path)
else:
  submol = Chem.Mol(mol)
```

**Comment by i-tub** [comment]
I was about to file a ticket but I found this one. I don't quite get why this is the intended behavior, but since it is, I think it could be made clearer in the documentation, because IMHO it is counterintuitive. The docs say "Finds the bonds within a certain radius of an atom in a molecule". I take "within" as meaning "less than or equal to", so I would expect based on that description that if I ask for say, bonds within radius=1000000, I would get all bonds.

It's not like the function is only returning bonds at _exactly_ the requested distance; it does returns closer bonds as well, even bonds along paths that won't reach the radius, which makes the behavior all the more surprising.

**Comment by IchiruTake** [comment]
@i-tub I agree, the current documentation does not match with the behaviour. I have contributed this behaviour on the new PR, in which I correct the function and wait for review.
@greglandrum

**Comment by IchiruTake** [comment]
> I was about to file a ticket but I found this one. I don't quite get why this is the intended behavior, but since it is, I think it could be made clearer in the documentation, because IMHO it is counterintuitive. The docs say "Finds the bonds within a certain radius of an atom in a molecule". I take "within" as meaning "less than or equal to", so I would expect based on that description that if I ask for say, bonds within radius=1000000, I would get all bonds.
> 
> It's not like the function is only returning bonds at _exactly_ the requested distance; it does returns closer bonds as well, even bonds along paths that won't reach the radius, which makes the behavior all the more surprising.

In fact, the documentation in C++ and Python is not fully compatible. 
In C++, the doc is `find bond subgraphs of a particular radius around an atom`
In Python, the doc is `Finds the bonds within a certain radius of an atom in a molecule`.

Although both used the same function, the meaning of this doc is incorrect.

C++: https://www.rdkit.org/docs/cppapi/namespaceRDKit.html#aec3ca1c15fbd45510403121f86a907e6 
Python: https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html?highlight=findatomenvironmentofradiusn#rdkit.Chem.rdmolops.FindAtomEnvironmentOfRadiusN
