### ISSUE TITLE
rdMolDescriptors.CalcNumAtomStereoCenters breaks during multiprocessing.

### ISSUE THREAD

**Issue by aced125** [rdkit/rdkit#3678]
```python
import multiprocessing as mp
import rdkit.Chem.rdMolDescriptors as rdmd

def f(mol):
    return rdmd.CalcNumAtomStereoCenters(mol)

mols = [Chem.MolFromSmiles("c1ccncc1C(=O)[C@@H](Br)C")] * 10

out = list(map(f, mols))
print('Succeeded single process')


with mp.Pool(2) as p:
    out = p.map(f, mols)

print('failed')
```

`rdMolDescriptors.CalcNumAtomStereoCenters` fails when using python multiprocessing. But most other `rdMolDescriptors` functions work.

**Comment by aced125** [comment]
Fails with `pathos.multiprocessing.ProcessingPool` as well.

**Comment by ptosco** [comment]
@aced125 The `multiprocessing` module needs to pickle (i.e., serialize) data structures to pass them to worker processes. By default, the RDKit `Mol` pickler does not pickle properties. You can change this behavior using `Chem.SetDefaultPickleProperties()`:
```
Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)
```
file:///M:/src/rdkit/docs/python/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.SetDefaultPickleProperties

If you re-run your code after applying the above setting, you will get the expected behavior.
