### ISSUE TITLE
Morgan fingerprint to Smiles and Morgan Fingerprint validation check.

### ISSUE THREAD

**Issue by emdayr123** [rdkit/rdkit#3709]
I would really love if RDKIT had a feature where you could check if a Morgan Fingerprint is valid/invalid. You can do things for Smiles string but no for fingerprints. I also would like to convert from Morgan Fingerprint to Smiles.

**Comment by greglandrum** [comment]
@emdayr123 : Because Morgan fingerprints are constructed by setting bits if a substructure is present and there aren't any rules which say that if "bit A is present then bit B cannot be", there's not really any such thing as an "invalid" Morgan fingerprint.

For the second part: the translation from structure -> fingerprint is lossy and there is no guaranteed correct way to go backwards. This presentation describes a machine learning approach to attempt to invert Morgan FPs:
https://github.com/rdkit/UGM_2020/blob/master/Presentations/TuanLe_Neuraldecipher_UGM2020.pdf
They show remarkable success, but that approach still fails a lot of the time.

**Comment by greglandrum** [comment]
If you'd like to discuss this further, please use the Discussions tab.
