### ISSUE TITLE
initialization of the PeriodicTable object should be made thread-safe

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#381]

**Comment by greglandrum** [comment]
Closing this because I think the current initialization is threadsafe.

**Comment by JLVarjo** [comment]
I would suggest re-opening this since it doesn't seem to be thread-safe. I have code in which mol objects are created in separate threads and simultaneous Atom constructions lead to multiple PeriodicTable initializations. A simple workaround was to construct PeriodicTable once before doing anything else, though.

**Comment by greglandrum** [comment]
I remain unable to reproduce a problem here, but making the initialization threadsafe is easy enough.
