### ISSUE TITLE
GetConformers(Mol) returns non-tuple object

### ISSUE THREAD

**Issue by kazuyaujihara** [rdkit/rdkit#3810]
**Describe the bug**
`GetConformers(Mol)` returns `rdkit.Chem.rdchem._ROConformerSeq` not tuple of  `Conformer` after merging https://github.com/rdkit/rdkit/pull/3527. The RDKit documentation shows the method returns "all the conformers as a tuple". 

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromSmiles("C1CCCCC1CC")
AllChem.EmbedMultipleConfs(mol)
print(type(mol.GetConformers()))

for i, conf in enumerate(mol.GetConformers()):
    if i == 2:
        mol.RemoveConformer(i)
```
The above code prints "<class 'rdkit.Chem.rdchem._ROConformerSeq'>" and raises RuntimeError.

**Expected behavior**
Prints "<class 'tuple'>" and ends without error.

**Configuration:**
 - RDKit version: 2020.09.4
 - OS: Ubuntu 18_04 (built by myself) / Windows (form conda-forge)

Some existing code assumes the method returns tuple, ie, removing/adding conformer during iteration of conformers, which causes not only RuntimeError but MemoryError or Segmentation fault by chance. (I could not find a solid test case yet.) 
I think we should introduce a new method to iterate conformers.

**Comment by greglandrum** [comment]
You are correct that the documentation is now wrong. Thanks for pointing that out.

The runtime error is because the result of `GetConformers()` is now "live" and you are modifying the molecule's conformers as you loop over that sequence.

If you want a tuple you can just convert the results to a tuple:
```
for i, conf in enumerate(mol.GetConformers()):
    if i == 2:
        mol.RemoveConformer(conf.GetId())
```
I also changed this to call `conf.GetId()`. It's not safe to assume that the conformers are numbered 0-numConformers.

A couple of things to note:
1. #3527 was merged to deal with a memory management problem - it was possible to delete a molecule even though there were still conformers around which reference the molecule. Converting the result of `GetConformers()` to a tuple (or list, or whatever) exposes you to the same risk.
2. A general point. I know this is just sample code, but unless you have a specific reason not to you should always add Hs to a molecule before you generate conformers for it.

**Comment by kazuyaujihara** [comment]
Thanks Greg for your guidance.  I missed that the docstring has already changed.
