### ISSUE TITLE
'Image' object has no attribute 'save' for PNG images in Jupyter Notebooks

### ISSUE THREAD

**Issue by RMeli** [rdkit/rdkit#3940]
**Describe the bug**
Trying to save an image from `PandasTools.FrameToGridImage` in a Jupyter Notebook results in the following exception:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-001b88a9ac40> in <module>
----> 1 img.save("plots/molecules.png")

AttributeError: 'Image' object has no attribute 'save'
```

**To Reproduce**
Steps to reproduce the behavior (in a Jupyter notebook):
```
img = PandasTools.FrameToGridImage(df, column="mol", legendsCol="compound", molsPerRow=6)
img.save("molecules.png")
```

The odd thing to me is that this works as expected if the option `returnPNG=False` is passed _explicitlty_, despite the argument being the [default for `Draw.MolsToGridImage()`](http://rdkit.org/docs/source/rdkit.Chem.Draw.html?highlight=molstogridimage#rdkit.Chem.Draw.MolsToGridImage). Am I missing something?

**Expected behavior**
I expect the above code to work without explicitly passing `returnPNG=False`, which is already the default value.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3
 - OS: macOS 10.15.7
 - Python version (if relevant): 3.8.6
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? `conda-forge`

**Additional context**

This behavior was recently reported/discussed on [StackOverflow](https://stackoverflow.com/questions/65470233/attributeerror-image-object-has-no-attribute-save); I encounter the same problem and was not able to find a discussion here (aside from a brief mention in https://github.com/rdkit/rdkit/issues/2974#issuecomment-784222809).

**Comment by greglandrum** [comment]
There is some magic that happens behind the scenes when the RDKit runs in Jupyter to make things nicer in the notebook: a variety of functions/methods are patched to return different values so that things like molecules display as images.

One of those changes is to patch the function `Draw.MolsToGridImage()` so that it returns an IPython Image instead of a PIL Image. `PandasTools.FrameToGridImage()` uses `Draw.MolsToGridImage()`, so the same patching affects it. This patch also changes the behavior of the `returnPNG` argument. 
Manually setting `returnPNG=False` when calling `FrameToGridImage()` (or `MolsToGridImage()`) is, as you've figured out, the way to get the original behavior of having the code return a PIL Image object.

Note: if you want you can completely disable the patches installed by IPythonConsole by calling `IPythonConsole.UninstallIPythonRenderer()`

**Comment by RMeli** [comment]
Thanks for expanding the explanation given in https://github.com/rdkit/rdkit/issues/2974#issuecomment-784222809 ! It is much clearer now.

I did not realized the returned object was a `IPython.core.display.Image` and not a `PIL.Image`. I guess it would be nice if the two had the same API...

Is this discussed in the documentation already? If not, I can add a note somewhere sensible.

**Comment by greglandrum** [comment]
No, there's currently no documentation about which functions/methods are modified when working in the notebook.
That would be a good section for the Getting Started in Python document though.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by RMeli** [comment]
Yes, the question is answered. Thank you very much!

I left it open to remind myself to add something to the documentation, but I just made a note and I'll try to open a PR when I have time.
