### ISSUE TITLE
rdFMCS.FindMCS uses huge amounts of memory for this pair of molecules when CompleteRingsOnly is True

### ISSUE THREAD

**Issue by i-tub** [rdkit/rdkit#3965]
When I try to find the MCS between these two mols (only differing in the location of one ring nitrogen), I find that after waiting a couple minutes, the Python process is already using 4 GB of RAM. I've killed it at this point, so I don't know if it ever finishes, but I heard from someone who saw it die from lack of memory, at which point it presumably was taking tens of GB.

![image](https://user-images.githubusercontent.com/16563496/112071088-8973bd00-8b45-11eb-9e56-6217931cd5f1.png)

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdFMCS

ref = Chem.MolFromSmiles('CC(C)CNC(=O)[C@H](C(C)C)C[C@H](O)[C@@H](NC1=O)COCc(ccc2)cc2[C@@H](c3ccccc3)NC(=O)c(cc14)cc(c4)N(C)S(=O)(=O)C')
lig = Chem.MolFromSmiles('CC(C)CNC(=O)[C@H](C(C)C)C[C@H](O)[C@@H](NC(=O)c(cc12)nc(c1)N(C)S(=O)(=O)C)COCc3cc(ccc3)[C@H](NC2=O)c4ccccc4')

params = rdFMCS.MCSParameters()
params.BondCompareParameters.CompleteRingsOnly = True

result = rdFMCS.FindMCS([ref, lig], params)
print(result)
```

**Expected behavior**

Some kind of MCS result in a reasonable amount of time and memory. :-) Without the CompleteRingsOnly flag, the job completes in less than 2 seconds.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: CentOS 7
 - Python version (if relevant): 3.7.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? Not sure.
 - If you are not using conda: how did you install the RDKit? I've also reproduced the bug with the RDKit bundled by Schrödinger with its 21-1 suite.

**Comment by ricrogz** [comment]
Just a small heads up: the SMILES in the code snippet do not match the image. In the code, the difference is that in one of the mols we have a C atom that is a N atom in the other one. These are the mols in the code:

![image](https://user-images.githubusercontent.com/7498185/122264971-2eccd180-cea6-11eb-99c5-4e1fcdd9cec2.png)

**Comment by i-tub** [comment]
Thanks for catching that mistake! I had been working with the three molecules (N in one place, N in the other place, or no N in that ring) and ended up using SMILES not matching the images. Anyway, the sample code still uses a lot of time and memory when I run it. :-)

**Comment by rachelnwalker** [comment]
I looked into this issue for a bit and it seems that the MCS algorithm is stuck in a long (probably infinite?) 'loop' in certain queries where `BondCompareParameters.CompleteRingsOnly` is set to `True`. Interestingly, the algorithm does find the correct answer to the example given in this issue after ~7s, but never completes the search. I made a [PR (closed now)](https://github.com/rdkit/rdkit/pull/4328) that solves this problem but breaks the algorithm for some other cases.  

I think this example is gets stuck because the `findMCS` algorithm thinks that it can get a larger MCS using a seed that cannot close incomplete rings. In the PR I mentioned, I tried to fix this by only growing seeds that could potentially close incomplete rings, but this doesn't seem to be the best approach. I think that another reasonable approach could be to change `Seed::computeRemainingSize` so that a seed can recognize how big it will grow with no incomplete rings.

Another fix could be to implement the optimization mentioned [here](https://github.com/rdkit/rdkit/blob/24339823863bbdd7efc6f917b6e1c01caaf73bfc/Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp#L399).

**Comment by i-tub** [comment]
@greglandrum , I finally got around to testing this. It _did_ finish, which is definitely an improvement, but still took around 2 minutes and 2 GB. Now I must admit that I may not fully appreciate the algorithmic complexity here, but is this much time and memory reasonable? It feels a little excessive.

**Comment by DavidACosgrove** [comment]
If you’re only interested in the MCS between 2 molecules at a time, you might check out the new RASCAL MCES implementation that Greg blogged about a few weeks ago. I’d be interested to know how it does with that pair of molecules.

**Comment by i-tub** [comment]
Thanks, I'll give RASCAL a try and let you know how it goes!

**Comment by mjjmmj** [comment]
version 2023.09.6 still fails on the ff: compounds even with 64GB ram.

from rdkit import Chem
from rdkit.Chem import rdFMCS

prb = 'CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CCCCN)NC(=O)[C@@H]2CCCN2C(=O)[C@H](Cc2ccc(O)cc2)NC(=O)CSC[C@@H](C(=O)O)NC(=O)[C@H](Cc2c[nH]c3ccccc23)NC1=O'

ref = 'CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2c[nH]c3ccccc23)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H]([C@@H](C)CC)NC(=O)[C@H](CC(=O)N[C@@H](Cc2ccc(O)cc2)C(=O)O)NC(=O)CSC[C@@H](C(=O)O)NC(=O)[C@H](Cc2c[nH]c3ccccc23)NC1=O'

mol1 = Chem.MolFromSmiles(prb)
mol2 = Chem.MolFromSmiles(ref)
mcs = rdFMCS.FindMCS([mol1, mol2], ringMatchesRingOnly=True,completeRingsOnly=True)
