### ISSUE TITLE
Problems generating conformers for a macrocycle

### ISSUE THREAD

**Issue by sargelavoie** [rdkit/rdkit#3984]
**Describe the bug**
I try to generate conformers using the method EmbedMultipleConfs from a 3D sdf file prepared with Chem3D. Molecule A is a macrocycle embedding two aromatic rings. For a reason i don't know, it fails to return any conformer. I reduced my code to its simplest form and tested it with two different molecules. For molecule B, it works perfectly with 10 conformers returned in 2.55 sec, but none with compound A after 258 sec of computation (still only 2.55 of system cpu time). Is their a way to debug what happen internally in EmbedMultipleConfs  to understand why it fail? I tried the code on two different systems, but both behave the same.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import AllChem

def main():
    input_file = "moleculeA.sdf"
    #input_file = "moleculeB.sdf"
      
    suppl = Chem.SDMolSupplier(input_file, removeHs=False) #open input file and take the first molecule
    mol = suppl[0] #take the first and only molecule
    params=AllChem.ETKDGv2() #prepare the parameters for conformer generation
    params.numThreads=1
    params.randomSeed=1
    params.useRandomCoords=True
    ids=AllChem.EmbedMultipleConfs(mol, 10, params)
    print("%d conformers generated" % len(ids))

if __name__ == "__main__":
    main()
```
The molecule structures can be find here:
[https://www.swisstransfer.com/d/8786dcc3-6055-42a3-9fc5-7b28b701e9f0](https://www.swisstransfer.com/d/8786dcc3-6055-42a3-9fc5-7b28b701e9f0)

**Expected behavior**
Some conformers should be returned

**Configuration (system 1) :**
 - RDKit version: 2020.09.3 (py39hccf6a74_0)
 - OS: CentOS 7
 - Python version (if relevant): 3.9.1
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Configuration (system 2) :**
 - RDKit version: 2020.09.3 (py36he549ac7_0)
 - OS: Windows 10 (20H2)
 - Python version (if relevant): 3.6.12
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
Hi @sargelavoie : sorry for the very slow reply on this.
I can confirm the problem, also with v2021.03.1 of the RDKit, but I'm afraid I don't have a good answer for you as to what is going on or how to work around it. I will dig a bit to see if I can track it down so that we can fix this.

**Comment by greglandrum** [comment]
After a bit more investigation: the "K" terms in ETKDG - which, among other things, try to make conjugated systems flat - are causing the problem in your molecule. Specifically it looks like the code is having problems getting the phenyl rings flat without ending up with the aromatic H atoms which point in to the macrocyle having bad bumps, either with each other or with Hs across the macrocycle. Here's an image of your input structure showing how crowded things are:
![image](https://user-images.githubusercontent.com/540511/115406373-66453780-a1ef-11eb-9c23-01cf2a3c2fac.png)

A workaround here is to disable the K terms, like this:
```
params=AllChem.ETKDGv2() #prepare the parameters for conformer generation
params.numThreads=1
params.randomSeed=1
params.useRandomCoords=True
params.useBasicKnowledge = False
ids=AllChem.EmbedMultipleConfs(mol, 10, params)
```
Note that the resulting conformers are pretty horrible looking (since the aromatic rings aren't flat) and will definitely need to be minimized with a force-field before you use them for anything real.

I'm going to see if there's a way to resolve this within the RDKit itself, but I'm not super optimistic about that.
