### ISSUE TITLE
Problem finding potential stereo-centres in bridged bicyclics involving 4-membered rings?

### ISSUE THREAD

**Issue by jepdavidson** [rdkit/rdkit#4155]
FindPotentialStereo() fails to find centres in bridged bicyclic systems involving a 4-membered ring.
See original rdkit-discuss [here](https://sourceforge.net/p/rdkit/mailman/message/37285715/).

Four test cases are given in the code below:
- Symmetrically-disubstituted 6-membered ring
- A bridged version (using a 1-atom bridge to avoid a completely symmetrical product)
- Symmetrically-disubstituted 4-membered ring
- A bridged version (this time using a 2-atom bridge to avoid symmetry)

```
smi_list = ['CC1CCC(CC1)C(N)=O', 'CC12CCC(CC1)(C2)C(N)=O', 'CC1CC(C1)C(N)=O', 'CC12CC(C1)(CC2)C(N)=O']
for smi in smi_list:
    mol = Chem.MolFromSmiles(smi)
    display(show_mol(mol, size=(450, 200)))  # wrapper function for new drawing code in jupyter
    print(list(Chem.FindPotentialStereo(mol)))
    print(Chem.FindMolChiralCenters(mol, includeUnassigned=True, useLegacyImplementation=False))
```

![image](https://user-images.githubusercontent.com/7816101/118841852-94866780-b8c0-11eb-8ab3-5523db27e4a3.png)

In the case of the bridged 4-membered ring (or bridged 5-membererd ring, depending on your viewpoint!), FindPotentialStereo() fails to identify the two potential stereo atoms (it would be expected to be stereochemically analogous to the other three cases.

 - RDKit version: 2021.03.2
 - OS: Debian GNU/Linux 10 (buster)
 - conda-forge

**Comment by greglandrum** [comment]
@jepdavidson, I spent a while looking at the code here and can explain what's going on. Unfortunately that just leads to more questions... Let me explain what's happening and why and see what you think. I find this a tricky topic, so it could be that I got something wrong.

We're dealing here with an example of what I call "ring stereochemistry" (I think IUPAC refers to this as pseudo-asymmetry, but they frustratingly don't have a specific example of it in their "basic terminology of stereochemistry" document): there are two atoms involved which are opposite each other in a ring, and each of those atoms has at least two identical substituents. This would normally disqualify those atoms from being considered as potential stereocenters, but their relative orientation ends up being important. Your first and third molecules are good examples of this:
These two molecules are the same: 
![image](https://user-images.githubusercontent.com/540511/120282374-4f980300-c2ba-11eb-84ac-9f9905eb6186.png)
but these two are not:
![image](https://user-images.githubusercontent.com/540511/120282402-5a529800-c2ba-11eb-96df-77d8cfc30494.png)

The RDKit has logic to handle these situations and, I think, does the right thing.

Things are more complicated when you have fused rings like in your second and fourth examples.

The stereochemistry perception code has logic to recognize that multiply fused rings are different. This molecule has two stereocenters:
![image](https://user-images.githubusercontent.com/540511/120287010-1f069800-c2bf-11eb-8dcd-1372dcd8bce0.png)
but if I connect the two methyl groups to each other to close the ring I end up with no potential stereocenters:
![image](https://user-images.githubusercontent.com/540511/120286767-e49cfb00-c2be-11eb-8f8f-51976f53e269.png)

I added this logic to reflect the fact that there's really no conformational flexibility in this system, this is the only form of the structure which is possible:
![image](https://user-images.githubusercontent.com/540511/120287975-0b0f6600-c2c0-11eb-98bd-045c2d90dec5.png)
since this definitely doesn't make sense:
![image](https://user-images.githubusercontent.com/540511/120288092-24181700-c2c0-11eb-8b96-26062b07985c.png)

Based on that logic, your last molecule, which has no conformational flexibility, is being treated properly: it shouldn't have potential stereocenters. The actual bug in the current logic is that your second molecule has potential stereo recognized at all.

*However* after going through this analysis I think I may have overstepped by adding the logic to remove ring stereo from these fused systems. It's looking like it'll be challenging to always get this exclusion right (this issue is a case in point) and I'd rather be overly permissive about what is considered to be a possible stereocenter than overly restrictive. 

So I'm going to look into removing the fused ring test for considering possible stereocenters and see what impact that has.

Feedback or comments or questions about all of this are more than welcome. As I said: think it's pretty easy to overlook details and edge cases and get things wrong here.

**Comment by jepdavidson** [comment]
@greglandrum - thanks for looking into this.
I absolutely agree that in the case of strained systems often only one geometry makes physical sense; even if in principle more than one can be drawn in 2D with wedges/hashes.

But I think being more permissive / removing the 'physical' rules is definitely a good direction.  For me, the question being asked by 'find potential stereocentres' should be purely one of symmetry - and I guess the fewer rules, the better / more consistent things can be.

Adamantanes are well-known systems where there is only one physically-relevant way of joining-the-dots.  RDKit identifies the potential stereocentres in these situations:
```
from rdkit import Chem
from rdkit.Chem import AllChem, rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG, display

print(Chem.rdBase.rdkitVersion)

# A tetra-substituted adamantane with a plane of symmetry
m = Chem.MolFromSmiles('CC12CC3(C)CC(N)(C1)CC(O)(C2)C3')
centers = Chem.FindMolChiralCenters(m, useLegacyImplementation=False, includeUnassigned=True)
print(centers)

# Make a valid 3D geometry
mh = Chem.AddHs(m)
AllChem.EmbedMolecule(mh)
AllChem.MMFFOptimizeMolecule(mh)
m = AllChem.RemoveHs(mh)

# Draw in 3D
drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
drawer.drawOptions().addStereoAnnotation = True
drawer.DrawMolecule(m)
drawer.FinishDrawing()
display(SVG(drawer.GetDrawingText()))

# Assign the stereocentres from 3D
Chem.AssignStereochemistryFrom3D(m)
centers = Chem.FindMolChiralCenters(m, useLegacyImplementation=False, includeUnassigned=True)
print(centers)

# Draw in 3D
drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
drawer.drawOptions().addStereoAnnotation = True
drawer.DrawMolecule(m)
drawer.FinishDrawing()
display(SVG(drawer.GetDrawingText()))
```
![image](https://user-images.githubusercontent.com/7816101/120301140-79eebe00-c2c4-11eb-95b5-c7f46521197a.png)

Other toolkits (JChem, Biovia) also appear to always flag the centres (even if their CIP rule implementations are sometimes lacking...).

I think this also raises some other considerations over whether a non-stereo representation is equivalent to a stereo representation when only one isomer is physically achievable...  The SMILES, InChI's, etc will of course be different; so how to immediately know that the two representations of the adamantane above mean the same thing (or asked another way, should canonicalisation know the equivalence and add the parity info, or know about it and remove it, or do nothing?).

HSRBAOBUCHCHTQ-UHFFFAOYNA-N  (without defined stereocentres)
HSRBAOBUCHCHTQ-IWDIQUIJNA-N  (with defined stereocentres)
