### ISSUE TITLE
better integration of the SA score

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#4161]
**Is your feature request related to a problem? Please describe.**
We have a SA score demo script.
If would be nice if the SA score is more integrated into rdkit,
for example if it becomes one of the rdmoldesc functions.

**Describe the solution you'd like**
Well, maybe the first thing is that P.Ertl's SA score becomes one of the molecular
descriptors.

**Describe alternatives you've considered**
I could write an ad-hoc script.
But, in the long run, the more rdkit can do, the more useful.

**Comment by greglandrum** [comment]
@UnixJunkie I agree that having an updated version of SA score integrated would be useful.

I say "updated" because the scoring algorithm relies on the bit IDs from the RDKit's morgan fingerprints and bug fixes in the underlying RDKit code (not the fingerprinting code itself) in the years since that work was done have caused bit IDs to change in some cases. Those molecules will have inaccurate predictions.

I'd like to have this cleared up before moving the code into the core, but that will require someone to re-do the analysis Peter and Ansgar did for the original paper using an up-to-date version of the RDKit. We'll want to add tests too in order to have a chance at detecting future changes.

**Comment by UnixJunkie** [comment]
I might be able to update the model.
I will have a look into how the current script is working.
