### ISSUE TITLE
Incorrect drawing of E/Z stereoisomers 

### ISSUE THREAD

**Issue by SamusRam** [rdkit/rdkit#4180]
**Describe the bug**
E/Z stereoisomers are drawn incorrectly by RDKit. E.g., (2Z,6E)-Hedycaryol is drawn as 
![](https://i.imgur.com/GK4qIU6.png)
while the correct drawing (produced by any other visualizer I tried) is
![](https://i.imgur.com/Uh4eeC6.png).

Analogously, (+) Germacrene A is drawn by RDKit as follows:
![](https://i.imgur.com/hA1gwxc.png)
while the correct drawing is:
![](https://i.imgur.com/Mi9aM4i.png)

**To Reproduce**
```
from rdkit.Chem.Draw import *
from rdkit.Chem import inchi
from IPython.display import SVG, display

for InChI in ['InChI=1S/C15H24/c1-12(2)15-10-8-13(3)6-5-7-14(4)9-11-15/h6,9,15H,1,5,7-8,10-11H2,2-4H3/b13-6+,14-9+/t15-/m1/s1',
              'InChI=1S/C15H26O/c1-12-6-5-7-13(2)9-11-14(10-8-12)15(3,4)16/h6,9,14,16H,5,7-8,10-11H2,1-4H3/b12-6+,13-9-/t14-/m1/s1']:
    mol = inchi.MolFromInchi(InChI)
    drawer = rdMolDraw2D.MolDraw2DSVG(300, 300)
    drawer.drawOptions().addStereoAnnotation = True
    drawer.DrawMolecule(mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    display(SVG(svg.replace('svg:','')))
```

**Expected behavior**
The expected behavior is the correct depiction of substituents' orientation around double bonds, just as other libraries do. Please, see the correct visualizations above. 

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.2
 - OS: CentOS 8
 - Python version: 3.6
 - Are you using conda? I tried to install rdkit both via conda and via pip, the result is the same.
 - If you are using conda, which channel did you install the rdkit from? I tried conda-forge and rdkit channels (for trying out older versions)
 `conda install -c conda-forge rdkit`, `conda install -c rdkit rdkit=2018.09.1`
 - If you are not using conda: how did you install the RDKit? 
 `pip install rdkit-pypi`

**Comment by vfscalfani** [comment]
Hi, I think you want to use the CoordGen library for these molecules. Try something like this below. Also, it is generally not recommended to create a molecule from an InChI, but that is a different conversation. I hope this helps.

```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG

mol = Chem.MolFromInchi('InChI=1S/C15H26O/c1-12-6-5-7-13(2)9-11-14(10-8-12)15(3,4)16/h6,9,14,16H,5,7-8,10-11H2,1-4H3/b12-6+,13-9-/t14-/m1/s1')
drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
drawer.drawOptions().addStereoAnnotation = True
drawer.DrawMolecule(mol)
drawer.FinishDrawing()
SVG(drawer.GetDrawingText())

```

**Comment by SamusRam** [comment]
> Hi, I think you want to use the CoordGen library for these molecules. Try something like this below. Also, it is generally not recommended to create a molecule from an InChI, but that is a different conversation. I hope this helps.
> 
> ```
> from rdkit import Chem
> from rdkit.Chem import Draw
> from rdkit.Chem.Draw import rdMolDraw2D
> from rdkit.Chem import rdDepictor
> rdDepictor.SetPreferCoordGen(True)
> from rdkit.Chem.Draw import IPythonConsole
> from IPython.display import SVG
> 
> mol = Chem.MolFromInchi('InChI=1S/C15H26O/c1-12-6-5-7-13(2)9-11-14(10-8-12)15(3,4)16/h6,9,14,16H,5,7-8,10-11H2,1-4H3/b12-6+,13-9-/t14-/m1/s1')
> drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
> drawer.drawOptions().addStereoAnnotation = True
> drawer.DrawMolecule(mol)
> drawer.FinishDrawing()
> SVG(drawer.GetDrawingText())
> ```

@vfscalfani , thank you a lot for your reply! It works like charm. I will close the issue. Could you please comment on why CoordGen is not used by default?

**Comment by ptosco** [comment]
@SamusRam I think the reason is that `CoordGen` does a much crisper job, but at the moment it is slower than the native RDKit depiction, particularly for large/complex molecules.

**Comment by vfscalfani** [comment]
Thanks @ptosco. There is also some information about CoordGen, precision, and timings here:  https://github.com/rdkit/UGM_2020/blob/master/Notebooks/Landrum_WhatsNew.ipynb

**Comment by SamusRam** [comment]
@ptosco , @vfscalfani , thank you for the informative replies and for your help!

**Comment by d-b-w** [comment]
Coordgen is expected to be much faster now than it was at the time of that notebook, but it's still quite a bit slower than RDKit's default 2D coordinate generation scheme. Schrödinger continues to put dev resources into improving the performance and quality of coordgen; if you can tolerate the performance now, it might be reasonable to switch.

**Comment by SamusRam** [comment]
@d-b-w , thank you for the detailed info! I've already switched to `CoordGen` and I would view it as my "personal default" 2D coordinate generation scheme.

**Comment by greglandrum** [comment]
I also use Coordgen by default for my own work since the team has made it significantly faster and the quality of the results tends to be quite high.

It's probably a good time for me to go back and look at a large number of structures again in order to see if it's worth making it the default in general.

**Comment by jepdavidson** [comment]
Hi, I know this issue is marked as closed, but I have to say I am still a bit confused on whether this is purely a discussion on differences in 2D depiction, or whether there is something more fundamental going on...

I was interested to see how RDKit's GenerateDepictionMatching3DStructure() method would do using the same input molecule, but actually I didn't get that far - as I couldn't generate a 3D conformation that retained the correct double-bond geometries usingMMFFOptimizeMolecule() first.  Here's example code using the InChI provided above for (2Z,6E)-hedycaryol.

```
from rdkit import Chem
from rdkit.Chem import Draw, AllChem, rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D, IPythonConsole
from IPython.display import SVG

rdDepictor.SetPreferCoordGen(True)

m = Chem.MolFromInchi('InChI=1S/C15H26O/c1-12-6-5-7-13(2)9-11-14(10-8-12)15(3,4)16/h6,9,14,16H,5,7-8,10-11H2,1-4H3/b12-6+,13-9-/t14-/m1/s1')
mh = Chem.AddHs(m)
AllChem.EmbedMolecule(mh)
AllChem.MMFFOptimizeMolecule(mh)
m = Chem.RemoveHs(mh)
Chem.MolToMolFile(m, 'test.mol')
                             
rdDepictor.SetPreferCoordGen(False)
drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
drawer.drawOptions().addStereoAnnotation = True
drawer.DrawMolecule(m)
drawer.FinishDrawing()
SVG(drawer.GetDrawingText())
```

As we are generating the coordinates ourselves, I don't think the preferCoordgen setting has any influence - but I left it set to True in this example.  You can see that the 3D conformation has both bonds in (Z) configuration - even though the input is (E) (Z).  Strangely(?), the correct (E) input geometry is actually (incorrectly) shown on the 2D depiction of the 3D geometry.

![image](https://user-images.githubusercontent.com/7816101/119910357-e8dbb800-bf4e-11eb-90fe-37bb3bec405c.png)

I get the same outcome, even if I explicitly embed 2D coordinates using coordgen prior to calling MMFFOptimize().

Is this issue somehow related to the 2D depiction, or is it independent and due to double-bond geometries potentially getting flipped during MMFF minimisation (and how should one get the desired geometrical isomer minimised in 3D)?

**Comment by ptosco** [comment]
@jepdavidson I have run into the same issues a couple of years ago while I was trying to embed constrained macrocycles with _trans_ double bonds. At the time `EmbedMolecule` did not enforce the stereochemistry of double bonds, and it looks like this is still the case:
```
from rdkit import Chem
from rdkit.Chem import AllChem
import nglview as nv

m = Chem.MolFromInchi('InChI=1S/C15H26O/c1-12-6-5-7-13(2)9-11-14(10-8-12)15(3,4)16/h6,9,14,16H,5,7-8,10-11H2,1-4H3/b12-6+,13-9-/t14-/m1/s1')
mh = Chem.AddHs(m)
AllChem.EmbedMolecule(mh)
0

view = nv.NGLWidget()
Chem.MolToSmiles(m)
'C/C1=C/C[C@H](C(C)(C)O)CC/C(C)=C/CC1'

view.add_structure(nv.RdkitStructure(mh), ext='mol')
view.clear_representations()
view.add_line(multipleBond=True, bondSpacing=1.5)
view
```
![image](https://user-images.githubusercontent.com/5244385/119946190-a8a02800-bf96-11eb-80b1-db685685fcbe.png)
Once the wrong stereochemistry is in place, the MMFF optimization won't be able to do anything about it, and it would never flip a double bond geometry due to the high isomerization energy barrier.

However, if you manually cut the ring, set the dihedrals to a _trans_ geometry, mend the ring, set a dihedral constraint on those dihedrals and minimize with MMFF, with luck (and probably with chiral center inversions, if you have any, given how distorted the structure is after brutally resetting the dihedrals like that) you will get a _trans_ geometry:

```
mh_rw = Chem.RWMol(mh)
ch = mh_rw.GetConformer()
ff = AllChem.MMFFGetMoleculeForceField(mh_rw, AllChem.MMFFGetMoleculeProperties(mh_rw))
for b in mh_rw.GetBonds():
    if (b.GetBondType() == Chem.BondType.DOUBLE):
        ba = b.GetBeginAtom()
        ea = b.GetEndAtom()
        baNbrIdx = [nbr.GetIdx() for nbr in ba.GetNeighbors() if (nbr.IsInRing() and nbr.GetIdx() != ea.GetIdx())]
        assert(len(baNbrIdx) == 1)
        baNbrIdx = baNbrIdx.pop(0)
        baNbrIdx2 = [nbr.GetIdx() for nbr in mh_rw.GetAtomWithIdx(baNbrIdx).GetNeighbors() if (nbr.IsInRing() and nbr.GetIdx() != ba.GetIdx())]
        assert(len(baNbrIdx2) == 1)
        baNbrIdx2 = baNbrIdx2.pop(0)
        eaNbrIdx = [nbr.GetIdx() for nbr in ea.GetNeighbors() if (nbr.IsInRing() and nbr.GetIdx() != ba.GetIdx())]
        assert(len(eaNbrIdx) == 1)
        eaNbrIdx = eaNbrIdx.pop(0)
        mh_rw.RemoveBond(baNbrIdx, baNbrIdx2)
        Chem.SanitizeMol(mh_rw)
        AllChem.SetDihedralDeg(ch, baNbrIdx, ba.GetIdx(), ea.GetIdx(), eaNbrIdx, 180.0)
        mh_rw.AddBond(baNbrIdx, baNbrIdx2, Chem.BondType.SINGLE)
        Chem.SanitizeMol(mh_rw)
        ff.MMFFAddTorsionConstraint(baNbrIdx, ba.GetIdx(), ea.GetIdx(), eaNbrIdx, True, 0, 0, 1.e4)
ff.Minimize(maxIts=10000)
0
view2 = nv.NGLWidget()
view2.add_structure(nv.RdkitStructure(mh_rw), ext='mol')
view2.clear_representations()
view2.add_line(multipleBond=True, bondSpacing=1.5)
view2
```
![image](https://user-images.githubusercontent.com/5244385/119951667-7b567880-bf9c-11eb-9990-2f224ff95b59.png)

**Comment by jasondbiggs** [comment]
`EmbedMolecule` not respecting double-bond stereochemistry in rings was raised in [issue 1852](https://github.com/rdkit/rdkit/issues/1852).    

If `Compute2DCoords` is also ignoring ring bond stereo then that seems like a bug and I agree with the comment above that this issue was closed prematurely.
