### ISSUE TITLE
HetAtomTautomer Mol Hash may include explicit Hydrogens

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#4234]
Example:

```python
from rdkit import Chem
from rdkit.Chem import rdMolHash

mol = Chem.MolFromSmiles(r'[H]\N=C\C')
print(rdMolHash.MolHash(mol, rdMolHash.HashFunction.HetAtomTautomer))
```

This prints:
```
[H][N][CH]C_0_0
```

According to what we commented, this hash shouldn't include any explicit Hydrogen.

 I'm not too familiar with hashes, but there's some other's that also include explicit Hydrogens. Using the same `mol` object, 
```python
molhashf = rdMolHash.HashFunction.names
for i, j in molhashf.items():
    print(i, rdMolHash.MolHash(mol, j))
```
prints:
 ```
AnonymousGraph ****
ElementGraph [H]NCC
CanonicalSmiles [H]/N=C/C
MurckoScaffold 
ExtendedMurcko 
MolFormula C2H5N
AtomBondCounts 4,3
DegreeVector 0,0,2,2
Mesomer [H][N][CH]C_0
HetAtomTautomer [H][N][CH]C_0_0
HetAtomProtomer [H][N][CH]C_0
RedoxPair [H][N][CH]C
Regioisomer [H]/N=C/C
NetCharge 0
SmallWorldIndexBR B3R0
SmallWorldIndexBRL B3R0L2
ArthorSubstructureOrder 000400030100020001000014000000
 ```

**Comment by greglandrum** [comment]
I agree that the explicit H shouldn't be there for the tautomer hash. I think that's also true for the element graph, protomer, mesomer, and redox pair hashes.

An aside: you could make an argument that the hashes should be the same for molecules where we've called AddHs() as they are for molecules without the Hs explicitly present. I don't think this necessarily needs to be the case... client code which wants that guarantee can easily call `RemoveHs()` before generating a hash.

Your example is a nice one for showing the subtleties since it includes an H which needs to be there in order to define stereochemistry at the N atom (thus it shows up in the canonical SMILES)
