### ISSUE TITLE
DrawMorganBit returns empty image for "isolated" fingerprints

### ISSUE THREAD

**Issue by eguidotti** [rdkit/rdkit#4242]
**Describe the bug**
`DrawMorganBit` returns an empty image for "isolated" fingerprints, i.e. atoms with no bonds.

**To Reproduce**
Here I plot an example molecule:
```py
from rdkit import Chem
from rdkit.Chem import Draw, rdMolDescriptors
mol = Chem.MolFromSmiles('N.N.OC(O)=O')
mol
```
![mol](https://user-images.githubusercontent.com/24247667/121819544-ed61d980-cc8d-11eb-987b-99945443039d.png)

And here I try to plot the fingerprint corresponding to NH3. The image is blank.
```py
info = {}
rdMolDescriptors.GetMorganFingerprint(mol, radius=2, bitInfo=info)
# this should display NH3 but it's blank instead
Draw.DrawMorganBit(mol, 847950754, info)
```

**Expected behavior**
I would expect  an image like this:
![out](https://user-images.githubusercontent.com/24247667/121819953-46cb0800-cc90-11eb-90ee-0ae6a51fe5dc.png)

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.4
 - OS: Windows
 - Python version (if relevant): 3.7

**Comment by eguidotti** [comment]
Any hint so far?

**Comment by greglandrum** [comment]
I'm afraid not. That code still doesn't work in situations like this.

**Comment by eguidotti** [comment]
Thanks @greglandrum for the info. I'd be happy to help and fix this issue if you can point me to the file/function responsible for that.

I'm using rdkit to plot the fingerprints and explain AI predictions so I'm quite interested in avoiding blank images

**Comment by greglandrum** [comment]
Hi @eguidotti, what's happening is that the call to `Chem.PathToSubmol()` here - https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Draw/__init__.py#L751 - returns an empty molecule if the `enlargedEnv` argument (which is the list of bonds to include in the submol) is empty. Fragments from free atoms never have any bonds, so the enviroment ends up being empty.

The fix would be to detect the cases when `enlargedEnv` is empty and manually create a one-atom molecule instead of calling `PathToSubmol()`

**Comment by eguidotti** [comment]
Thanks @greglandrum. I've done what you suggested and created PR https://github.com/rdkit/rdkit/pull/5147

It is a simple one-line fix but let me know if there are better ways to create a one-atom molecule, otherwise... I look forward to the merge!

**Comment by eguidotti** [comment]
Would it be possible to merge https://github.com/rdkit/rdkit/pull/5261?
