### ISSUE TITLE
pg_restore does not work with some mol type molecule

### ISSUE THREAD

**Issue by mihalyszabo88** [rdkit/rdkit#4442]
**Describe the bug**
If in postgresql mol type column is used then pg_restore from a dump can cause errors for some molecules.

**To Reproduce**
`create table public.test (mol mol);
insert into public.test (values (mol_from_smarts('[SbH6-3]')));
select * from public.test;`
pg_dump -p5432 -U__USER__ -t test -n public > test_dump.sql
psql -h localhost -p5432 -U__USER__ -f test_dump.sql

ERROR:  could not create molecule from SMILES '[SbH6-3]'

**Expected behavior**
If a molecule can be inserted into a column, the dump / recovery process must work properly.

**Configuration (please complete the following information):**
 - RDKit version: **Release_2021_03_2**
 - OS: **Windows 10, Ubuntu 20.04, Debian linux-source 4.19.**
 - Python version (if relevant): -
 - Are you using conda? **No**
 - If you are not using conda: how did you install the RDKit? **RDKit database cartridge**

**Comment by greglandrum** [comment]
I agree that this is a bug, but it's not completely clear to me how to resolve it, so a fix may take a while.

What's going on is that the cartridge assumes that it can translate molecule columns to/from SMILES when you use pg_dump/pg_restore. This is generally not true if the molecule was constructed from SMARTS.

**Comment by mwojcikowski** [comment]
@greglandrum Would it be reasonable to set export format for mol type to pkl from SMILES? It would address at least few problems.

**Comment by greglandrum** [comment]
@mwojcikowski That's certainly possible, and it would clearly solve some problems, but then you'll see the pickled strings in the output of select statements instead of seeing something humanly readable. I think that's too big of a change.

The rdkit extension does define standard postgresql methods which serialize/deserialize molecules using pickles, but it seems that these are not used by pg_dump and there's no way to make it use them: https://stackoverflow.com/questions/27917771/how-to-dumprestore-a-postgresql-type-in-custom-binary-format

**Comment by greglandrum** [comment]
Here's a bit more detail on what's going on and why I think this isn't solvable by changing the molecule input/output functions in the cartridge.

PostgreSQL extension types define, among others, the two functions `INPUT` and `OUTPUT` which are used to construct the specified type from a string or to convert the specified type to a string. These need to be symmetric (i.e. the result of the output function needs to be parseable by the input function). There's more info on all of this here: https://www.postgresql.org/docs/12/xtypes.html

`pg_dump` and `pg_restore` use the output and input functions to do their work.

The OUTPUT function is also what's used to display a type when you do a `select` statement. So in this example, the `m` column, which is of type `mol`, is output as SMILES:
```
regression=# \d chemblmol;
              Table "public.chemblmol"
  Column  |  Type   | Collation | Nullable | Default 
----------+---------+-----------+----------+---------
 molregno | integer |           |          | 
 m        | mol     |           |          | 
Indexes:
    "mol_idx2" gist (m)

regression=# select * from chemblmol limit 2;
 molregno |                        m                        
----------+-------------------------------------------------
        1 | Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccccc1Cl
        2 | Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1C(=O)c1ccc(C#N)cc1
(2 rows)
```
The OUTPUT function is also what's used when returning results to python, so any changes to it will have wide-reaching consequences.

It would be easy enough to modify OUTPUT so that it produces SMARTS instead of SMILES for molecules which have query features, but this would require INPUT to also be modified to accept either SMILES or SMARTS. That's an easy change to make, but it would also have wide-reaching consequences since syntactically invalid SMILES like `ccc` would now be accepted: it would be parsed as SMARTS.

I think either of these changes are just too large and backwards incompatible.

**Comment by greglandrum** [comment]
One solution to this bug, and what I plan to implement, is to deprecate the function `mol_from_smarts()` and replace it with `qmol_from_smarts()`. The `qmol` type uses SMARTS as it's input/output format and would solve the problem @mihalyszabo88 is having:
```
regression=# select '[C,N,O]'::qmol;
  qmol   
---------
 [C,N,O]
(1 row)
```
