### ISSUE TITLE
bad placement of atom labels when using MolsToGridImage

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4519]
**Describe the bug**
This came up in the discussion of #4508 

When drawing the attached molecules in a grid, one of the atom labels ends up overlapping with a bond.

Here's what `MolsToGridImage` outputs:
![image](https://user-images.githubusercontent.com/540511/133447336-090b0ea6-bec5-4008-9b15-aa6692bfb70d.png)
but here's the image for the last molecule by itself:
![image](https://user-images.githubusercontent.com/540511/133447397-d9b0b38d-8734-469f-8113-5af8090c5d80.png)
That's not great, but it's better than what's in the grid.

**Configuration (please complete the following information):**
 - RDKit version: master
 - OS: all

[without_fielddisp_property.txt](https://github.com/rdkit/rdkit/files/7170685/without_fielddisp_property.txt)

**Comment by DavidACosgrove** [comment]
I wonder if this is as simple as it not taking account of the extra width of a double bond when doing the clash detection.  But also it would be better if it put the label in between the two single bonds. That should be a simple addition to the rules for where it starts the placement search, I think.
I believe the weather forecast is a bit shite for the weekend so I’ll try and find time to have a look at it.

**Comment by DavidACosgrove** [comment]
So, the problem is that the code that decides if a label clashes with something in the drawing assumes that the label is centred on the coords (TextAlignType::MIDDLE) but the SGroupData (and some others as well, for that matter) explicitly set it to TextAlignType::START.  This means that the rectangles used in the clash detection aren't actually where the text ends up.   It will take some re-factoring to fix this - it seems sensible that we pass an AnnotationType into calcAnnotationPosition rather than the plain string at present, so the alignment, orientation etc are available as well to be used and/or set.  It feels to me that we could do something a bit cleverer than decide arbitrarily, as the SGroupData example does, and change the alignment according to where the label is going to end up.  For example, in this case, use MIDDLE, but if it were going between the 2 single bonds, use END and if between the vertical single and the double, use START.
The basic solution will produce a placement as below for this test case.
![image](https://user-images.githubusercontent.com/9198870/134778775-df811e83-42d5-4693-a960-ffb35a2de542.png)
Ignore the blue rectangles, which are just there to show the problem but are where the string would end up with the fancy extra as described above.
@greglandrum Does that sound sensible?  If so, I'll try and get to it in the next week or so.

**Comment by greglandrum** [comment]
@DavidACosgrove if I'm understanding correctly, that sounds somewhat fiddly
Wouldn't it be easier to go with the first idea and have calcAnnotationPosition take a TextAligntType?

**Comment by DavidACosgrove** [comment]
@greglandrum Certainly, the first idea is the one to go with.  The rest was just an improvement once that was implemented.  It may be a refinement too far.  I'll see how long the first bit takes.  I suspect this will fix the phenylaniline problem as well.  A fix is becoming more imminent.
