### ISSUE TITLE
CalcNumRotatableBonds gives inconsistent results

### ISSUE THREAD

**Issue by ano302** [rdkit/rdkit#4524]
**Describe the bug**
The results for CalcNumRotatableBonds() gives different results, depending if hydrogens are present or not.
For example, an amide may not be detected if the hydrogen on the C(=O) is missing.
An other example is, that methyl groups become a rotatable bond, when hydrogen is added.

While this behavior may - from a technical point of view - be correct, from a chemists point of view it will lead to a lot of confusion and a high chance of wrong decision making.

P.s. I just noticed, this bug only shows, when there is a ring present.

**To Reproduce**
from rdkit import Chem
from rdkit.Chem import AllChem

test_mol = Chem.MolFromSmiles('C2CC(C)(C)C(C)(C)C2')
print("Number of atoms:", test_mol.GetNumAtoms())
print(Chem.rdMolDescriptors.CalcNumRotatableBonds(test_mol))
test_mol= Chem.AddHs(test_mol)
print("Number of atoms:", test_mol.GetNumAtoms())
print(Chem.rdMolDescriptors.CalcNumRotatableBonds(test_mol))

test_mol = Chem.MolFromSmiles('O=CN1CCNCC1')
print("Number of atoms:", test_mol.GetNumAtoms())
print(Chem.rdMolDescriptors.CalcNumRotatableBonds(test_mol))
test_mol= Chem.AddHs(test_mol)
print("Number of atoms:", test_mol.GetNumAtoms())
print(Chem.rdMolDescriptors.CalcNumRotatableBonds(test_mol))

**Expected behavior**
Consistent results, no matter if hydrogens are present or not.

**Configuration (please complete the following information):**
 - RDKit version: 2019.03.4 and 2021.03.5

 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment]
I understand your point, and agree that this isn't the best behavior, but there are numerous 2D descriptors in the RDKit which will return different values for molecules with and without explicit Hs added.
To get correct values, it's almost always a good idea to use hydrogen-suppressed graphs (i.e. molecules which don't have Hs explicitly present in the graph).

I'm going to close this as "wont-fix" because the computational cost of handling detecting Hs with every call to the various descriptor values isn't reasonable.
