### ISSUE TITLE
AlignMol could not find substructure match? 

### ISSUE THREAD

**Issue by Mirrty** [rdkit/rdkit#4575]
I am testing the Chem.rdMolAlign.AlignMol function,  which, as I understood from the documentation, could calculate RMS for two conformers as well as two different molecules. The function successfully returns RMS in case of conformers, but when I pass different molecules, it returned the following error:

> RuntimeError: No sub-structure match found between the probe and query mol

**My code:**
```
mol1=Chem.MolFromSmiles('c1ccccc1O')
mol2=Chem.MolFromSmiles('c1ccccc1N')
mol1=Chem.AddHs(mol1)
mol2=Chem.AddHs(mol2)

Chem.rdMolAlign.AlignMol(mol1,mol2)
```
**Expected behavior:**
Phenol and Aniline will be aligned by aromatic ring as MCS and RMS for the MCS is returned.

 - RDKit version: 2021.03.5
 - OS: [e.g. Ubuntu 20.04] Linux Centos 8
 - If you are using conda, which channel did you install the rdkit from? codna create -c conda-forge -n my-rdkit rdkit

++

**Comment by jasondbiggs** [comment]
Since `mol1` is not a substructure of `mol2` the automatic alignment will fail in this case.  You have to find the maximum common substructure between the two molecules and use that to provide an atom mapping between your two molecules.

See [this thread](https://sourceforge.net/p/rdkit/mailman/rdkit-discuss/thread/CAD4fdRTBOzg_5ytghQAH%3Dwgg2HPCDKQoqhmmpCmdBkV-HPVqBg%40mail.gmail.com/#msg35678724) for an example

**Comment by Mirrty** [comment]
Understood. Thank you, @jasondbiggs !
