### ISSUE TITLE
Wrong tautomers generated

### ISSUE THREAD

**Issue by sonial** [rdkit/rdkit#4700]
Hi,

I would like to obtain the canonical tautomer of a set of molecules preserving stereochemistry, here is my code:

```
tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveSp3Stereo = False
tautomer_params.tautomerRemoveBondStereo = False
tautomer_params.tautomerRemoveIsotopicHs = False

enumerator = rdMolStandardize.TautomerEnumerator(tautomer_params)
mol_can = standardizer.remove_hs_from_mol(Chem.MolFromSmiles(mol))
mol_can = enumerator.Canonicalize(mol_can)
```

In some instances, the obtained canonical tautomers look odd to me, as the changes in the canonical tautomer are in atoms/bonds that in my opinion should not be involved in tautomerisation. Se for instance the double bond move in `[H]C@]12SCC(CSC3=NN=NN3CCN(C)C)=C(N1C(=O)[C@H]2NC(=O)CC1=CSC(N)=N1)C(O)=O`
![image](https://user-images.githubusercontent.com/7021751/141794176-1e89c856-fdd0-4a65-8b68-8e6940cbbf6c.png)
 and the phosphate groups in  `CC1=CN([C@@H]2O[C@H](COP(O)(=O)OP(O)(=O)OP(O)(O)=O)C=C2)C(=O)NC1=O`
![image](https://user-images.githubusercontent.com/7021751/141794251-817cd3d4-7d71-46a7-bf7d-f6dc333d76b3.png)

Thanks for your help!

**Configuration**
RDKit version: 2021.03.5
OS: Windows 10
Python version: 3.9.7
Are you using conda? Yes
If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
@sonial : I agree that there's something suspicious about the tautomers being generated in the first example. I think we can get that fixed.

**Comment by greglandrum** [comment]
@ptosco : I'd appreciate your opinion about the change I'm thinking of making before I actually make it.
The odd tautomer in the first example here is being caused by the fact that the 1,5 (thio)keto/enol rules are being applied to molecules like this:
![image](https://user-images.githubusercontent.com/540511/142656049-481548f1-75cf-4d41-9d44-a2391e2a3743.png)
(I'm skipping a bunch of steps of debugging which led to this simple example).
I don't think the keto/enol rules should be applied to carboxylic acids

The definition of the 1,5 (thio)keto/enol forward transformation is here: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.in#L25
This, like most of the transforms, is something we brought over from MolVS.

The corresponding SMIRKS in the original paper (http://link.springer.com/10.1007/s10822-010-9346-4) is:
```
[O,S,Se,Te;X1:1]=[Cz1H0:2][C:5]=[C:6][CX4z0,NX3:3][#1:4][[ [#1:4][O,S,Se,Te;X2:1][Cz1:2]=[C:5][C:6]=[Cz0,N:3]
```
That uses a cactvs extension `z` (number of heteroatom neighbors), which the RDKit supports.

I would propose to modify the default tautomer transformations to match the ones in that paper as closely as we can, including using the cactvs extensions that the RDKit supports. I would also keep the original transforms around as a "v1" version so that people who want backwards compatibility can get it.

Make sense to you?

**Comment by sonial** [comment]
Thanks for looking into this @greglandrum. 
Do you think what is happening in my second example is expected? 
Phosphorus has only 5 valence electrons, hence 7 bonds do not look correct to me.

**Comment by greglandrum** [comment]
>Do you think what is happening in my second example is expected? Phosphorus has only 5 valence electrons, hence 7 bonds do not look correct to me.

The RDKit supports phosphorous with a valence of 7, so these do not involve valence exceptions. Whether or not it's a "nice" tautomer... there I don't have a strong opinion.
