### ISSUE TITLE
tautomerRemoveIsotopicHs does not give the expected result

### ISSUE THREAD

**Issue by sonial** [rdkit/rdkit#4783]
**Configuration**
RDKit version: 2021.03.5
OS: Windows 10
Python version: 3.9.7
Are you using conda? Yes
If you are using conda, which channel did you install the rdkit from? conda-forge

```
original_smiles = "CC=CO[2H]"
mol = Chem.MolFromSmiles(original_smiles)

tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveIsotopicHs = True

enumerator = Chem.MolStandardize.rdMolStandardize.TautomerEnumerator(tautomer_params)
mol_can = enumerator.Canonicalize(mol)

print(Chem.MolToSmiles(mol_can))
```

I would like to preserve deuteriums linked to atoms involved in tautomerism, but I noticed that the canonical tautomer is the same (`[2H]O=CCC` in this example) whether the `tautomerRemoveIsotopicHs` parameter is set to True or False.

By setting `tautomerRemoveIsotopicHs = False`, I would expect the result of tautomer canonicalization to be the same as the input in this case, is my assumption wrong? 

Thanks,
Sonia

**Comment by ptosco** [comment]
Hi Sonia, let me explain how this is supposed to work.
The `TautomerEnumerator` will only work sensibly if the input has no explicit Hs, i.e. no real H atoms in the graph, be it H, D or T.
This is true in many places across RDKit - many algorithm will break or will give unexpected results if real Hs are present in the input molecule.
This is the reason that prompted me to add the `RemoveHsParameters.removeAndTrackIsotopes` flag, which allows to remove all real Hs from a molecule and convert them to implicit, while keeping track of where H isotopes were originally located, such that `AddHs` can add them back at the original position.
Example:

```
from rdkit import Chem
import rdkit.Chem.MolStandardize.rdMolStandardize

original_smiles = "CC=CO[2H]"
mol = Chem.MolFromSmiles(original_smiles)
mol
```
![image](https://user-images.githubusercontent.com/5244385/145442845-6cc974f2-2838-406b-934b-763f94cf2789.png)
```
params = Chem.RemoveHsParameters()
params.removeAndTrackIsotopes = True
mol = Chem.RemoveHs(mol, params)
mol
```
![image](https://user-images.githubusercontent.com/5244385/145442898-24359f53-fd72-4e28-84f0-5514e127e6c8.png)
Now I will convert implicit Hs to real Hs, and then remove all non-isotopic Hs:
```
Chem.RemoveHs(Chem.AddHs(mol))
```
![image](https://user-images.githubusercontent.com/5244385/145443028-867735d6-a00c-4055-a2ca-4c03376dd5f7.png)
As expected, the isotopic Hs has been restored in the original position.

Let's now compute the canonical tautomer of this molecule with only implicit Hs:
```
tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveIsotopicHs = True
enumerator = Chem.MolStandardize.rdMolStandardize.TautomerEnumerator(tautomer_params)
mol_can = Chem.RemoveHs(Chem.AddHs(enumerator.Canonicalize(mol)))
print(Chem.MolToSmiles(mol_can))
CCC=O
```
Note that I will get the same result (i.e., no isotopic Hs) even if I set
```
tautomer_params.tautomerRemoveIsotopicHs = False
```
The reason is that since the canonical tautomer is different from the input tautomer, the assumption is that deuterium was exchanged with solvent during the tautomerization reaction and hence was removed.

However, if we repeat the experiment starting from the most stable deuterated tautomer, i.e. the canonical one, this time `tautomer_params.tautomerRemoveIsotopicHs` makes a difference:
```
d_propanaldehyde = Chem.MolFromSmiles("CC([2H])C=O")
d_propanaldehyde
```
![image](https://user-images.githubusercontent.com/5244385/145466884-b620d4bc-3d0e-44f3-8c46-6f38e39fe1f3.png)
```
d_propanaldehyde = Chem.RemoveHs(d_propanaldehyde, params)
d_propanaldehyde
```
![image](https://user-images.githubusercontent.com/5244385/145466938-eca6c380-3ca3-4937-9275-be3612f647fb.png)
```
tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveIsotopicHs = False
enumerator = Chem.MolStandardize.rdMolStandardize.TautomerEnumerator(tautomer_params)
d_propanaldehyde_can = Chem.RemoveHs(Chem.AddHs(enumerator.Canonicalize(d_propanaldehyde)))
print(Chem.MolToSmiles(d_propanaldehyde_can))
[2H]C(C)C=O
tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveIsotopicHs = True
enumerator = Chem.MolStandardize.rdMolStandardize.TautomerEnumerator(tautomer_params)
d_propanaldehyde_can = Chem.RemoveHs(Chem.AddHs(enumerator.Canonicalize(d_propanaldehyde)))
print(Chem.MolToSmiles(d_propanaldehyde_can))
CCC=O
```
The rationale is that in this case by setting `tautomer_params.tautomerRemoveIsotopicHs = False` we assume that no tautomerization reaction has actually taken place because the canonical tautomer is stable and does not exchange with solvent. This can be useful to avoid that deuterated molecules which are known to be stable to tautomerization are altered by the standardizer.
I hope this makes sense to you and clarifies the behaviour you observed.

**Comment by sonial** [comment]
Thanks for your quick reply @ptosco, your explanation makes sense from a chemical point of view and clarifies the output I am obtaining, but leaves me with more doubts on what I am trying to do.

I am creating a standardisation pipeline to compare compounds from different sources, and I would like to generate the canonical tautomer and merge compounds whose representation in different databases might refer to different tautomeric forms. By doing this, I don't want to lose the different stereochemistry (both sp2 and sp3) and isotopic composition of the atoms involved in tautomerism, which I thought could be done with the settings 
```
tautomer_params.tautomerRemoveIsotopicHs = False
tautomer_params.tautomerRemoveSp3Stereo = False
tautomer_params.tautomerRemoveBondStereo = False
```
Based on your explanation, it seems I have two options:
1. lose D assuming it is exchanged with water during the tautomeric transformation;
2. retain D, and obtain the keto-tautomer with charged O.

Neither of these options is ideal, as the first one will lead me to wrongly merge compounds with different chemical structures in terms of isotopic composition, and the second will import a wrong structure (positively charged O with 3 bonds) into my library.
The ideal solution for me would be to revert the generation of the canonical tautomer if D (or T) are linked to atoms whose oxidation state changes as a result of tautomerisation, but I cannot think of a way to implement this (and now I am not sure if it makes sense at all!).
If you have any input on this it would be much appreciated
