### ISSUE TITLE
MDL query with aromatic bond sets aromatic flag on atoms even though they are not in an aromatic ring

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#4785]
This query drawn in MarvinJS
![image](https://user-images.githubusercontent.com/5244385/145473089-7eeca9ba-784b-428e-bd64-bd81f6968d3e.png)
resolves to this MDL query that can't be read by RDKit:
```
Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  MRV SMA   1 [#6;a;a]
M  MRV SMA   2 [#6;a;a]
M  END
""")
RDKit ERROR: [21:44:20] non-ring atom 0 marked aromatic
[21:44:20] non-ring atom 0 marked aromatic
```
Similarly
```
Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  END
""")
RDKit ERROR: [21:44:47] non-ring atom 0 marked aromatic
[21:44:47] non-ring atom 0 marked aromatic
```
Skipping sanitization and removing the aromatic flags from atoms allows to sanitize:
```
mol = Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  END
""", sanitize=False)
mol.GetAtomWithIdx(0).SetIsAromatic(False)
mol.GetAtomWithIdx(1).SetIsAromatic(False)
Chem.SanitizeMol(mol)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
mol
```
![image](https://user-images.githubusercontent.com/5244385/145473724-b99ac815-f0c0-4cb3-9c23-4a12ea10a748.png)
However, attempting to generate a molblock gives the same molblock that can't be parsed:
```
print(Chem.MolToMolBlock(mol))

     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1
M  END
Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
RDKit ERROR: [21:52:26] non-ring atom 0 marked aromatic
[21:52:26] non-ring atom 0 marked aromatic
```

**Comment by greglandrum** [comment]
This is not really a bug, or at least it doesn't match the description. 

The RDKit always raises errors for aromatic atoms which aren't in rings when you sanitize a molecule:
```
In [20]: Chem.MolFromSmiles('c:c')
[04:41:21] non-ring atom 0 marked aromatic
```
I think this is a feature, not a bug: when doing sanitization and converting to a kekule form there's no way to figure out what the bond order should be. If you want to skip it and create query molecules then it's easy enough to disable sanitization entirely or to do partial sanitization.

In the case of Mol blocks there aren't actually aromatic atoms since the CTAB spec has no way to indicate that. What happens is the Mol file parser sees an aromatic bond and automatically sets the atoms on either end to be aromatic:https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FileParsers/MolFileParser.cpp#L2637

This doesn't need to happen this way... It looks like a couple of small changes to the code can resolve this without breaking other stuff, but I want to do a bit more testing to be sure.

**Comment by ptosco** [comment]
@greglandrum I completely agree with your analysis. You are right that the title is incorrect - that's because I wrote _before_ I spend quite a bit of time in figuring out what the problem was, which is exactly the one that you described, I have changed the tile, and many thanks for taking care of this!

**Comment by greglandrum** [comment]
@ptosco : I've assigned this to the 2022.03 release because it feels like it's a large-ish change for a patch release.
If you think it's important to have it in a patch release, we can change that.
