### ISSUE TITLE
Draw molecule with bond angles. 

### ISSUE THREAD

**Issue by cdelv** [rdkit/rdkit#4835]
**Is your feature request related to a problem? Please describe.**
I want to plot a molecule with its bond angles on top. Here I show an example
![Screenshot from 2021-12-28 20-37-31](https://user-images.githubusercontent.com/54986485/147619272-3ba8f3ac-be7b-4fdc-b4ba-e004ad503c84.png)

**Describe the solution you'd like**
The solution was briefly discussed in this discussion https://github.com/rdkit/rdkit/discussions/4832#discussioncomment-1879090. The idea is to have a function that does a `SetProp('atomdNote', 'bar')` but  instead of atomNote would be `SetProp('angleNote', 'bar')`. Then, we could iterate over all the angles and add the note. Also, it Would be nice if you could activate and deactivate the angle arc.  I know that there's a function already for that, then would be a matter of calling it. 

**Describe alternatives you've considered**
The alternative is to use the DrawString function but as you can see in the discussion, It doesn't give a good result and you'll have to manually select the x, y coordinates. Then, that alternative is not general and a lot of work. 

**Additional context**
I noticed that the functions `GetAngleDeg` and `GetBondLength` don't respect the coordinates of the mol file from which the molecule is initiated. You might want to be careful with that when testing. Also, @DavidACosgrove said he was going to work on this but I just wanted to officialize the feature request.

**Comment by DavidACosgrove** [comment]
What I meant in the discussion was that I will look at exposing setFontScale() to the python layer, not implement the whole of the code for showing the bond angles and lengths.  To me, and @greglandrum may disagree, this feels more like something that might go in contrib rather than form part of the base code.  It's a bit of a niche thing and I think what's important is to make sure that the tools are there for the user to create such a drawing.  As @greglandrum's [gist](https://gist.github.com/greglandrum/bf7a0d6b91ee2afb32724fc22ad8faf0) demonstrates, it's not a huge piece of work to write such functionality, once the necessary functions are there and working correctly.

**Comment by greglandrum** [comment]
> What I meant in the discussion was that I will look at exposing setFontScale() to the python layer, not implement the whole of the code for showing the bond angles and lengths. To me, and @greglandrum may disagree, this feels more like something that might go in contrib rather than form part of the base code. It's a bit of a niche thing and I think what's important is to make sure that the tools are there for the user to create such a drawing. As @greglandrum's [gist](https://gist.github.com/greglandrum/bf7a0d6b91ee2afb32724fc22ad8faf0) demonstrates, it's not a huge piece of work to write such functionality, once the necessary functions are there and working correctly.

I agree 100% with @DavidACosgrove here: this isn't code which would land in the C++. I could see it ending up in the cookbook or, possibly, somewhere in the rdkit.Chem.Draw module.
