### ISSUE TITLE
ROMol#getNumBonds(boolean) ignores onlyHeavy parameter in Java wrappers

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#4866]
The method `ROMol#getNumBonds(boolean)` reports the number of bonds including those to hydrogen if the molecule has explicit hydrogens

```
ROMol mol = RWMol.MolFromSmiles("[H]c1nc(OC([H])([H])C([H])([H])[H])c([H])c([H])c1[H]", 0);
System.out.println(mol.MolToSmiles()); // "[H]c1nc(OC([H])([H])C([H])([H])[H])c([H])c([H])c1[H]"
System.out.println(mol.getNumBonds(false); // 18 - as expected
System.out.println(mol.getNumBonds(true); // 18 - expected 9
```

if we remove H's all is fine:

```
ROMol mol = RWMol.MolFromSmiles("[H]c1nc(OC([H])([H])C([H])([H])[H])c([H])c([H])c1[H]", 0);
mol = RDKFuncs.removeAllHs(mol);
System.out.println(mol.MolToSmiles()); // "[H]c1nc(OC([H])([H])C([H])([H])[H])c([H])c([H])c1[H]"
System.out.println(mol.getNumBonds(false); // 18 - as expected
System.out.println(mol.getNumBonds(true); // 9 - as expected
```

**Configuration (please complete the following information):**
 - RDKit version: org.rdkit.knime.types_4.2.0.v202103031420
 - OS: [e.g. Ubuntu 20.04] W10
 - Python version (if relevant): N/A
 - Are you using conda? N/A
 - If you are not using conda: how did you install the RDKit? - KNIME

There's a possibility I might be missing something here, but I don't think I am!

Steve

**Comment by ptosco** [comment]
@sroughley Hi Steve, that's actually the expected behaviour. By default, the `onlyHeavy` parameter is `true`, which means that bonds to implicit Hs (i.e., Hs which are not included in the molecule graph as real atoms, but only exist as counts associated to their parent heavy atom) are not taken into account. Instead, if you set `onlyHeavy` to `false`, also bonds to implicit Hs will be counted. This is why you get different counts when you have implicit Hs in your molecule (as you do when you remove all real Hs from the graph calling `removeAllHs()`; by the way, `System.out.println(mol.MolToSmiles())` should return `CCOc1ccccn1` after calling `removeAllHs()`, so I am assuming you have a copy/paste typo above).
Instead, when you have Hs in the molecule graph as real atoms, there are no implicit Hs anymore, so their counts on the parent heavy are all zero. Instead, all bonds in the molecule are now between real atoms, and therefore are counted no matter whether they are between heavy atoms or involve hydrogens.
You may refer to these resources for further information on the different kinds of hydrogens in RDKit:
https://sourceforge.net/p/rdkit/mailman/message/29679834/
https://sourceforge.net/p/rdkit/mailman/message/36696340/
https://nextmovesoftware.com/blog/2013/02/27/explicit-and-implicit-hydrogens-taking-liberties-with-valence/

**Comment by sroughley** [comment]
Thanks @ptosco - I think that makes sense, I was just expecting it to exclude bonds to H regardless of whether they are implicit or explicit!

Yes, the SMILES was a copy/paste/too-late-on-Friday error!

Steve
