### ISSUE TITLE
Highlight bond widths: Setting highlight_linewidth_multipliers in DrawMoleculeWithHighlights leads to no change.

### ISSUE THREAD

**Issue by keishk** [rdkit/rdkit#4974]
**Describe the bug**
Setting highlight_linewidth_multipliers in DrawMoleculeWithHighlights leads to no change.
Possibly an issue with the Python layer.

**To Reproduce**
Shown in linked discussion #4972 

**Expected behavior**
Expect to see highlighted bond width to increase or decrease.

**Screenshots**
![highlight](https://user-images.githubusercontent.com/44964904/152013771-ef1ce385-40a8-44de-a66e-f2334dbc9371.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.2
 - OS: CentOS Linux release 7.9.2009
 - Python version (if relevant):
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
#4972

**Comment by DavidACosgrove** [comment]
Hi @keishk,
Sorry, this is a bug of documentation rather than implementation.  The highlight_linewidth_multipliers parameter is only used if drawOptions().fillHighlights is False. I don't think you would ever have guessed that from the documentation.  If you add the line '''d2d.drawOptions().fillHighlights = False''' before your call to draw the molecule, you should see an effect.  I will update the description of the function in the header file to reflect this.  At present it doesn't mention highlight_linewidth_multipliers at all.

**Comment by keishk** [comment]
Thanks @DavidACosgrove , that works for me now.
