### ISSUE TITLE
Extra hydrogens added using the MolFromPDB and Chem.Draw

### ISSUE THREAD

**Issue by davidRFB** [rdkit/rdkit#5219]
**Describe the bug**
the Draw module is adding an additional hydrogen into the image when the RDKIT molecules is created from a PDB file

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.
```
def draw_mol(mol, size=(300,300)):
    drawer = rdMolDraw2D.MolDraw2DSVG(size[0], size[1])
    drawer.drawOptions().annotationFontScale = 0.9
    drawer.DrawMolecule(mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    return SVG(svg)

def create_mol_with_atom_names(file):
    mol = Chem.MolFromPDBFile(file,sanitize=True,removeHs=True)
    for atom in mol.GetAtoms():
        atomname= atom.GetMonomerInfo().GetName()
        atom.SetProp('atomNote', atomname)
    AllChem.Compute2DCoords(mol)
    return mol

mol = create_mol_with_atom_names('./files_visualization/DA_1MQ2.pdb')
draw_mol(mol,size=(400,200))
```
**Expected behavior**
The draw should not contain the hydrogen in P neither the hydrogen in OP2. 

**Screenshots**
![image](https://user-images.githubusercontent.com/28023319/163963040-16a4aa2e-f545-462c-a428-ec137ed93df4.png)
The additional hydrogen in the P atom is not present in the DA_1MQ2.pdb file. This also happen with other dNTP molecules.

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.5
 - OS: [e.g. Ubuntu 20.04] 20.04
 - Python version (if relevant): 3.9
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?
pip install rdkit-pypi
**Additional context**
Here is the PDB file used: 

```
ATOM     58  P    DA T   4      28.534  18.348  -2.730  1.00 44.30           P
ATOM     59  OP1  DA T   4      27.631  19.435  -3.189  1.00 44.28           O
ATOM     60  OP2  DA T   4      29.092  18.393  -1.354  1.00 43.75           O
ATOM     61  O5'  DA T   4      27.764  16.965  -2.911  1.00 44.96           O  
ATOM     62  C5'  DA T   4      27.127  16.640  -4.147  1.00 44.78           C
ATOM     63  C4'  DA T   4      26.501  15.267  -4.074  1.00 44.54           C  
ATOM     64  O4'  DA T   4      27.524  14.275  -3.821  1.00 43.52           O
ATOM     65  C3'  DA T   4      25.462  15.087  -2.967  1.00 45.21           C  
ATOM     66  O3'  DA T   4      24.414  14.231  -3.432  1.00 48.16           O
ATOM     67  C2'  DA T   4      26.249  14.409  -1.861  1.00 43.22           C  
ATOM     68  C1'  DA T   4      27.198  13.530  -2.656  1.00 41.83           C
ATOM     69  N9   DA T   4      28.448  13.200  -1.974  1.00 39.44           N
ATOM     70  C8   DA T   4      29.374  14.061  -1.438  1.00 39.01           C
ATOM     71  N7   DA T   4      30.411  13.459  -0.908  1.00 37.95           N
ATOM     72  C5   DA T   4      30.149  12.109  -1.104  1.00 36.70           C
ATOM     73  C6   DA T   4      30.867  10.948  -0.772  1.00 35.50           C
ATOM     74  N6   DA T   4      32.049  10.961  -0.153  1.00 35.52           N
ATOM     75  N1   DA T   4      30.324   9.757  -1.104  1.00 34.28           N
ATOM     76  C2   DA T   4      29.141   9.746  -1.731  1.00 34.27           C
ATOM     77  N3   DA T   4      28.373  10.767  -2.100  1.00 35.28           N
ATOM     78  C4   DA T   4      28.940  11.935  -1.753  1.00 37.14           C
```

**Comment by ptosco** [comment]
@davidRFB That's not a bug, that's the expected behavior.
When you load a file with no hydrogen atoms with `sanitize=True`, RDKit will fill empty valences with implicit Hs.
In the drawing, all implicit hydrogens bonded to heteroatoms will be displayed: for example, in your drawing you have two OH groups and one NH2 groups; those hydrogens are not present in your PDB file, but were added by RDKit.
Similarly, in your PDB molecule phosphorus has 4 satisfied valences. RDKit knows that phosphorus is either tri- or penta-valent, and since 4 valences are satisfied, it concludes that phosphorus here is pentavalent, hence fills the empty valence with an implicit H.
Looking at the original 1MQ2 PDB file, you may notice that the `DA T   4` is bonded through a phosphodiester bond to the neighboring `DG T   3` bond.
If you simply extract `DA T   4`, it is expected that it will be missing an oxygen (that the RDKit replaces with an implicit H to avoid leaving a dangling valence), as you have cut it away from a polymer, but the DA monomer does have that oxygen:
![image](https://user-images.githubusercontent.com/5244385/164985463-9aaee4d6-788b-4615-a643-aa9d19ece6be.png)
If you wish to display the PDB ligand as is, without implicit Hs added, you need to load it with `sanitize=False`.
