### ISSUE TITLE
ReplaceSubstructs sometimes does not form bond to replacement, depending on order of atoms in SMARTS query

### ISSUE THREAD

**Issue by i-tub** [rdkit/rdkit#5329]
**To Reproduce**

```
from rdkit import Chem

# Example: replace the pyridine ring in 2-methyl pyridine with fluorine.

def replace(mol, query_smarts):
    query = Chem.MolFromSmarts(query_smarts)
    replacement = Chem.MolFromSmiles("F")
    products = Chem.ReplaceSubstructs(mol, query, replacement)
    print(Chem.MolToSmiles(products[0]))

mol = Chem.MolFromSmiles('Cc1ncccc1')

# try six different SMARTS for pyridine, only differing in atom order:
replace(mol, 'n1ccccc1')
replace(mol, 'c1ncccc1')
replace(mol, 'c1cnccc1')
replace(mol, 'c1ccncc1')
replace(mol, 'c1cccnc1')
replace(mol, 'c1ccccn1')

# Prints the following (expected result: "CF"):
# C.F
# CF
# C.F
# C.F
# C.F
# CF
```

**Expected behavior**

I would expect the output in all cases above to be CF, forming a bond to the replacement regardless of the SMARTS used for pyridine. Note: I also tried using `[F]` for the replacement SMILES, which led to the additional oddness that the product SMILES is `C[F]` or `C.[F]`, even if I add a sanitization step. Shouldn't `C[F]` canonicalize to `CF`? But maybe that's a separate issue.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: CentOS 7
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Schrodinger

**Comment by greglandrum** [comment]
@i-tub this is not well documented, but the bond between the replacement and whatever is left of the molecule after removing the pattern is always done between the first atom in the replacement and whatever is bonded to the atom in the molecule which matched the first atom of the pattern.
So in your case when the first atom of the pattern is a C which is adjacent to the N you end up with a C-F bond, otherwise you have two separate fragments.

This is expected behavior. I agree that it would be nice if it could somehow always do the right thing, but I don't think that's realizable (for example: what should the code do if you have more than one group attached to the substructure which is being removed?).

FWIW: The best way to exercise tight control over how substructures are replaced is to use the chemical reactions code.

**Comment by i-tub** [comment]
Thanks @greglandrum , that makes sense now! Still might be worth a documentation fix (I'd be happy to come up with a PR). I see the API allows specifying which atom to connect to in the replacement; would it make sense to be able to specify which atom to use in the pattern as well? (Of course, the pattern can be rewritten to put the right atom first, so it's not a big deal.)

I'll also see about adapting our code to use reactions.
