### ISSUE TITLE
Aromaticity perception fails

### ISSUE THREAD

**Issue by sjcheon86** [rdkit/rdkit#5405]
**Configuration (please complete the following information):**
 - RDKit version: 2022.03.3
 - OS: Ubuntu 16.04
 - Python version (if relevant): 3.10.5
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Describe the bug**
RDKit fails to percept some aromatic fused rings.
For example, [nH]1cc2c3c(cccc31)cc[nH]2 may be an aromatic fused ring.
But RDKit canonicalizes the SMILES into C1=Cc2cccc3[nH]cc(c23)N1.
To figure out why this happens, I looked into the atoms and bonds.
I could figure out that the 9, 10, 11 th atoms (cc[nH]) and their bonds are being considered not aromatic.

**To Reproduce**

codes
from rdkit import Chem
SMILES = '[nH]1cc2c3c(cccc31)cc[nH]2'
mol = Chem.MolFromSmiles(SMILES)
atoms = mol.GetAtoms()
print([atom.GetIsAromatic() for atom in atoms])
print([atom.GetNumExplicitHs() for atom in atoms])
bonds = mol.GetBonds()
print([(bond.GetBeginAtom().GetIdx(), bond.GetEndAtom().GetIdx())  for bond in bonds if bond.GetIsAromatic() == False])
SMILES_can = Chem.MolToSmiles(mol)
print(SMILES_can)

results
[True, True, True, True, True, True, True, True, True, False, False, False]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[(4, 9), (9, 10), (10, 11), (11, 2)]
C1=Cc2cccc3[nH]cc(c23)N1

**Expected behavior**

results
[True, True, True, True, True, True, True, True, True, True, True, True]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[]
c1[nH]c2cccc3cc[nH]c1c23

**Comment by greglandrum** [comment]
The RDKit's rules for aromaticity perception are described here: https://www.rdkit.org/docs/RDKit_Book.html#aromaticity

I believe that this molecule is not aromatic according to that definition since I can't find a ring which involves atoms 9, 10, and 11 and which has 4n+2 electrons. If we take all of the atoms into account then we end up with a system which has 14 electrons, but we're no longer talking about a single ring.

If I've missed something, please do point it out and I will re-open this.
