### ISSUE TITLE
pip install problem with Windows

### ISSUE THREAD

**Issue by jvalegre** [rdkit/rdkit#5416]
Dear RDKit devs,

I'm getting  an error when installing RDkit from pip that didn't show up when installing from conda-forge. I've seen this error in Windows 10 and 11 when I import the rdkit.Chem module in AQME (python program):

```
  File "PATH\anaconda3\lib\site-packages\aqme\csearch.py", line 18, in <module>
    from rdkit.Chem import AllChem as Chem
  File "PATH\anaconda3\lib\site-packages\rdkit\__init__.py", line 38, in <module>
    from . import rdBase
ImportError: DLL load failed while importing rdBase: The specified module could not be found.
```

I'm using an Anaconda 3 prompt with python 3.9.7 to run the code. 

Thanks,
Juan

**Comment by ricrogz** [comment]
Hola Juan,

I don't think this is a bug in RDKit. I'm rather inclined to think this is a problem with your setup:

I just installed the RDKit package using `pip` under non-Anaconda Python 3.9 on Windows 10, and I can run `python -c "from rdkit.Chem import AllChem as Chem"` without a traceback, so I don't think the package itself is broken.

But, if I install anaconda, and then again try to install the pypi rdkit package under it using `pip`, and again run `python -c "from rdkit.Chem import AllChem as Chem"`, then I get a traceback similar to yours. I think this might be happening because of some incompatibility between the pypi package and anaconda.

There's a workaround you can try, though. You can run the following in your anaconda environment before trying to use the rdkit package:
```
set PATH=%PATH%;{your PATH}\anaconda3\lib\site-packages\rdkit.libs
```
(Note that `{your PATH}` should be the same as the `PATH` in the traceback you posted)

This will tell the OS to also look for DLLs under path `{your PATH}\anaconda3\lib\site-packages\rdkit.libs`, and find the DLLs that the pypi rdkit package installs there, which are required to use rdkit. But please be aware that this might break dependencies for other anaconda packages. It's up to you to test this workaround and, if it works, decide if you are ok with it. Suerte!

Since, as I said, this is not an RDKit bug, I'm going to close this issue.
