### ISSUE TITLE
RGD with tetrazole core yields to core that cannot be kekulized

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#5500]
**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import rdRGroupDecomposition

core = Chem.MolFromSmiles("n1nn[nH]c1Cc1ccccc1")
core
```
![image](https://user-images.githubusercontent.com/5244385/184904822-7715be14-4bfb-4760-948f-88ca49a2325b.png)
```python
mol = Chem.MolFromSmiles("n1nnn(C)c1Cc1ccccc1")
mol
```
![image](https://user-images.githubusercontent.com/5244385/184904925-2cf5de1d-24ed-44ad-a5f4-e276378fdf7c.png)
```python
rgd = rdRGroupDecomposition.RGroupDecomposition(core)
rgd.Add(mol)
0

rgd.Process()
True

rgd.GetRGroupsAsRows(asSmiles=True)
[{'Core': 'c1ccc(Cc2[nH]nnn2[*:1])cc1', 'R1': 'C[*:1]'}]

Chem.MolFromSmiles('c1ccc(Cc2[nH]nnn2[*:1])cc1')
[16:31:47] Can't kekulize mol.  Unkekulized atoms: 5 7 8

rgd.GetRGroupsAsRows()[0]["Core"]
```
![image](https://user-images.githubusercontent.com/5244385/184905359-a41ef60e-e3f8-4599-829e-c61beedc6a93.png)

**Comment by Hong-Rui** [comment]
Hi @ptosco, I met this problem before.
The RGD is problematic when dealing with core the contains chemical gorups with aromatic nitrogens.
Our workaround on this issue is to convert the core as a SMARTS pattern, and then set the explicit hydrogen count to 0:
![1662119531749](https://user-images.githubusercontent.com/8930355/188136230-98bac22a-381b-4fc4-a897-564a7cfe57c2.png)

The RGD will work for this modified pattern mol.
Hope this helps.

**Comment by BJWiley233** [comment]
@Hong-Rui,

I tested doing this on this tetrazole containing molecule `Cc1cc(-c2nn[nH]n2)ccc1OS(=O)(=O)c1cccc(-c2nnnn2C)c1` and then followed up with `Draw.MolsToGridImage` to see if it could still be drawn and I get `Unkekulized atoms: 4 5 6 7 8` which are the atoms of the tetrazole ring.

**Comment by bp-kelley** [comment]
You can always have rgd return the molecule version of the core and just render that.  Barring that, you may have to render the smiles with sanitization off.

**Comment by bp-kelley** [comment]
rgd.GetRGroupsAsRows(asSmiles=False)

**Comment by BJWiley233** [comment]
Sorry I didn't mention I wasn't using RGD and I was just using the smiles as a reference to `AssignBondOrdersFromTemplate`.  Now I realize that it can't be drawn because when you remove the hydrogen from `1H-Tetrazole` this works as a template and my molecule is returned correctly with `AssignBondOrdersFromTemplate` but obviously it cannot be drawn because the valence for the nitrogen is 4.
