### ISSUE TITLE
Chirality not affected by atom-map index

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#553]
I've been working with Jameed's code from Contrib/mmpa. I figured I would update it to work more closely to the RDKit API instead of working with SMILES strings. One of the test cases is:

    C[C@@H](N)C(=O)O Ala1
    C[C@H](N)C(=O)O Ala2

The original code didn't identify the chiral change [*:1][C@@H]([*:2])[*:3]>>[*:1][C@H]([*:2])[*:3] . My modified code did. I eventually tracked it down to a difference in how RDKit handles atoms like "[1*]" vs. "[*:1]". For context, Jameed's code uses isotope labels then post-modifies the SMILES to convert [1*] to [*:1], etc. for 2 and 3, and re-canonicalizes the SMILES with the labels. My code uses the 'molAtomMapNumber' property to modify that value directly.

However, there's a subtle issue in that the isotope label version keeps the chirality in the final SMILES while the atom map version (both though re-canonicalization an by direct modification of the atom map number) does not. Here's a reproducible:

    >>> from rdkit.Chem import *
    >>> MolToSmiles(MolFromSmiles("[*:1][C@@H]([*:2])[*:3]"), isomericSmiles=True)
    'C([*:1])([*:2])[*:3]'
    >>> MolToSmiles(MolFromSmiles("[1*][C@@H]([2*])[3*]"), isomericSmiles=True)
    '[1*][C@@H]([2*])[3*]'

I think this ends up causing a bug in the MMPA code by ignoring (a small number of) transformations which have multiple cuts on the same atom, causing the stereo information to disappear. However, I'm still not sure about it, so perhaps this is something to take to Jameed.

**Comment by greglandrum** [comment]
I believe that the atom-map index should affect the chirality. It's an easy fix.

**Comment by adalke** [comment]
As a followup, the change and the tests I see only handle SMILES parsing. What about SMILES generation with hydrogens with atom maps? I think they should be left as actual atom terms in the SMILES, similar to how [2H] and other isotopes are kept.

    >>> mol = Chem.MolFromSmiles("[H:1][C@@H]([H:2])[H:3]")
    >>> Chem.MolToSmiles(mol)
    'C'
    >>> Chem.MolToSmiles(mol, allHsExplicit=True)
    '[CH4]'

**Comment by greglandrum** [comment]
That's not the SMILES generation, the Hs are being removed when you construct the molecule. You can turn this off:
```python
In [7]: mol = Chem.MolFromSmiles("[H:1][C@@H]([H:2])[H:3]",sanitize=False)

In [8]: Chem.SanitizeMol(mol)
Out[8]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [9]: Chem.MolToSmiles(mol,isomericSmiles=True)
Out[9]: '[C@H]([H:1])([H:2])[H:3]'
```
This should be easier; MolFromMolBlock() has a "removeHs" argument that allows you to sanitize the molecule without removing Hs first.

**Comment by adalke** [comment]
You're right. I should have compared it to how isotopically labeled hydrogens  are not removed during input process. Should atom class labeled hydrogens also not be removed? Though I think it's time for a new issue if so.

**Comment by greglandrum** [comment]
I double agree: that's a reasonable expectation of removeHs and it should be a new issue.

**Comment by j-wags** [comment]
I just stumbled upon this, and it actually explains some RDKit behavior we recently patched around. OpenFF is just starting to think about what map indices "mean" for a molecule, and how we should add it to our molecule spec. 

The [Daylight spec](https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html) does not make any statements about whether atom map indices are chemically significant. It specifies the isotope syntax used in this issue (section 3.3.1), but doesn't connect atom map indices to any particular physical/chemical meaning (section 3.5.1). At the same time, I'm not sure whether RDKit is super strict about adhering the Daylight SMILES spec, or if it has known differences.

@greglandrum, it's not clear from this this discussion or #1368 whether the statement "atom map indices are considered chemically important, at the same level as isotope labels" is a running design philosophy throughout RDKit, or if it's a behavior added to support this specific use case. I'd be interested in your thoughts on this, especially as OpenFF works out how we're going to treat map indices (and I'll link our own spec discussion here shortly).

**Comment by bp-kelley** [comment]
I think the problem that this is fixing is canonical representations of
fragments of molecules.  For MMPS the atom label is being used as a place
holder saying, "trust me, this will really be a stereo center".  Without
this, the stereo information would really, truly be lost.

For example:

```

m = Chem.MolFromSmiles("NC[C@](CC)(CO)CS")

>>> Chem.MolToSmiles(m)

'CC[C@@](CN)(CO)CS'
```

And reducing to the attached carbons, we can keep chirality.

```

>> m = Chem.MolFromSmiles("[C:1][C@]([C:2])([C:3])[C:4]")

>>> Chem.MolToSmiles(m)

'[C@]([C:1])([C:2])([C:3])[C:4]'
```

I'm quite interested in the issue you are having with OpenFF.  Are you
happening to use the same atom map label more than once?

**Comment by j-wags** [comment]
> For MMPS the atom label is being used as a placeholder saying, "trust me, this will really be a stereo center".

Thanks, @bp-kelley. That explanation makes a lot of sense. OpenFF is going to start dealing with molecule fragments soon, too, so we might be headed toward the same issue. 

> I'm quite interested in the issue you are having with OpenFF.  Are you happening to use the same atom map label more than once?

We use partially- or fully-indexed SMILES as a way to safely jump between QM and MM representations of the same molecule. By "MM molecule", I mean "graph molecule", and by "QM molecule" I mean "positions and symbols of nuclei, multiplicity, and total charge". When we make the jump from a MM to a QM representation of a molecule, we save a fully indexed SMILES of the molecule (with map indices corresponding to the order of symbols in the QM molecule). Keeping this around as metadata allows us to pull back the resulting geometry from the QM calculation, and unambiguously apply MM parameters to do energy comparisons. 

Keeping a fully mapped SMILES solves two problems:
* We would otherwise need to guess bond order and formal charge from geometry+symbols at the end of a QM geometry operation. 
* The graph molecule can change during QM operations (hydrogen migration, bond order changes). Keeping a fully indexed SMILES gives us a way to error-check the final geometries.

So, we've started implementing features to produce "MM molecules" from fully-indexed SMILES (load the fully-indexed SMILES in some arbitrary order, but then immediately reindex according to the map indices from the SMILES). However, using RDKit's stereochemistry detector, we were getting errors that the fully-indexed SMILES had undefined stereochemistry. Really, the issue was that a stereocenter was created in an otherwise non-stereogenic molecule due to the differences in atom indices. https://github.com/openforcefield/openforcefield/issues/412#issuecomment-528000213

Stripping map indices before checking chirality was an easy fix to make on our end.  https://github.com/openforcefield/openforcefield/commit/f8508e9f8581102660cae1b268e981ce30535054#diff-c854e3299a958176be6dac43c8f3213eR1895-R1903
