### ISSUE TITLE
Documentation for RDKit in Java

### ISSUE THREAD

**Issue by asmirn1** [rdkit/rdkit#5603]
Hi,

We are trying to use RDKit in our Java application to plot chemical structured from SMILES or InChI. But we didn't find any documentation for using RDKit in Java. Could you point us to Java documentation if it exists?

We found API and Getting Started documentation for C++. I wonder how similar the Java API and C++ API for RDKit, and whether we can use C++ documentation with our Java code.

Thank you!

**Comment by ptosco** [comment]
@asmirn1 Would you mind asking this question in the [Discussions](https://github.com/rdkit/rdkit/discussions) tab?
This makes it more discoverable to other users looking for the same information in the future and also keep the bug tracker tidy, since this is not actually a bug.
Thanks in advance, I am closing this now.
