### ISSUE TITLE
JS substructure match

### ISSUE THREAD

**Issue by PigUnderRoof** [rdkit/rdkit#5688]
Hi,

I am using RDkitJS 2022.09.01 from unpkg for substructure matching.

```
m = window.RDKit.get_mol("CC(=O)Oc1cc2SC(=O)Oc2c3ccccc13")
ref = window.RDKit.get_qmol("O=C1SccO1")
#~1 ref = window.RDKit.get_qmol("O=C1SCCO1")
#~2 ref = window.RDKit.get_qmol("O=C1SC=CO1")
match = m.get_substruct_match(ref)
```

match returns '{}', even with ~1 ~2 ref, while three all works in Python HasSubStrutureMatch.

Also notice JSSubstructLibrary added in 2021, should I turn to that?

Best

**Comment by PigUnderRoof** [comment]
Later, I tried with

```
m = window.RDKit.get_mol("CC(=O)Oc1cc2SC(=O)Oc2c3ccccc13")
ref = window.RDKit.get_mol("O=C1SccO1")
match = m.get_substruct_match(ref)
```

It works. What's the difference between mol and qmol, why is qmol necessary?

**Comment by greglandrum** [comment]
The difference is that `get_qmol()` parses the input as a SMARTS string while `get_mol()` parses it as a SMILES string.
Your input - `O=C1SccO1` - includes information about aromaticity on the atoms which is enforced when you parse it as a SMARTS. When parsed as a SMILES the RDKit does aromaticity perception, so that heterocycle is treated the same way in the query as it is in your molecule (the RDKit thinks that the heterocycle is aromatic).

**Comment by PigUnderRoof** [comment]
thx! @greglandrum
