### ISSUE TITLE
MolDraw2DCairo.GetDrawingText() doesn't work with Python3

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#571]
It's a bytes vs text problem.

**Comment by brilee** [comment]
I suspect a similar wrapper is needed for MolDraw2DSVG.GetDrawingText, as this method returns bytes in py2 but a unicode string in py3.

For the most part, this hasn't resulted in any issues because SVG is (mostly) ascii, and you can convert the unicode back to bytes with `.encode('ascii')`. But it's a code smell.
