### ISSUE TITLE
Favor a lower number of charged atoms in rdDetermineBonds.DetermineBonds()

### ISSUE THREAD

**Issue by diogomart** [rdkit/rdkit#5888]
See code below to reproduce. [This PR](https://github.com/jensengroup/xyz2mol/pull/25) from the original xyz2mol code solved this issue, at the expense of long runtimes. 

Here's a few more SMILES strings with this problem:
[charged-sulfur-smiles.txt](https://github.com/rdkit/rdkit/files/10283309/charged-sulfur-smiles.txt)
These molecules are from https://github.com/ghutchis/conformer-benchmark

Attaching pictures to show the four examples in this code snippet. 

```python
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdDetermineBonds
from rdkit.Chem import rdDistGeom
from rdkit.Chem import rdForceFieldHelpers

etkdgv3 = rdDistGeom.ETKDGv3()

def smiles_to_xyz(smiles):
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)
    rdDistGeom.EmbedMolecule(mol, etkdgv3)
    rdForceFieldHelpers.UFFOptimizeMolecule(mol)
    xyz_block = Chem.MolToXYZBlock(mol)
    charge = sum([atom.GetFormalCharge() for atom in mol.GetAtoms()])
    return xyz_block, charge

def get_mol_rdDetermineBonds(xyz_block, charge):
    mol = Chem.MolFromXYZBlock(xyz_block)
    rdDetermineBonds.DetermineBonds(mol, charge=charge)
    mol = Chem.RemoveHs(mol)
    return mol

smiles_list = [
    "Cn2c(C)csc2=O",
    "c1ccsc1C(=O)O",
    "C1CCCS1=O",
    "Nc1ncc2c(Sc3ccccc3)cccc2[nH+]1",
]

for smiles in smiles_list:
    xyz_block, charge = smiles_to_xyz(smiles)
    try:
        mol = get_mol_rdDetermineBonds(xyz_block, charge)
    except ValueError as e:
        print(e)
        continue
    new_smiles = Chem.MolToSmiles(Chem.RemoveHs(mol), isomericSmiles=False)
    print(smiles)
    print(new_smiles)
    print()
```

![1](https://user-images.githubusercontent.com/1564797/209042956-6e4f79d9-471a-4bc9-a8f2-4d91ade6f864.png)
![2](https://user-images.githubusercontent.com/1564797/209042959-57a0008a-53d1-49a3-9f64-ce260c7f5fd8.png)
![3](https://user-images.githubusercontent.com/1564797/209042961-16b10b8b-a00d-4f98-a87d-f40cd5ca0d65.png)
![4](https://user-images.githubusercontent.com/1564797/209042963-fff3bd7f-654d-4e1f-9eef-c34e3c9072bf.png)

**Comment by greglandrum** [comment]
What you are getting from `DetermineBonds()` in these cases are just resonance structures of the molecule you are looking for.
While I agree that these are not the nicest resonance forms, I do believe that they are correct.

In every case except the third molecule you can get your "expected" SMILES by enumerating the resonance structures of the output molecule like this:
```
    mol = Chem.RemoveHs(mol)
    suppl = Chem.ResonanceMolSupplier(mol,Chem.ResonanceFlags.UNCONSTRAINED_ANIONS | Chem.ResonanceFlags.UNCONSTRAINED_CATIONS)
    for struct in suppl:
        print('  ',Chem.MolToSmiles(struct))
```

Since the current behavior is not wrong, I'm going to change this to an enhancement request.

**Comment by jasondbiggs** [comment]
I ran into this issue today with the input SMILES "CS(C)=c1c(=O)c2ccccc2c1=O", which gets converted to "C[S+](C)C1=C([O-])c2ccccc2C1=O".  Except in this case I can't get the `ResonanceMolSupplier` to give me a non-charge separated form.

**Comment by greglandrum** [comment]
@jasondbiggs , we'll need @ptosco to confirm, but I believe what's going on in the case of your molecule is a bug in the `ResonanceMolSupplier`.
I would expect the resonance supplier to be symmetrical, so that if mol1 is a resonance form of mol2 then mol2 would also be a resonance form of mol1. That does not seem to be the case here:
```
In [19]: m = Chem.MolFromSmiles('CS(C)=c1c(=O)c2ccccc2c1=O')

In [20]: suppl = Chem.ResonanceMolSupplier(m,Chem.ResonanceFlags.UNCONSTRAINED_ANIONS | Chem.ResonanceFlags.UNCONSTRAINED_CATIONS)

In [21]: ms = [x for x in suppl]

In [22]: for m in ms: Chem.SanitizeMol(m)

In [23]: set([Chem.MolToSmiles(x) for x in ms])
Out[23]:
{'CS(C)=c1c(=O)c2ccccc2c1=O',
 'C[S+](C)C1=C([O-])C2=CC=C[CH+]C2=C1[O-]',
 'C[S+](C)C1=C([O-])C2=C[CH+]C=CC2=C1[O-]',
 'C[S+](C)C1=C([O-])[C+]2C=CC=CC2=C1[O-]',
 'C[S+](C)C1=C([O-])[c+]2cc[cH-]cc2C1=O',
 'C[S+](C)C1=C([O-])[c-]2cc[cH+]cc2C1=O',
 'C[S+](C)C1=C([O-])c2c[cH+]cc[c-]2C1=O',
 'C[S+](C)C1=C([O-])c2c[cH-]cc[c+]2C1=O',
 'C[S+](C)C1=C([O-])c2ccccc2C1=O'}

In [24]: m2 = Chem.MolFromSmiles('C[S+](C)C1=C([O-])c2ccccc2C1=O')

In [25]: suppl = Chem.ResonanceMolSupplier(m2,Chem.ResonanceFlags.UNCONSTRAINED_ANIONS | Chem.ResonanceFlags.UNCONSTRAINED_CATIONS)

In [26]: ms = [x for x in suppl]

In [27]: for m in ms: Chem.SanitizeMol(m)

In [28]: set([Chem.MolToSmiles(x) for x in ms])
Out[28]:
{'C[S+](C)C1=C([O-])C2=CC=C[CH+]C2=C1[O-]',
 'C[S+](C)C1=C([O-])C2=C[CH+]C=CC2=C1[O-]',
 'C[S+](C)C1=C([O-])[C+]2C=CC=CC2=C1[O-]',
 'C[S+](C)C1=C([O-])c2ccccc2C1=O',
 'C[S+](C)[C+]1C([O-])=c2ccccc2=C1[O-]',
 'C[S+](C)[C-]1C(=O)c2ccccc2C1=O'}
```

I guess this is related to the multiple possible valence states of S...

**Comment by ptosco** [comment]
@greglandrum @jasondbiggs Yes, this seems to be a bug in `ResonanceMolSupplier`, possibly connected to #4491. I'll try and take a look.

**Comment by rogersayle** [comment]
If I were to hazard a guess this issue with rdDetermineBonds preferring three valent positively charged sulfur is caused by the strange values in DetermineBonds.cpp's getValenceCombinations:
```
  const std::unordered_map<int, std::vector<unsigned int>> atomicValence = {
      {1, {1}},  {5, {3, 4}}, {6, {4}},     {7, {3, 4}},     {8, {2, 1, 3}},
      {9, {1}},  {14, {4}},   {15, {5, 3}}, {16, {6, 3, 2}}, {17, {1}},
      {32, {4}}, {35, {1}},   {53, {1}}};
```
Notice that the entry for element 16 (sulfur), lists valences as 6, 3, 2. (I believe in the algorithm's order of preference).  I would expect to see 2 (neutral) and 4 (neutral) before 3 (cation), and possibly even a final 1 (anion) to match oxygen's behaviour. 

One concern is that adding more valences may adversely affect the run-time (given the use of Cartesian product).

Note: this algorithm ("generate and test" using lazy cartesian product to generate and Edmond's maximum cardinality [Blossum algorithm] to test) probably isn't the best solution to this class of problem, but that's a different issue.

**Comment by diogomart** [comment]
@rogersayle that's a good point, made me realize I haven't been using valence=3 for sulfur, only 6, 4, and 2.
