### ISSUE TITLE
HEME only partially aromatic

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#5953]
**Describe the bug**
Using the SMILES string from pubchem for heme (https://pubchem.ncbi.nlm.nih.gov/compound/Heme#section=IUPAC-Name), `CC1=C(C2=CC3=NC(=CC4=C(C(=C([N-]4)C=C5C(=C(C(=N5)C=C1N2)C=C)C)C)CCC(=O)[O-])C(=C3C)CCC(=O)O)C=C.[Fe+2]`,   I'd expect all three nitrogen rings to be aromatic.

**To Reproduce**
```
>>> from rdkit import Chem                                                                                                                                                                                               
>>> heme = Chem.MolFromSmiles('CC1=C(C2=CC3=NC(=CC4=C(C(=C([N-]4)C=C5C(=C(C(=N5)C=C1N2)C=C)C)C)CCC(=O)[O-])C(=C3C)CCC(=O)O)C=C')                                                                                         
>>> Chem.MolToSmiles(heme)                                                                                                                                                                                               
'C=CC1=C(C)c2cc3[n-]c(cc4nc(cc5[nH]c(cc1n2)c(C)c5C=C)C(C)=C4CCC(=O)O)c(CCC(=O)[O-])c3C'
```
**Expected behavior**
I think that I'd expect all ring envelopes of the heme to be aromatic. I see the same issue with porphyrin- https://pubchem.ncbi.nlm.nih.gov/compound/Porphyrin#section=IUPAC-Name

**Comment by greglandrum** [comment]
I believe that this is expected behavior

Here's a drawing of the core of your heme structure with the aromatic bonds highlighted:
![image](https://user-images.githubusercontent.com/540511/213381552-76735aaa-257f-4da3-94e1-8b417cffa8d4.png)

Two of the five-membered rings are aromatic (they have 6 pi electrons) and two are not (they have 5 pi electrons). The entire inner envelope is aromatic (it has 18 pi electrons), but the RDKit doesn't find any path involving the "outer" two bonds of the non-aromatic five-rings. I did a bit of mental enumeration and didn't find anything to contradict that, but if you do see something, please let me know.

**Comment by d-b-w** [comment]
I guess I also cannot unless I delocalize the negative charge to 18 or 5. I'm going to close this because it's not a bug.
