### ISSUE TITLE
Issues with ACS1996 drawing mode on a small canvas

### ISSUE THREAD

**Issue by DavidACosgrove** [rdkit/rdkit#6041]
**Describe the bug**
Drawing a molecule into a small canvas in ACS1996 mode has a couple of problems:
1. The bonds are inside the letters sometimes
2. The down wedges aren't always seen.

**To Reproduce**
```
    auto m =
        "CC(C)(F)c1noc(N2CCCN([C@H]3CC[C@H](COc4ccc(S(C)(=O)=O)cc4F)CC3)CC2)n1"_smiles;
    MolDraw2DSVG drawer(125, 125);
    RDDepict::compute2DCoords(*m);
    drawer.drawOptions().addStereoAnnotation = true;
    MolDraw2DUtils::setACS1996Options(drawer.drawOptions(), 1.5);
    drawer.drawMolecule(*m);
    drawer.finishDrawing();
    std::string text = drawer.getDrawingText();
    std::ofstream outs(nameBase + "_2.svg");
    outs << text;
    outs.flush();
    outs.close();
```

**Expected behavior**
Not this.

**Screenshots**
Magnified significantly for clarity.
![image](https://user-images.githubusercontent.com/9198870/216282436-816e1669-cd81-4dfc-a08b-e5526d307826.png)

**Configuration (please complete the following information):**
 - RDKit version: master, also previous releases
 - OS: macOS Ventura 13.2 Apple Silicon
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: built from master

**Additional context**
Fix on its way.

**Comment by greglandrum** [comment]
To capture this here (from the discussion on #6042): The bonds appearing inside the letters is just due to the fact that a size has been specified for a canvas which is then used for the ACS1996 formatting. This is a mistake since the only way for those settings to work properly is to either have a giant canvas or use a "flexicanvas" where both the height and the width are set to -1.
