### ISSUE TITLE
EnumerateStereoisomers should remove non-abs enhanced stereo from results

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6045]
**Describe the bug**

```
In [7]: m = Chem.MolFromSmiles('O[C@H](Br)[C@H](F)C |&1:1,3|')

In [8]: set(Chem.MolToCXSmiles(x) for x in EnumerateStereoisomers.EnumerateStereoisomers(m))
Out[8]: {'C[C@@H](F)[C@H](O)Br |&1:1,3|', 'C[C@H](F)[C@@H](O)Br |&1:1,3|'}
```
Given that one of the purposes of `EnumerateStereoisomers()` is to give all the individual stereoisomers which are described by a set of StereoGropus, I believe that the results should no longer have the enhanced stereo.

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: all

**Comment by greglandrum** [comment]
@ricrogz , @d-b-w : I think we've talked about this in the past, but I want to check that you agree with me here.

**Comment by ricrogz** [comment]
I don't remember if we talked about this, but it makes sense to me.

**Comment by d-b-w** [comment]
I think that this is probably the right thing to do - stereoisomer enumeration is generating all the real structures possible...

I think that there is some use case where people want to know what the source molecule was after a long workflow, but I think that there are probably better ways to do that.

Fixing this will break RegistrationHash's hacky canonicalization of enhanced stereochemistry... But I assume that you're raising this issue because you intend to remove the stereogroups in enumeration when canonicalization also canonicalizes stereo groups.
