### ISSUE TITLE
Cyclobutyl group in a macrocycle triggers a stereo center

### ISSUE THREAD

**Issue by cdvonbargen** [rdkit/rdkit#6049]
**Describe the bug**
Adding a cyclobutyl group into a macrocycle causes the nitrogen to be treated as a stereo center.

**To Reproduce**
```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("O=S1(=O)C=CC=C2CCCCC3CC(C3)N21")
>>> [Chem.MolToSmiles(x) for x in Chem.EnumerateStereoisomers.EnumerateStereoisomers(mol)]
['O=S1(=O)C=CC=C2CCCCC3CC(C3)[N@@]21', 'O=S1(=O)C=CC=C2CCCCC3CC(C3)[N@]21']
```
The nitrogen isn't necessary, the following variation also treats the same position as a carbon as a stereo center:
```
>>> mol = Chem.MolFromSmiles("C1=CCC2C(=C1)CCCCC1CC2C1")
>>> [Chem.MolToSmiles(x) for x in Chem.EnumerateStereoisomers.EnumerateStereoisomers(mol)]
['C1=CC[C@@H]2C(=C1)CCCCC1CC2C1', 'C1=CC[C@H]2C(=C1)CCCCC1CC2C1']
```
**Screenshots**
<img width="223" alt="Screenshot 2023-02-02 at 2 19 16 PM" src="https://user-images.githubusercontent.com/9365596/216428868-4ea7d629-9ee7-4316-a032-e1f15fa8892f.png">

**Configuration:**
```
>>> rdkit.__version__
'2022.09.4-sch'
```

**Comment by greglandrum** [comment]
Here's what's going on in this one.
It's clear that a C in that position should be stereogenic: it has four different neighbors.
The condition for an N with degree three to be stereogenic is that it be in a ring of size 3 or be shared between at least 3 rings (In this case, the docs were actually useful to me in figuring this out, I *love* it when that happens! https://www.rdkit.org/docs/RDKit_Book.html#stereogenic-atoms-bonds). That last condition was added (PR #3958) in order to handle bridgehead atoms like the N here:
![image](https://user-images.githubusercontent.com/540511/216748951-1602a89e-5034-4d99-95ca-b884e80fcda8.png)

In this case the presence of the four membered ring means that the macrocycle actually counts as 2 rings (due to the symmetric paths around the 3 ring), so the N is in three rings, so it's considered stereogenic. If you make the four-ring a five-ring this goes away. If you make it a para-substituted six-ring it comes back:
![image](https://user-images.githubusercontent.com/540511/216749184-aa196598-309c-47ee-bc95-178897cc38f4.png)

So I think the problem here is that `queryIsAtomBridgehead()` is falsely identifying this N as a bridgehead.
