### ISSUE TITLE
Single atom or queries with hydrogens shouldn't trigger warning in mergeQueryHs

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#6119]
Very minor bug in mergeQueryHs

Example with no warning:

```
>>> pat = Chem.MolFromSmarts("[#6,#1]")
>>> pat2 = Chem.MergeQueryHs(pat)
>>> Chem.MolToSmarts(pat2)
'[#6,#1]'
```

Add a single carbon, get the warning:
```
>>> pat = Chem.MolFromSmarts("C[#6,#1]")
>>> pat2 = Chem.MergeQueryHs(pat)
[12:28:53] WARNING: merging explicit H queries involved in ORs is not supported. This query will not be merged
```

Note the lack of WARNING in the first example.

**Comment by dessygil** [comment]
I would like to give this one a try!

**Comment by greglandrum** [comment]
@dessygil this is pretty good one for beginners : it will require a bit of digging to understand how the query code works, but not too many code changes.

This is something that needs to be fixed in the C++ code, are you a C++ programmer?

**Comment by dessygil** [comment]
I have exposure to C but not C++, I'm learning C++ as we speak to be able to contribute.

**Comment by greglandrum** [comment]
> I have exposure to C but not C++, I'm learning C++ as we speak to be able to contribute.

Great, let me know when you are ready and I can try and point you to where you should be looking in the code

**Comment by dessygil** [comment]
I am ready, I just submitted a PR for the other bug I was looking at and now have more time to try this one! Where would you suggest I begin here?

**Comment by dessygil** [comment]
I think I have it figured out

IsQueryH in the file addHs.cpp should throw the warning for explicit H merge queries. IsQueryH returns false before it can throw this warning because of this line of code in the function

` if (atom->getDegree() != 1) {
    // only degree 1
    return false;
  }`

It should be changed to the following block of code to include unbonded Hs

` if (atom->getDegree() != 1 || atom->getDegree() != 0) {
    // only degree 1
    return false;
  }`

**Comment by dessygil** [comment]
I now see I solved the initial title. The warning thrown `merging explicit H queries involved in ORs is not supported. This query will not be merged` Shouldn't this be thrown for both C[C,H] and [C,H] because they are both explicit AtomOr H queries, or has the goal changed to get rid of the warning altogether in the situation and be able to Merge these types of queries?
