### ISSUE TITLE
Exact search showing false

### ISSUE THREAD

**Issue by sitanshubhunia** [rdkit/rdkit#6276]
**Describe the bug**
Exact search showing false

**To Reproduce**

For reference I have attached two mrv files.

[mol_1_mrv.txt](https://github.com/rdkit/rdkit/files/11171376/mol_1_mrv.txt)
[mol_2_mrv.txt](https://github.com/rdkit/rdkit/files/11171374/mol_2_mrv.txt)

From this marvin I am getting Chemaxon SMILES .

On that SMILES am querying below

select 'FC(F)(F)C(=O)[NH2+]CC1CNCO1 |lp:0:3,2:3,3:3,5:2,10:1,12:2,^1:6|'::mol@='FC(F)(F)C(=O)[NH2+]CC1CNCO1 |lp:0:3,2:3,3:3,5:2,10:1,12:2|'::mol;

**Screenshots**

As per marvin element analysis shown all are same 

![element_analysis_marvin](https://user-images.githubusercontent.com/840684/230400784-d917f704-5de7-4426-8751-756fb0679c99.png)

But when I am querying on postgresql, it's return false

select 'FC(F)(F)C(=O)[NH2+]CC1CNCO1 |lp:0:3,2:3,3:3,5:2,10:1,12:2,^1:6|'::mol@='FC(F)(F)C(=O)[NH2+]CC1CNCO1 |lp:0:3,2:3,3:3,5:2,10:1,12:2|'::mol;
 

 **Configuration :**

RDKit version:
select rdkit_version() --> [ 0.76.0 ]
select rdkit_toolkit_version() --> [2022.03.4]
OS: [e.g. Ubuntu 20.04]
postgres:12

**Comment by greglandrum** [comment]
Hi @sitanshubhunia : Your first input smiles specifies that the NH2+ has a radical electron on it and this information is not being removed (as it should be) when the molecule is imported. That radical is causing the two structures to not match each other.

Since the underlying problem is in the radical count not being cleared, I have created a separate issue:
https://github.com/rdkit/rdkit/issues/6370

Once that is fixed, I will try to remember to update this one.

**Comment by sitanshubhunia** [comment]
@greglandrum 

In the meantime, thank you for your kind attention and time.

**Comment by sitanshubhunia** [comment]
@greglandrum 

Hopefully there is a typo error regarding milestone **2923**_03_4

**Comment by greglandrum** [comment]
I believe that this is fixed on master, probably in #6842
I will confirm, but the fix should be in the 2024.03.1 release
