### ISSUE TITLE
Pre-condition Violation when using HasReactionSubstructMatch

### ISSUE THREAD

**Issue by victorsabanza** [rdkit/rdkit#6369]
**Describe the bug**
I'm trying to use the HasReactionSubstructMatch function to match a reaction template to a given reaction SMILES, but I'm getting an error when running the function with a simple example.

**To Reproduce**
```
from rdkit.Chem import AllChem
from rdkit.Chem.rdChemReactions import HasReactionSubstructMatch

smarts = '[c:1][O;D2:2][CH2:3]>>[c:1][OH:2].[CH3:3]'

rxn = AllChem.ReactionFromSmarts(smarts)

rxn_smiles = 'c1ccccc1OCCCC>>c1ccccc1O.CCCC'

rxn_smiles = AllChem.ReactionFromSmarts(rxn_smiles, useSmiles=True)

HasReactionSubstructMatch(rxn_smiles, rxn)
```

I get the following error:
```
RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 297 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2022.09.5
	BOOST: 1_78
```

**Expected behavior**
The function should return `True` as the reaction SMARTS and the reaction SMILES match.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5
 - OS: Linux
 - Python version (if relevant): 3.8
 - If you are not using conda: how did you install the RDKit?: pip

**Comment by greglandrum** [comment]
@victorsabanza what's going on here is confusing, but it is currently expected behavior.
Your SMARTS reaction include query features which check the number of Hs on an atom (the `[CH2]` in the reactants and `[CH3]` in the products), however the RDKit's normal molecule sanitization is not performed when you construct a reaction from either SMILES or SMARTS. This means that `rxn_smiles` does not have H counts calculated, and that leads to the exception.

The solution is to do sanitize the reactants and products:
```
In [35]: for m in rxn_smiles.GetReactants():
    ...:     Chem.SanitizeMol(m)
    ...:

In [37]: for m in rxn_smiles.GetProducts():
    ...:     Chem.SanitizeMol(m)
    ...:

In [39]: HasReactionSubstructMatch(rxn_smiles,rxn)
Out[39]: True
```
We could (and probably should) make this a bit easier.

As an aside: if you want to include sample input or output in a github issue or comment, you should enclose it in triple backwards quotes, not normal quotes. I've edited your post to do so.

**Comment by victorsabanza** [comment]
Thanks a lot for the explanation and the advice @greglandrum.
