### ISSUE TITLE
MolDraw2D: increasing padding results in the legend not being displayed

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6400]
**Describe the bug**
notice lack of legend:
![image](https://github.com/rdkit/rdkit/assets/540511/2f5b4758-a6d7-4c77-9664-da9dd0c2cc54)

**To Reproduce**
```
mol = Chem.MolFromSmiles('CCCOC')
d2d = Draw.MolDraw2DCairo(300,300)
dopts = d2d.drawOptions()
dopts.padding = 0.2 # default is 0.05
show_mol(d2d,mol,legend='padding')
```

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: release
 - OS: all

**Comment by DavidACosgrove** [comment]
It's a picky distinction, but the legend is being drawn, just in a zero-size font :-).  When looking at it, I had paused to wonder, should the padding go all round the image, including the legend?  If so, the easiest way to do this, that will probably make other stuff easier as well, might be to use a smaller drawing area within the canvas and offset it, since you've done all the hard work to make it possible to draw to an arbitrary position on the canvas.  It will take a bit of re-engineering, I think, but will probably repay the effort with easier maintenance later.  I'll set aside a bit of time to do it over the next week or so.

**Comment by greglandrum** [comment]
> It's a picky distinction, but the legend is being drawn, just in a zero-size font :-). 

silly me for missing that!

> When looking at it, I had paused to wonder, should the padding go all round the image, including the legend?

I think it makes sense for the padding to include the image. i.e. if the padding is 5%, then there is always a 5% border with nothing in it.
