### ISSUE TITLE
Alternating canonical SMILES produced

### ISSUE THREAD

**Issue by rhjohnstone** [rdkit/rdkit#6420]
**Describe the bug**
SMILES canonicalization alternates between two different outputs.

**To Reproduce**
```python
from rdkit import Chem

def canonicalize(smiles):
    return Chem.MolToSmiles(Chem.MolFromSmiles(smiles))

s1 = "O=C(C[C@]1(c2ccc(-c3ccc(F)cc3)cc2)C2CC3CC1CC(C2)[C@@H]3O)N1CC(O)C1"
s2 = canonicalize(s1)
s3 = canonicalize(s2)

print(s1 == s2, s1 == s3)
>>> False True
```

**Expected behavior**
Since `s1` might not be canonical smiles, I would expect at least `s2 == s3`, and that all future outputs are the same.

**Configuration (please complete the following information):**
 - RDKit version: `2023.03.1`
 - OS: MacOS Monterey
 - Python version: 3.9.16
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? `pip` via `pdm`

**Comment by ptosco** [comment]
The legacy stereochemistry perception code (default) has known issues.

If you switch to the new stereochemistry perception code the issue disappears.
Note that all stereochemistry will be stripped from the molecule upon canonicalization, since the adamantane has all bridgehead stereocenters undefined, and hence there is not enough information to unequivocally determine the stereochemistry at the centers that carry wedged bonds.
```
from rdkit import Chem, ForceField
from rdkit.Chem import rdDistGeom, rdForceFieldHelpers

Chem.SetUseLegacyStereoPerception(False)

def canonicalize(smiles):
    return Chem.MolToSmiles(Chem.MolFromSmiles(smiles))

s1 = "O=C(C[C@]1(c2ccc(-c3ccc(F)cc3)cc2)C2CC3CC1CC(C2)[C@@H]3O)N1CC(O)C1"
s2 = canonicalize(s1)
s3 = canonicalize(s2)
print(s1 == s2, s1 == s3)
False False
s2 == s3
True
s2
'O=C(CC1(c2ccc(-c3ccc(F)cc3)cc2)C2CC3CC1CC(C2)C3O)N1CC(O)C1'
```
However, if you provide a full stereochemical description of the adamantane, stereochemistry will be retained upon canonicalization:
```
s4 = 'O=C(C[C@@]1(c2ccc(-c3ccc(F)cc3)cc2)[C@@H]2C[C@@H]3C[C@H]1C[C@H](C2)[C@H]3O)N1CC(O)C1'
canonicalize(s4) == s4
True
```
