### ISSUE TITLE
Chem.SanitizeMol removes aromaticity tag from smarts Mol

### ISSUE THREAD

**Issue by HelloJocelynLu** [rdkit/rdkit#6658]
**Describe the bug**
When creating a `mol` object with MolFromSmarts, the aromaticity tag of atoms is removed by `Chem.SanitizeMol`.

**To Reproduce**
Before the sanitization, GetIsAromatic() returns True; After `Chem.SanitizeMol(mol)`, GetIsAromatic() returns False
```python3
mol = Chem.MolFromSmarts('a1aaaaa1')
for atom in mol.GetAtoms():
    print(atom.GetIdx(), atom.GetIsAromatic())
Chem.SanitizeMol(mol)
print('='*20)
for atom in mol.GetAtoms():
    print(atom.GetIdx(), atom.GetIsAromatic())
```
I can confirm that this issue does not occur if we remove `Chem.SanitizeMol(mol)` or if we have `mol = Chem.MolFromSmiles('c1ccccc1')`

**Expected behavior**
I would expect GetIsAromatic() should not change before & after sanitization:
```
0 True
1 True
2 True
3 True
4 True
5 True
====================
0 True
1 True
2 True
3 True
4 True
5 True
```

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/34988596/87818f5b-558c-44d0-a5dd-2ab162079634)

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2
 - OS: [e.g. Ubuntu 20.04]: Ubuntu 20.04 and MacOS Ventura 13.3.1 (a) 
 - Python version (if relevant): python 3.9.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? NA

**Additional context**

**Comment by bp-kelley** [comment]
I think you are asking a bit much from sanitization.  Sanitization really requires a physically reasonable molecule.

That being said, the RDKit is largely based on the daylight smiles model, so let's take a look at what you are really doing, first by converting your query to a molecule and then to a smiles string:

```
>>> from rdkit import Chem
>>> m = Chem.MolFromSmarts("a1aaaaa1")
>>> smi = Chem.MolToSmiles(m)
>>> print(smi)
*1:*:*:*:*:*:1
```

What this is converted to in smiles-land are dummy atoms connected by aromatic bonds.  In SMILES there is no concept of an aromatic dummy atom so this gets stripped.  However, if we read the smiles we just made back into a smarts pattern:

```
>>> pat = Chem.MolFromSmarts(smi)
>>> print(Chem.MolFromSmiles("c1ccccc1").HasSubstructMatch(pat))
True
```

It still matches aromatic atoms so all is good.  I think an important concept in SMARTS which is kind of the opposite in SMILES is that the matches are controlled by what you are explicitly set to, otherwise you still match.  I.e. if you don't say you are explicitly aliphatic or aromatic, you will match both.

**Comment by HelloJocelynLu** [comment]
Hi Brian,

Thank you for your explanation. Would you mind taking a look at [this discussion](https://github.com/rdkit/rdkit/discussions/6655#discussion-5544611), generally I want to keep some properties (such as aromaticity) in SMATRS.

Jocelyn
