### ISSUE TITLE
SpacialScore ignores undefined bond stereo

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#6957]
Based on this text from the [original paper](https://chemrxiv.org/engage/chemrxiv/article-details/64257af562fecd2a83add9c2) I would think that "2-butene" should give the same SPS as "cis-2-butene":

>SPS also accounts for the stereogenicity of an atom, where (pseudo)stereogenic tetrahedral carbons and atoms involved in a double bond with possible E and Z isomers are assigned 𝑠=2, otherwise, the term is equal to 1.

```
>>> from rdkit import Chem
>>> from rdkit.Chem.SpacialScore import SPS
>>> SPS(Chem.MolFromSmiles("CC=CC"), False)
22
>>> SPS(Chem.MolFromSmiles("C/C=C\\C"), False)
38
```

**Comment by greglandrum** [comment]
@apahl what's your take on this one?

**Comment by frog2000** [comment]
Thank you very much @jasondbiggs for finding this discrepancy in the scoring.
Indeed, compounds with the unspecified stereo at double bonds should give the same result as compounds with explicitly stated E/Z arrangements. In line with the ideas described for SPS, the lack of knowledge about the compound's configuration should not have impact on the compound's complexity.
In your example, both compounds should thus give the score of 38.

Axel (@apahl) and I already work on a potential fix.

**Comment by apahl** [comment]
Big thanks to @jose-manuel for pointing out that the call to the SPS function gives the correct result when `FindPotentialStereoBonds(mol)` is run after creating the mol object from SMILES and before calling the SPS function:

`rdmolops.FindPotentialStereoBonds(mol)`

(The `rdmolops` module can be imported from `Chem`).

The function assigns all potential stereogenic double bonds correctly to "STEREOANY", if they are not defined as E/Z, instead of them being "STEREONONE" after generating the mol from SMILES.

The question is whether we should add the call to `rdmolops.FindPotentialStereoBonds(mol)` to the SPS code or add a remark to the documentation of SPS, that the `rdmolops.FindPotentialStereoBonds(mol)` function should be called on the mol before calculating SPS.  
How is this handled with other descriptors?

**Comment by greglandrum** [comment]
Sorry I am slow here... I missed the notification

If the SPS function may behave incorrectly unless `FindPotentialStereoBonds()` is called, then it should copy the input molecule, call FindPotentialStereoBonds() on the copy, and then calculate the descriptor using the copy:
```
molCp = Chem.Mol(mol)
rdmolops.FindPotentialStereoBonds(molCp)
```
