### ISSUE TITLE
LocaleSwitcher drastically slows down GetProp

### ISSUE THREAD

**Issue by JLVarjo** [rdkit/rdkit#703]
After switching to 2015_09_2 release, I noticed slowliness in my runs. Managed to track it down to Dict::getVal, where some LocaleSwitcher has been recently added. Timings for the test code (below) are
29.53 seconds
with untouched 2015_09_2, and
1.05 seconds
after I commented out all four 'Utils::LocaleSwitcher ls;' lines from Dict.cpp.

I wonder if anyone can reproduce this, or might it be e.g. a locale-specific issue?

'

    mol=Chem.MolFromSmiles("Cn1cnc2n(C)c(=O)n(C)c(=O)c12") 
    for atom in mol.GetAtoms():
        atom.SetProp("FOO1", "BAR")
        atom.SetProp("FOO2", "BAR")
        atom.SetProp("FOO3", "BAR")
        atom.SetProp("FOO4", "BAR")
        atom.SetProp("FOO5", "BAR")
    for i in range(10000):
        for atom in mol.GetAtoms():
            atom.GetProp("FOO1")
            atom.GetProp("FOO2")
            atom.GetProp("FOO3")
            atom.GetProp("FOO4")
            atom.GetProp("FOO5")
'

**Comment by greglandrum** [comment]
Interesting.
I am able to reproduce some slowdown:
```
~ > locale
LANG=
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL="de_DE.UTF-8"
# This uses the current trunk:
~ > time python gprops.py 

real	0m2.021s
user	0m1.982s
sys	0m0.037s
~ > export LC_ALL=""
~ > locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
~ > time python gprops.py 

real	0m2.129s
user	0m2.084s
sys	0m0.038s
# conclusion 1: the actual setting of the locale value doesn't make any real difference

# now with the four instances of LocalSwitcher in Dict.cpp commented out:
~ > time python gprops.py 

real	0m1.108s
user	0m1.069s
sys	0m0.036s
~ > export LC_ALL="de_DE.UTF-8"
~ > time python gprops.py 

real	0m1.135s
user	0m1.097s
sys	0m0.036s
```

That's a factor of two, which is definitely real.

My usual (joke) response to this kind of problem is: Just use the "C" locale! But that is, of course, not actually helpful. :-)

I'm going to have to think about this a bit. The use of LocaleSwitcher is due to the fixes for #577. It could well be that when I made that fix I was a bit too broad with the application of the LocaleSwitcher.

**Comment by JLVarjo** [comment]
Quite a big difference on the slowdown factors? I'm running under Windows 10, btw: perhaps the cost of the std::setlocale operation is much higher there.

**Comment by bp-kelley** [comment]
LOCALE's are really painful especially dealing with external inputs and sending them to another locale.  I suggest not using them if possible.

I think part of the issue is that Set/GetProp as exposed to Python is string based which makes a lot of calls to boost::lexical_cast which IS locale aware in the global sense and locale is not thread safe anyway.  I suggest standardizing on C locale by not using a local aware function really anywhere internally to RDKit.  We had issues in OpenEye where we couldn't even read SDF files in germany for instance.

One potential solution is not to use LOCAL mainly because the point of using lexical_cast as far as I can tell is to get stuff into/from python.  One way to do this is through string streams (stack overflow example here of course) and we could replace boost::lexical_cast with rd_lexical_cast using something like the following:

```
std::string rd_lexical_cast<T>(const T&v) {
  return boost::lexical_cast<T>(v);
}

// specialize for floats/doubles
std::string rd_lexcal_cast(const double &v) {
 std::ostringstream oss;
 oss.imbue(std::locale::classic());
 oss.precision(std::numeric_limits<double>::digits10);
 oss<<v;
 return oss.str();
}

```

**Comment by greglandrum** [comment]
Though there may be a longer-term solution for this, given the complexity of the space, particularly where Java is concerned (*lots* of KNIME users with "weird" locales), I really am reluctant to mess around here.

I believe the locale switching code that is in use is "thread safe enough" (TM). There are certainly large numbers of people running it in multi-threaded mode in KNIME.

**Comment by bp-kelley** [comment]
I really don't think this is the case.  std::setlocale is global so it needs to be protected by mutexes for the duration of use.  I'm unclear how Java uses locale, actually.  

At the minimum, LocaleSwitcher should be protected with a global mutex:

```
std::mutex local_mutex;
class LocaleSwitcher {
 public:
  LocaleSwitcher() { 
     local_mutex.lock();
    std::setlocale(LC_ALL, "C"); 
  }
  ~LocaleSwitcher() { 
     std::setlocale(LC_ALL, ""); 
     local_mutex.unlock();
  }
};
```

Fixing lexical_cast however, removes this lock entirely.

**Comment by greglandrum** [comment]
Given the difficulty in testing these things and that we know that what is
currently there works (really, there are lots of people using the code in
a multi-threaded environment in KNIME), I am reluctant to make substantial
changes until we have a big block time and resources to do testing across
C++, Python, and Java (particularly KNIME across all 5 supported platforms).

Until then I think we have two choices: we can either leave the code as is
(rejecting the PR) and keep taking the performance hit, or we can do a
minimal change like what's proposed here.

>

**Comment by bp-kelley** [comment]
The fix doesn't make anything worse and I expect most Linux locales are actually "c" anyway so I tend to agree with you.  However we should flag this as an issue so we don't forget about it.

----
Brian Kelley

**Comment by rvianello** [comment]
for what is worth I would be fine with addressing the performance issue for now, but coming from a country where a weird locale is the norm (apart on my own machines) I'm not very much convinced by the idea of enforcing the C locale, especially if this limited the ability to process an input file encoded according to the locale configured in the user's environment. in addition, RDKit is a toolkit, and a similar choice should perhaps be delegated to the applications that use it.

looking at #577, I think maybe the python layer should instead use local.atof for parsing strings into floating point numbers, and behave consistently with lexical cast.

**Comment by bp-kelley** [comment]
Perhaps the problem is that this is the only way to get a double prop out of an rdkit dict.

Perhaps we should expose GetDoubleProp and avoid the middle man.

----
Brian Kelley

**Comment by bp-kelley** [comment]
@riccardo I'm not sure that we can easily use locale.atof in the C++/python layer,  the conversion from string->double is quite deep in the C++ layer.  It would perhaps be better to simply state:  all numeric values return by GetProp are converted into strings using the current locale, and then perhaps introduce the GetDoubleProp interface as a backup.

**Comment by rvianello** [comment]
if I understood the connection with #577 correctly, LocaleSwitcher was implemented to work around the behavior of the python builtin 'float' that (differently from boost::lexical_cast) is not locale-aware. I was wondering if replacing 'float' with 'locale.atof' (in the python layer alone) would have solved the issue.

**Comment by greglandrum** [comment]
Exactly. LocaleSwitcher was added to the GetProp interface because of #577,
which arose because lexical_cast is locale aware and the python float()
call is not.

LocaleSwitcher was being used before in the file parsers, which also use
lexical_cast. It was originally added to the RDKit to allow them to be able
to read floating point values from files when the locale was set to things
other than "C". There were problems reading SD files from within KNIME when
people were using locales where the decimal separator is ",".

**Comment by bp-kelley** [comment]
Apologies for being pedantic about this, but I do think that changing the locale is very problematic in the long run, especially for threaded programs.

So there are a issues here that I was confused by, so let me see if I have them:

 * sd file -> parse in different locale -> set "C" locale globally for the duration of the read  (sdfile reading/parsing is in C  (actually Fortran) locale

 * double -> setprop<double> -> python -> float(getprop()) broken getprop is set to system locale (get prop is string in python)

worse case that we can't solve:

 * double -> python -> setprop(float(double)) -> pickle -> C++ in non C locale -> broken

I sent a message to riccardo that didn't appear on the list.  I agree with him that we should pretty much do what the internal lexical_cast, strtod does, i.e. make it the Users problem :)  I suggested the following:

 1. GetProp<string> when returning a number always returns the number in the current locale
     which means python will need to use atof.  I think this makes good sense as I think it makes sense in     
     the context of  users and C++ users who have to deal with this anyway.

 2. expose Get/SetDoubleProp to python/swig that returns the stored double if possible so the user
    doesn't have to deal with the locale if not necessary.

This will revert the fix we made for Andrew (but I think he can handle it) and give an API point that is consistent and makes sense.  Both are easy to implement, I'll have a branch later this afternoon.

As for the SDFile parser, I expect we can hand roll a float parser/writer because we don't have to deal with infinity/exponents and the format is exactly defined:

```
  xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz
```

A side benefit is that it will probably parse a lot faster as well (I'm guessing 10-20%).  

However we still need to enforce SDData floats being written and read to use the C locale, I propose switching to:

```
  stringstream ss;
  ss.imbue( c_locale );
```

Which uses a non-global state.  I agree with Greg that this is a fairly large change and will probably take a while, but I'd be happy to look into it.

**Comment by bp-kelley** [comment]
It turns out there is a better way:

```
#include <string>
#define BOOST_LEXICAL_CAST_ASSUME_C_LOCALE 1
#include <boost/lexical_cast.hpp>
```

forces C locale in lexical casts without having to set the locale for the file under question.  I think this may be our winner.

**Comment by greglandrum** [comment]
That sounds great. Unfortunately, at least in my initial experiments, it doesn't seem to do anything, even when set globally.

**Comment by greglandrum** [comment]
Which is odd, because it certainly looks like it should.

**Comment by bp-kelley** [comment]
I'm having the same issue.  

As an aside, I added Get/SetDouble prop to atoms and bonds in commit @ 93f31d07cd4830a0b5abc0d740521d98376617d3

I'll push the same for molecules in a bit.

```
mol.GetDoubleProp("ddd")
```

which would have solved Andrews issue I think.
