### ISSUE TITLE
Rationalize attachment points

### ISSUE THREAD

**Issue by cdvonbargen** [rdkit/rdkit#7078]
**Is your feature request related to a problem? Please describe.**

Attachment points are represented in at least two ways -- either as properties on a parent atom as done in MDL, or as explicit dummy atoms with an _AP# property as done in extended SMILES. The request here is to rationalize how attachment points are both read/written in the RDKit. I would assume it makes the most sense to double down on the explicit representation as done with extended SMILES, in which case this request would be:

- on MDL read: expand molAttachPoint properties to explicit dummy atoms, cleanup the molAttachPoint on parents, and generate reasonable coordinates for the new dummy atoms
- on MDL write: collapse attachment dummies to molAttachPoint properties on parent atoms

Also to be clear: this request is likely to cause issues with backwards compatibility.

Something else discussed with Greg last week -- how should wedging operations treat attachment points? Because bond order and bond wedging doesn't impact how enumerations/decompositions operate (they simply indicate the place *where* to make the attachment, they don't specify bond type matching) I think we should make sure that attachment points are down-weighted as much as possible when wedging is assigned. A look through
https://github.com/rdkit/rdkit/blob/702f958621233b50c363d356820b353c7136ab41/Code/GraphMol/WedgeBonds.cpp#L263
it seems that lower atomic numbers are preferred, so it would be good to avoid situations when possible where wedging is applied to attachment points. Greg pointed out that it's probably not wise to entirely avoid wedging attachment points as there may be examples where IUPAC rules would make this unavoidable. But we should make sure we give dummies low priority. Which means there are two additional requests here:

- ensure dummy atoms have low priority in the wedging code
- if an attachment point dummy *IS* wedged on MDL write, we should *NOT* collapse it as to avoid loss of information

**Comment by greglandrum** [comment]
@cdvonbargen : I think we can solve this within the v2 API without having an impact on bacwkards compatibility: the v2 API has a `MolFileParserParams` class that we can add a "expandAttachmentPoints" option to in order to control the on-parse behavior. We can also add a v2 version of the writer (there isn't currently a v2 version of the writers) with a parameter object that includes a "collapseAttachmentPoints" option. We can even discuss enabling these options by default in the v2 API (though I'm a bit nervous about this)

This seems saner/safer than making a pretty significant backwards-incompatible change that's not reversible.

Sound reasonable?

**Comment by cdvonbargen** [comment]
Sounds good to me!
