### ISSUE TITLE
Some metal centers get radical electrons

### ISSUE THREAD

**Issue by cdvonbargen** [rdkit/rdkit#7122]
**To Reproduce**
```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("I[Nb](I)(I)(I)I")
>>> Chem.MolToCXSmiles(mol)
'I[Nb](I)(I)(I)I |^1:1|'
```
Similar examples
```
[Zn+]C1=CC=CC=C1 |^1:0|
O=[Ta](=O)O |^1:1|
Cl[La](Cl)Cl |^1:1|
```

**Expected behavior**
I would expect that these species wouldn't get radical electrons. @greglandrum suggested that we might be able to zero the number of radicals on anything that has a single default valence value of -1 as a way to address this.

**Comment by greglandrum** [comment]
It's worth linking this to #3330, because any fix here will affect/change the outcome of that.

**Comment by greglandrum** [comment]
After thinking about this a bit more and looking at #3330, here's my suggested solution:
- If the "metal" atom ("metal" here means anything with a default valence of -1) has no neighbors then it is assigned either 0 or 1 radical electrons based on whether it has an even or odd number of valence electrons. This was what the fix for #3330 was intended to do. 1 may not be the right answer (because we don't know if the thing is high- or low-spin), but 0 is DEFINITELY wrong if there is an odd number of electrons.
- If the "metal" atom has a bond to it, then it's assigned 0 radical electrons. This may or may not be correct, but there's no way to answer the question generally, so we follow the "don't make stuff up" principle.

**Comment by greglandrum** [comment]
@cdvonbargen @ricrogz we should figure out whether or not we believe this should end up in the 2023.09.5 release or wait for 2024.03.1.
Do either of you have a strong opinion?

**Comment by ptosco** [comment]
@greglandrum I have also seen undesired radicals popping up in depictions of lanthanum complexes, so I am in favor of your proposed fix, and I would be happy for it to land in the 2023.09.5 release.

**Comment by greglandrum** [comment]
@ptosco: the RDKit actually has valences for Al, so this PR will not affect those cases.

Can you share examples?

**Comment by ptosco** [comment]
@greglandrum I don't think it has valences for lanthanum:
```
57      La      2.07    1.69    2.5     138.906 3       139     138.9063533     -1
```

**Comment by greglandrum** [comment]
@ptosco uh, sorry, somehow I read that as Al

**Comment by ricrogz** [comment]
I think 2023.09.5 is fine for us too. We'll have enough time for tests and patches before our next release.

**Comment by cdvonbargen** [comment]
Ditto 2023.09.5

**Comment by greglandrum** [comment]
@ptosco are you good with 2023.09.5 too?
