### ISSUE TITLE
AddHs cip rank is declared <int> should be unsigned int?

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#717]
I don't know if boost::any cares deep down, but I think the following code:

```
            int cip = 0;
            tAtom->getPropIfPresent<int>(common_properties::_CIPRank, cip);
```

should probably be

```
            unsigned int cip = 0;
            tAtom->getPropIfPresent<unsigned int>(common_properties::_CIPRank, cip);
```

as cipRanks are unsigned.

The following causes a bad_any cast for me so I think it may be a real bug

```
#include <boost/any.hpp>

int main() {
  boost::any v((unsigned int)1);
  int vv = boost::any_cast<int>(v);
  return 0;
}
```

**Comment by greglandrum** [comment]
I agree that this is a bug, but while making the "easy" fix, I noticed that this code is actually never called.
This call: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/AddHs.cpp#L325
clears the CIP properties (which are tagged as computed here: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Chirality.cpp#L654) before that piece of code is ever reached. grrrrr.

We need to figure out what the consequences would be to removing _CIPCode from the list of computed properties. It's another topic, but this would fit into the idea of making those values attributes of the molecule instead of properties.

**Comment by DoliathGavid** [comment]
I'm +1 for turning the properties into actual attributes that can be enforced at compile-time. Though maybe the better approach is add these attributes to a subclass of ROMol.

**Comment by bp-kelley** [comment]
@greg Yeah, I found this "bug" when I mucked up the computed prop implementation in my working branch. 

As for stereo, a while ago I had made a packed structure for storing stereo into that I could dig up, I think there is some space savings we could make there.  One method is to use the stereo done on the molecule which is already used to verify stereo and use that to reset the cip codes.  In fact, we could do that for most atom based computed props, just mark them as perceived on the mol and kind of ignore the computed props.

@DoliathGavid In general I agree, however if we make all the atom properties concrete (cipcode is an atom prop) then each atom can get pretty large, using properties helps this situation. However, we ALWAYS add stereo information, so it is actually cheaper to make these concrete.

@greg I have worried a bit about typing and props, we could just have typedefs to help us out:

```
CIPCode_t cip;
m.getPropIfPresent(common_properties::CIPCode, cip);
```

but this is still opt-in.
