### ISSUE TITLE
BCUT2D throws an error when it should return NaN

### ISSUE THREAD

**Issue by j-adamczyk** [rdkit/rdkit#7265]
**Describe the bug**
When I use `BCUT2D` function on SMILES `[Li]F`, I get an error:
```
ValueError: ERROR: No Gasteiger Partial Charge parameters for Element: Li Mode:
```

**To Reproduce**
```
from rdkit.Chem import MolFromSmiles
from rdkit.Chem.rdMolDescriptors import BCUT2D

BCUT2D(MolFromSmiles("[Li]F"))
```

**Expected behavior**
NaN values for Gasteiger features. I don't believe that if we can't compute a part of a feature vector, it should always throw an error.

Additionally, based on other issues and discussions, e.g. [this one](https://github.com/rdkit/rdkit/discussions/5824), I assume that using separate BCUT descriptors actually does return NaN, not an error.

**Configuration (please complete the following information):**
 - RDKit version: 2023.9.5
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.11
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? pip

**Comment by thegodone** [comment]
This is not a bug metals have no charges. Envoyé de mon iPhoneLe 16 mars 2024 à 22:57, Jakub Adamczyk ***@***.***> a écrit :﻿
Describe the bug
When I use BCUT2D function on SMILES [Li]F, I get an error:
ValueError: ERROR: No Gasteiger Partial Charge parameters for Element: Li Mode:

To Reproduce
from rdkit.Chem import MolFromSmiles
from rdkit.Chem.rdMolDescriptors import BCUT2D

BCUT2D(MolFromSmiles("[Li]F"))

Expected behavior
NaN values for Gasteiger features. I don't believe that if we can't compute a part of a feature vector, it should always throw an error.
Additionally, based on other issues and discussions, e.g. this one, I assume that using separate BCUT descriptors actually does return NaN, not an error.
Configuration (please complete the following information):

RDKit version: 2023.9.5
OS: Ubuntu 22.04
Python version (if relevant): 3.11
Are you using conda? no
If you are not using conda: how did you install the RDKit? pip

**Comment by j-adamczyk** [comment]
I am not arguing that it should compute them, no charge message totally makes sense. However, [ComputeGasteigerCharges function](https://www.rdkit.org/docs/source/rdkit.Chem.rdPartialCharges.html) has `throwOnParamFailure` parameter exactly for this situation, which has default value `False`. So the default behavior is different in computing Gasteiger charges separately and when using them in BCUT2D.

So I think that:
1. This should be made consistent, i.e. BCUT2D should set either NaN or zeros for Gasteiger charges in those cases
2. BCUT2D should also have such a parameter to control this behavior

**Comment by j-adamczyk** [comment]
@thegodone the problem lies precisely here: https://github.com/rdkit/rdkit/blob/a6f0493fddad16f77db19b389cb107a86bddb7f4/Code/GraphMol/Descriptors/BCUT.cpp#L121C3-L121C50. `throwOnParamFailure`, the third argument, is hardcoded as `true`.

**Comment by bp-kelley** [comment]
I think the main problem is that there is no way to currently extract the ones that succeed.  I think this should remain the default but adding an option to not throw on failure is valid IMO.  Making it explicit means the user needs to check the return values.

**Comment by greglandrum** [comment]
My two cents on this one: If there's a clear error condition, like this one, I would rather that the descriptor calculator throw an explict exception with an informative message (as it does here) than simply returning NaN. 
It's easy enough, and much more explicit, for client code to catch the exceptions and insert whatever error-handling they think is appropriate.

**Comment by j-adamczyk** [comment]
@greglandrum so maybe I formulated this wrong: the problem is that the current code does not allow passing down the `throwOnParamFailure` parameter, which is hardcoded. As it is currently, I have to reimplement the whole BCUT2D from scratch in Python, just to pass this one parameter down to `computeGasteigerCharges`. I think this issue should be open, and instead maybe changed to adding this parameter to BCUT2D. The default behaviour should be as is, I agree, but this should be configurable.
