### ISSUE TITLE
Incorrect number of rings from GetSymmSSSR

### ISSUE THREAD

**Issue by diogomart** [rdkit/rdkit#7482]
For two molecules that are topologically similar to adamantane, and look like tetrahedrons from the graph perspective, I expect 4 rings from `Chem.GetSymSSSR()`, but for tetrahedron_a I get 3.

```python
from rdkit import Chem

tetrahedron_a = Chem.MolFromSmiles("C1CC2CCCC3CCC(C1)CCC(CC2)CC3")
tetrahedron_b = Chem.MolFromSmiles("C1CC2CCCC3CCC(C1)CCC(CC2)COC3")

print("length of Symm SSSR for tetrahedron A:", len(Chem.GetSymmSSSR(tetrahedron_a)))
print("length of Symm SSSR for tetrahedron B:", len(Chem.GetSymmSSSR(tetrahedron_b)))
```

output:
```
length of Symm SSSR for tetrahedron A: 3
length of Symm SSSR for tetrahedron B: 4
```

rdkit 2024.03.2, conda-forge, linux, python 3.12

**Comment by greglandrum** [comment]
I believe the current behavior is right, but please correct me if I've missed something and we can reopen this.
Your first structure has 4 rings, which are of size 9,10,10,11. Since there are only 3 SSR rings (20 bonds - 18 atoms + 1), the ring of size 11 is not included.
The second structure has 4 rings, which are of size 10,10,11,11. There are still only 3 SSR rings (21 bonds - 19 atoms + 1), but you get both of the 11 rings due to symmetrization.

**Comment by diogomart** [comment]
Honestly, I'm not sure. I read the following in the cookbook:
>the SSSR for cubane only contains 5 rings, even though there are “obviously” 6.

and `GetSymmSSSR` returns 6 rings for cubane, so I just assumed it would always return four rings for a "tetrahedron" like molecule.

**Comment by diogomart** [comment]
Thank you for looking into it, and for clarifying the expected output of `GetSymmSSSR`
