### ISSUE TITLE
AllChem.EmbedMolecule returns -1

### ISSUE THREAD

**Issue by hxu105** [rdkit/rdkit#7552]
Howdy,

I want to get the 3D conformation information for any given molecule; however, some molecules fail to produce the conformer. Following is the code that reproduces the issue.

`from rdkit import Chem`
`from rdkit.Chem import AllChem`
`sample_smiles = 'O=CCC1OC2COC12'`
`mol = Chem.AddHs(Chem.MolFromSmiles(sample_smiles))`
`AllChem.EmbedMolecule(mol) # -1`

If the molecule can generate conformation information, `AllChem.EmbedMolecule()` would return 0; I have identified many smiles/molecules that result in -1 when calling `AllChem.EmbedMolecule(mol)` , you may find some of those smiles in the picture below.

![image](https://github.com/rdkit/rdkit/assets/40327643/bab1a067-2e7d-492e-b4fc-782ab9260f5e)

Appreciate any suggestions!

**Comment by jasondbiggs** [comment]
You could consider this as a feature instead of a bug, since it allows you to filter out these SMILES from your dataset.  You can see from the pictures that they have a lot of ring strain with all of those 90-degree angles:

<img width="289" alt="image" src="https://github.com/rdkit/rdkit/assets/16337306/0dd8bcea-72fa-4e0a-b112-905e7a568dec">

If you don't consider it a feature, you could experiment with the various [options for EmbedMolecule](https://www.rdkit.org/docs/source/rdkit.Chem.rdDistGeom.html#rdkit.Chem.rdDistGeom.EmbedMolecule) - in particular try turning off `useBasicKnowledge`

**Comment by hxu105** [comment]
Thanks, but I tried to set `useBasicKnowledge=False` and other boolean arguments to False, and none of the combinations will return 0 when calling `AllChem.EmbedMolecule()`

**Comment by greglandrum** [comment]
I agree that we should probably be able to generate something for these molecules.
As an FYI: it is now possible to get more information about why conformer generation is failing:
https://greglandrum.github.io/rdkit-blog/posts/2023-05-17-understanding-confgen-errors.html
