### ISSUE TITLE
Stub files contain duplicate argument names

### ISSUE THREAD

**Issue by nielskm** [rdkit/rdkit#7583]
The stub for `Chem.rdMolDescriptors.PythonPropertyFunctor.__init__` contains two arguments named `self`. This naturally makes type checkers complain.

**Configuration**
 - RDKit version: 2024.3.1
 - OS: Ubuntu 22.04
 - Python version: 3.12.4
 - How did you install the RDKit? From PyPI using pip

**Comment by j-adamczyk** [comment]
+1, this is blocking RDKit version update for [scikit-fingerprints](https://github.com/scikit-fingerprints/scikit-fingerprints)

**Comment by greglandrum** [comment]
My two cents: the stubs are a nice-to-have that can make life easier. They are not guaranteed to be correct and are not necessary for correct use of the RDKit. I am not willing to commit to fix every possible stub problem going forward into the future.

If a problem with the stubs is going to cause your CI builds to fail, then you probably ought to look into updating the way your CI builds work.

**Comment by coltonbh** [comment]
More than making type checkers complain, this actually causes them to error and exit! Preventing all further type checking of a project!

My error:

```sh
/home/cbh/.cache/pypoetry/virtualenvs/qcio-RA1cVAvH-py3.8/lib/python3.8/site-packages/rdkit-stubs/Chem/rdMolDescriptors.pyi:247: error: Duplicate argument "self" in function definition
```

This refers to this line of code:

```python
    def __init__(self, self: typing.Any, name: str, version: str) -> None: # NOTE DOUBLE self HERE!
        """
            C++ signature :
                void __init__(_object*,_object*,std::string,std::string)
        """
```

I believe this is there the function is registered on the C++ side: https://github.com/rdkit/rdkit/blob/cba05a9b3a4fe38f50100b5cc5d17890517be526/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp#L1627

**Comment by j-adamczyk** [comment]
@coltonbh yeah, this will make mypy, pyright and any other type checker error, since they require type annotations recursively. There are ways to disable this, e.g. you can configure mypy to not check site-packages at all, but this will work globally for all packages.

@greglandrum if the stubs are core part of RDKit, and not `rdkit-stubs` (which I never had problems with before), I quite heavily disagree with this policy. The intended purpose of type checkers for any dynamically typed language, including Python, is not only to reduce the number of bugs, but also to enhance code security. This is why strict type checking for Python is enforced in many companies for many projects, e.g. Microsoft (pyright), Meta (pyre), also many Google projects (mostly mypy), and also where I work. Type checking is a first smoke test, along with code style checks and security scans, even before running the actual unit and integration test. This is the best we can do with dynamic languages, and can't switch from Python due to DS and ML applications.

In `scikit-fingerprints` (and any other projects where I use RDKit), we use pre-commit hooks and require all checks to pass even to make *any single Git commit*, even locally, and this is considered a good practice for Python. Relatively modern, but still, definitely best practice. `mypy`, along with `bandit` (code vulnerability scans) and `safety` (dependency vulnerability scans) are the first line of defense. For those reasons, I want (and implement this) not only CI to fail when there are problems with typing, I want my local Git to block and complain. So typing is absolutely much more than "just documentation".

My current solution was to remove type checking for all site-packages. However, I kindly request you to reconsider this policy.

**Comment by bddap** [comment]
This should be fixable by changing https://github.com/rdkit/rdkit/blob/cba05a9b3a4fe38f50100b5cc5d17890517be526/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp#L1628

to

```c++
          python::args("callback", "name", "version")))
```

[Boost docs seem to suggest](https://www.boost.org/doc/libs/1_85_0/libs/python/doc/html/reference/high_level_components/boost_python_init_hpp.html#high_level_components.boost_python_init_hpp.example) omitting the `self` arg when using `python::init` but it looks like the standard in rdkit it to name self explicitly. So maybe this version would be better received:

```c++
          python::args("self", "callback", "name", "version")))
```

**Comment by greglandrum** [comment]
> 
> [Boost docs seem to suggest](https://www.boost.org/doc/libs/1_85_0/libs/python/doc/html/reference/high_level_components/boost_python_init_hpp.html#high_level_components.boost_python_init_hpp.example) omitting the `self` arg when using `python::init` but it looks like the standard in rdkit it to name self explicitly. So maybe this version would be better received:
> 
> ```c++
>           python::args("self", "callback", "name", "version")))
> ```

Yeah, I think this would do it.
@ptosco added the "self" arguments when he wrote the code to create the stubs and I believe that was specifically because of the stubs.

**Comment by ptosco** [comment]
Sorry for the delay in replying to this thread (I am on a cycling holiday and have little time). I’ll look into applying the suggested fix over the next 2-3 days.

**Comment by greglandrum** [comment]
> Sorry for the delay in replying to this thread (I am on a cycling holiday and have little time). I’ll look into applying the suggested fix over the next 2-3 days.

@ptosco no worries! Enjoy your holidays!

**Comment by jhirshman** [comment]
upvoting this issue this is breaking out ability to upgrade

```
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/rdkit-stubs/Chem/rdMolDescriptors.pyi:247: error: Duplicate argument "self" in function definition
```

**Comment by UnixJunkie** [comment]
@coltonbh Is there a way to tell mypy to ignore the rdkit.Chem module?
As a workaround, because if you are working w/ an old version of rdkit, you need a workaround for mypy even if a more recent rdkit is fixed.
What I found online about a mypy.ini or a pyproject.toml file doesn't work.
```python
from rdkit import Chem # type: ignore
```
sadly also doesn't work.

**Comment by coltonbh** [comment]
@UnixJunkie I installed the `rdkit-stubs` package and this "fixes" the problem but it's really not a fix! It's simply causing `mypy` to lookup definitions in a separate package that don't necessarily correspond to the same function signatures as `rdkit`. It's a hack, but your `mypy` will stop exiting with an error code. :shrug:
