### ISSUE TITLE
MinimalLib Build Issue

### ISSUE THREAD

**Issue by Suganesh-repo** [rdkit/rdkit#7714]
**Describe the bug**

was trying to build the MinimalLib and ran into a build fail with this error:

Seems like an issue with rapidjson.

rdkit-temp/src/rdkit/External/rapidjson-1.1.0/include/rapidjson/document.h:319:82: error: cannot assign to non-static data member 'length' with const-qualified type 'const SizeType' (aka 'const unsigned int')
     [exec]   319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
     [exec]       |                                                                           ~~~~~~ ^
     

**Configuration (please complete the following information):**
 - RDKit version:  2024.03.3
 - OS: macOS version 14.3.1 (23D60)

**Comment by ptosco** [comment]
@Suganesh-repo This issue has already been fixed in `master`.
If you apply to `Code/MinimalLib/docker/Dockerfile` the last block in this patch:
[https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7550.diff](https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7550.diff)
you will be able to build MInimalLib.
I am therefore closing this bug.
