### ISSUE TITLE
MergeQueryHs explicit H warning when no explicit Hs were actually used

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#868]
I'm assuming that the following smarts actually doesn't have an explicit H

    Chem.MergeQueryHs(Chem.MolFromSmarts("C-[O-,OH]"))
   [20:12:40] WARNING: merging explicit H queries involved in ORs is not supported. This query will not be merged

Description 

    * idx 0
    AtomAnd
      AtomAtomicNum 6 = val
      AtomIsAliphatic 1 = val
    
    * idx 1
    AtomOr
      AtomAnd
        AtomAnd
          AtomAtomicNum 8 = val
          AtomIsAliphatic 1 = val
        AtomFormalCharge -1 = val
      AtomAnd
        AtomAnd
          AtomAtomicNum 8 = val
          AtomIsAliphatic 1 = val
        AtomHCount 1 = val

Interestingly, removing the C- doesn't have the error:

    Chem.MergeQueryHs(Chem.MolFromSmarts("[O-,OH]"))

Description:

    * 0
    AtomOr
      AtomAnd
        AtomAnd
          AtomAtomicNum 8 = val
          AtomIsAliphatic 1 = val
        AtomFormalCharge -1 = val
      AtomAnd
        AtomAnd
          AtomAtomicNum 8 = val
          AtomIsAliphatic 1 = val
        AtomHCount 1 = val

**Comment by bp-kelley** [comment]
@greglandrum  I think this is a bug, should I add the "bug" label and start hunting it down?

**Comment by greglandrum** [comment]
The warning occurs because mergeQueryHs() is being called and there's an atom with degree higher than one that has an H query and an OR query.

It doesn't really need to show up since none of the neighbors of the O are actually Hs.

A fix to avoid the unnecessary warning would be to check in `isQueryH()` for a neighbor that actually is an H before showing the warning. This would be a bit slower, but this code likely isn't on the critical path for most applications.

**Comment by bp-kelley** [comment]
Here are some examples from the internal Brenk set that all have the same pathology.

Brenk pattern #29 [SX3](=O)[O-,OH]
Brenk pattern #31 S(=O)(=O)[O-,OH]

# this one should give the warning:
Brenk pattern #46 C(=O)O[C,H1].C(=O)O[C,H1].C(=O)O[C,H1]

Brenk pattern #65 c1c([OH])c([OH,NH2,NH])ccc1


Brenk pattern #94 [OH]c1ccc([OH,NH2,NH])cc1
