### ISSUE TITLE
Isotope information not affecting chirality

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#90]
``` python
In [11]: Chem.MolFromSmiles('C[C@H](F)[13CH3]').Debug()
Atoms:
    0 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
    1 6 C chg: 0  deg: 3 exp: 3 imp: 1 hyb: 4 arom?: 0 chi: 0
    2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
    3 6 C chg: 0  deg: 1 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 iso: 13
Bonds:
    0 0->1 order: 1 conj?: 0 aromatic?: 0
    1 1->2 order: 1 conj?: 0 aromatic?: 0
    2 1->3 order: 1 conj?: 0 aromatic?: 0
```

How this one has managed to slip under the radar for so long is a mystery

**Comment by adalke** [comment]
I have an fragmentation algorithm which uses "*" as dummy atoms. To test it, I placed '[100U]", "[101U]", and "[102U]" atoms at the end of my cuts, and recanonicalized it. To my surprise, sometimes the atoms were in the wrong order.

The reason why is that the fix for this bug makes the valid chemical assumption that the isotope will never be 8 below the most common isotope for a given atomic number, and if that happens its corresponding invariant gets set to 0. Since 100 and 101 are well under 238, both get assigned the same invariant of 0.

Looking at the code, I realize that isotopes are also considered the same if they are larger than the most common value and differ by a multiple of 16. For example:

    >>> Chem.CanonSmiles("c1ccc([C@H]([32*])[16*])cc1")
    '[16*]C([32*])c1ccccc1'
    >>> Chem.CanonSmiles("c1ccc([C@H]([31*])[16*])cc1")
    '[16*][C@@H]([31*])c1ccccc1'

Also, "[15*]" is treated the same as "[*]"

    >>> Chem.CanonSmiles("c1ccc([C@H]([*])[14*])cc1")
    '[*][C@H]([14*])c1ccccc1'
    >>> Chem.CanonSmiles("c1ccc([C@H]([*])[15*])cc1")
    '[*]C([15*])c1ccccc1'
    >>> Chem.CanonSmiles("c1ccc([C@H]([*])[16*])cc1")
    '[*][C@H]([16*])c1ccccc1'

I do not believe this is expected behavior, but "expected" is a bit meaningless as the molecular graph gets further away from realistic chemistry.

While I would prefer to have 8 bits of freedom in how I label atoms instead of 4, I can easily fix my code to work within the existing limitations. I also don't think any of my previous code will break because of this.

Improving this is not a high urgency feature request.

**Comment by greglandrum** [comment]
Though this may be something of an odd case, a quick scan through the code doesn't make me think that it would be any problem to provide 8 bits here.
Created #803 to followup.
