### ISSUE TITLE
would it be interesting to change the output of GetProp("_CIPCode") to "" is HasProp("_CIPCode) is False?

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#947]
currently GetProp return an error  when there is no "_CIPCode" property for an atom.

I would like to know why we need to call 2 functions (Has then Get) + am if condition to get the final CIPCode of an atom ?

It' would be simpler to just return an empty string when there is no "_CIPCode" ?

A related question to the current Stereochemistry Chirality behaviour: Is our atom CIPCode can handle the case where the Sp3 is not assign in the smile for racemic mixture ? 

It's a interesting info to use in datamining model for NMR perspective to know if we have “homotopic”, “enantiotopic”, and “diastereotopic” protons.

**Comment by greglandrum** [comment]
The property isn't set on non-chiral atoms because non-chiral atoms don't have a CIP Code. 
As for having a single call: It's more efficient to check for the existence of the property first and then to actually get the value for the few cases where it's actually set. Setting an empty property on every atom would be very inefficient.

To the second part of your question:
If you want to check whether or not chirality is possible at a center, you can use the `_ChiralityPossible` property. Here's a short Python demonstration:
```
In [7]: m = Chem.MolFromSmiles('CC(F)(Cl)Br')

In [8]: [x.HasProp("_ChiralityPossible") for x in m.GetAtoms()]
Out[8]: [0, 1, 0, 0, 0]
```

If you just want a list of all the chiral centers or possible chiral centers in the molecule, this function (usable directly from Python but easily translatable into other things if you aren't using Python) shows how:
https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/__init__.py#L62

**Comment by thegodone** [comment]
On peut avoir accès aussi au cipcode non encode dans le smile

Envoyé de mon iPhone

**Comment by thegodone** [comment]
Thanks for those ideas
