### ISSUE TITLE
3-D generation of benzoquinone in macrocycle

### ISSUE THREAD

**Issue by cowsandmilk** [rdkit/rdkit#989]
We do some macrocycle 3-D generation.

One of the molecules is geldanamycin. That has a benzoquinone in a macrocyclic ring. This benzoquinone should be flat, giving you a plane for the atoms in the ring and the oxygens sticking off.

The structure produced was correct in 2015.09.2 , the new 2016.03.* releases generate something that isn't flat. If you produce a structure for just a benzoquinone (without the macrocycle), it works in both cases.

I git bisected it down to having broken in e5311fa

The meaningful change in that commit is a check for ring size <= 8 in setting the ring angle. This actually matches the fact that this issue only happens in macrocycles, since the atoms are not just in a 6-membered ring, but also in a ring > 8 atoms.

I've included a zip with my code and mol files output for e5311fa (first bad commit) and 7902637 (last good commit)

[rdkit_macrocycle.tar.gz](https://github.com/rdkit/rdkit/files/382624/rdkit_macrocycle.tar.gz)

**Comment by greglandrum** [comment]
Distance geometry can have problems with planarity of aromatic systems. One straightforward solution to this is to include Sereina's "Basic Knowledge" terms in the embedding:
```
m = Chem.MolFromSmiles('CO[C@H]1C[C@H](C)CC2=C(OC)C(=O)C=C(NC(=O)\C(C)=C\C=C/[C@H](OC)[C@@H](OC(N)=O)\C(C)=C\[C@H](C)[C@H]1O)C2=O')
mh = Chem.AddHs(m)
mh2 = Chem.Mol(mh)
AllChem.EmbedMolecule(mh2,useBasicKnowledge=True,useRandomCoords=True,randomSeed=0xf00d)
```
Here's the conformation that generates (looking edge-on to the bezoquinone):
![image](https://cloud.githubusercontent.com/assets/540511/17126361/cf38de6e-52fc-11e6-9ad8-5bd807bf8b15.png)

The basic knowledge terms are described, along with the experimental torsion parameters (which don't help here), in this publication: http://pubs.acs.org/doi/abs/10.1021/acs.jcim.5b00654
and also here: https://github.com/rdkit/UGM_2015/blob/master/Presentations/ETKDG.SereinaRiniker.pdf

I used the `useRandomCoords` argument here to modify the embedding behavior (instead of using a randomly generated distance matrix and embedding that, the algorithm uses a random set of initial coordinates and then minimizes using a force-field that enforces the distance constraints). I believe this is helpful for macrocycles.

**Comment by greglandrum** [comment]
You have a comment in your script: `In my experience, rdkit MMFF minimization with hydrogens is wrong`
Can you provide a bit more detail around that?

**Comment by cowsandmilk** [comment]
Testing stuff now, that comment is false, I thought about removing it, but yesterday, I swear I was still getting better structures without hydrogens than with; today, that's not the case. So... now, I'm very confused. If I can come up with a case that clearly demonstrates an actual problem, I'll let you know.

**Comment by greglandrum** [comment]
Ok, please do let me know if you can reproduce that. It really shouldn't happen.
